-- BEAM CONVERSION: a projectile weapon fires LAS-13 Trident pulses (docs/beam-conversion.md;
-- research/docs/beam-conversion-coverage-F5FEE03DCFDB.md, research/docs/beam-conversion-add-layout-F5FEE03DCFDB.md;
-- domains/beam_conversion.lua, generated by scripts/generate_beam_conversion.py). The productised form of the
-- live-proven experiments (runtime/experiment_liberator_beam.lua, runtime/experiment_beam_swap.lua and
-- runtime/experiment_beam_table.lua, kept unchanged as the proven fallbacks for their proofs), written through
-- hd2.ensure / transactions on hd2.weapon(name):beam_conversion() (domains/beam_conversion_writes.lua).
-- Two LAYOUTS (the catalogue picks one per weapon: domains/beam_conversion.lua weapon.layout):
--   ADD (the default where supported): the weapon KEEPS ProjectileWeapon (321) and GAINS BeamWeapon (270), so every
--     machine has the ProjectileWeapon instance the game's network apply looks up (multiplayer: runtime/beam_
--     conversion_sync.lua, identical conversions only). Per root, in this order (restore in reverse):
--       1. its BeamWeapon index row (as below);
--       2. its OWN unique-owner ProjectileWeapon record: +0 (the projectile type) -> 0, so every projectile shot ends
--          at the game's empty-magazine exit before it fires anything; on a heat weapon also +8 (the rate) -> the
--          heat bound of its pulse (M.heat_projectile_rate), so the kept projectile path adds no heat of its own;
--       3. chamber magazines (as below);
--       4. its entity map row's list POINTER (+8) -> its slot in ONE Runtime-owned, never-freed, read-only block of
--          grown lists (its file list plus 270, sorted), then its COUNT (+16) -> N + 1. Nothing else of the entity map
--          is written: the file's packed list and every neighbour stay byte-identical (core/owned_tables.lua lets the
--          catalogue accept exactly this pointer, count and content).
--   SWAP (the rest, and the fallback without a list block): per root, in this order (restore in reverse):
--       1. its BeamWeapon index row (record index, then key) in the table the game reads: the first empty row on its
--          probe path (home = resource mod 46, +1 with wrap). A restore removes the row with linear-probing deletion
--          (Knuth's algorithm R): a later converted row whose probe crossed the freed row moves into it before the
--          last vacated row is cleared, so every lookup finds its row at every step; a vanilla row never needs to move
--          (vanilla rows never cross a vanilla-empty row) and the module fails closed if one would;
--       2. its membership list: ProjectileWeapon (321) out, BeamWeapon (270) in, sorted, the same count, the pointer
--          unchanged (one 4-aligned window); its ProjectileWeapon row stays (the round spend reads it);
--       3. chamber magazines only (WeaponMagazine +156 = 1, a record the weapon owns alone): +156..+159 -> 0, the 40-K
--          Meltagun's no-chamber model (only a ProjectileWeapon instance fills a chamber; under the add layout a
--          chamber filled with type 0 would refuse to fire).
-- Two BeamWeapon table paths, never mixed:
--   OWNED (the default): a Runtime-owned, never-freed copy of the BeamWeapon table (records 0..23 byte-identical to the
--     file, then one record per catalogued weapon, each a copy of the Trident's record 18), made live by ONE aligned
--     8-byte store into slot 270; rows go into the copy. Each weapon has its OWN record: its own rate of fire (+104),
--     beams per pulse (+108) and pulse length (+112). The last restore puts the slot back (when no record 0..23 of the
--     copy drifted: a typed write made while the copy was live would otherwise be lost).
--   SHARED (the fallback when the owned table is unavailable: a pin, the adapter, the copy budget): the file table's
--     one unowned record 23 := the Trident's record 18, rows in the file's own table; every converted weapon shares
--     it, so per-weapon settings other than the Trident's are refused on this path.
-- Every call re-proves the pins, re-derives every address and checks every target; any third state of a table, a row,
-- a list, a record or a magazine byte is FOREIGN and refused (another mod: True Lasgun Beam Overhaul moves this table
-- and grows the Sickles' and the Sai's lists).
-- Gates (fail closed): ZERO live instances of every root written, at the write AND at the restore (the descriptor
-- census: ship previews, the armory, the loadout, pickups, other players' weapons); for an apply with another player
-- present, the swap layout refuses (NOT_SOLO) and the add layout needs every member to hold the identical conversion
-- already (NOT_AGREED); the Trident's package resident (the request's asset dependency loads and holds it). A busy
-- gate is TARGET_UNAVAILABLE, so a transaction retries and an ensure with `recover` waits until it is clear.
-- SWAP only: a weapon spawned while converted may leave a ProjectileWeapon private copy nothing removes (a default
-- ammunition or muzzle delta that patches ProjectileWeapon): RESTART THE GAME after using it (logged, and in status).
if rawget(_G,'jit')then jit.off(true,true)end
local world_module=require('hd2runtime/runtime/event_world')
local log_module=require('hd2runtime/runtime/log')
local edits=require('hd2runtime/core/reviewed_edits')
local owned=require('hd2runtime/core/owned_tables')
local b=require('hd2runtime/core/bytes')
local profile=require('hd2runtime/schemas/current')
local C=require('hd2runtime/domains/beam_conversion')
local CT=require('hd2runtime/domains/component_tables')
local unpack=unpack or table.unpack
local M={}
M.VERSION='1.1.0'   -- 1.1: the add layout
M.OWNER='HD2Runtime beam conversion'
M.PATHS={owned='owned table',shared='shared record'}
M.ACKNOWLEDGEMENT='allow_component_swap'
local PRIVATE,COMMIT,READONLY,READWRITE,PAGE=0x20000,0x1000,0x2,0x4,4096
local BW,MG,MZ,PJ,L,LS=C.beam,C.manager,C.magazine,C.projectile,C.copy,C.lists
local DONOR=b.unhex(C.trident.recordHex)            -- the Trident's record 18 (the reviewed copy source)
local VANILLA_ROWS=b.unhex(BW.vanillaRowsHex)       -- the file table's 46 index rows as reviewed
local VANILLA_RECORD23=b.unhex(BW.vanillaRecord23Hex)
local ZERO8,ZERO16=string.rep('\0',8),string.rep('\0',16)
local STATE_KEY='HD2RuntimeBeamConversionV1'        -- survives a module reload: the copy outlives every Lua module
local proven={}
local hooks={}

local SETTING,SETTINGS_FROM,SETTINGS_TO={},nil,nil
M.SETTINGS={}
for _,s in ipairs(C.settings)do
    SETTING[s.id]=s;M.SETTINGS[#M.SETTINGS+1]=s
    SETTINGS_FROM=math.min(SETTINGS_FROM or s.offset,s.offset);SETTINGS_TO=math.max(SETTINGS_TO or 0,s.offset+4)
end
local BY_NAME,BY_RESOURCE,RECORD_OF={},{},{}
for _,w in ipairs(C.weapons)do
    BY_NAME[w.name]=w
    for _,root in ipairs(w.roots or{})do BY_RESOURCE[root.resource]={weapon=w,root=root}end
end

local function session()
    local s=rawget(_G,STATE_KEY)
    if not s then s={used=false,copies=0,join_warned={}};rawset(_G,STATE_KEY,s)end
    return s
end
local function log(text)log_module.emit('BEAM CONVERSION: '..text)end
local function clean(why)return(tostring(why):gsub('^%[string "[^"]*"%]:%d+: ',''):gsub('^[^%s:]+:%d+: ',''))end
local function fail(text)error(text,0)end
local hex=b.hex
local function u64(value)
    local lo=value%4294967296
    return b.encode(lo,'u32')..b.encode((value-lo)/4294967296,'u32')
end
-- resource '0x...' -> {lo, hi} and its 8 little-endian key bytes.
local function key_bytes(resource)return b.unhex(resource:sub(3)):reverse()end
local TWO32=4294967296
local function home(resource,capacity)
    local hi,lo=tonumber(resource:sub(3,10),16),tonumber(resource:sub(11,18),16)
    return((hi%capacity)*(TWO32%capacity)+lo%capacity)%capacity
end
M.home=home

------------------------------------------------------------------------------------------------------- catalogue --
function M.catalogue()return C end
function M.weapon(name)return BY_NAME[name]end
-- The converted-record index of a weapon in the owned copy (records 24..).
function M.record_of(name)local w=BY_NAME[name];return w and w.record end

---------------------------------------------------------------------------------------------------------- proofs --
local function prove(world)
    local key=world.key
    if proven[key]==true then return true end
    if proven[key]then return nil,proven[key]end
    local why
    if C.source.gameDllSha256~=profile.dll_sha or CT.source.gameDllSha256~=profile.dll_sha then
        why='the beam conversion research covers another game.dll build'
    end
    local lists={C.pins,CT.pins,CT.lookups[BW.component]or{},CT.lookups[PJ.component]or{},CT.lookups[MZ.component]or{}}
    for _,list in ipairs(lists)do
        for _,pin in ipairs(list)do
            if not why and not world.view.proves(world.game+pin.rva,pin.hex)then
                why=('native code not as reviewed at game.dll+0x%X (%s)'):format(pin.rva,pin.label)
            end
        end
    end
    proven[key]=why or true
    if why then return nil,why end
    return true
end

local function region(world,at)
    local r=world.runtime.query(at)
    if not(r and r.state==COMMIT and r.type==PRIVATE and r.allocation_base and r.allocation_base>0
        and at>=r.base and at<r.base+r.size)then
        return nil
    end
    return r
end

-- A permanent block as the adapter left it: committed private pages of one allocation, every page readable
-- (READONLY, or READWRITE while a guarded transaction has it open).
local function block_ok(world,allocation,size,protect)
    for page=allocation,allocation+size-PAGE,PAGE do
        local q=world.runtime.query(page)
        if not(q and q.state==COMMIT and q.type==PRIVATE and q.allocation_base==allocation
            and(q.protect==(protect or READONLY)or not protect and q.protect==READWRITE))then
            return false
        end
    end
    return true
end
M.block_ok=block_ok

local function open()
    local world,why=world_module.open()
    if not world then fail('TARGET_UNAVAILABLE: '..tostring(why))end
    local ok,reason=prove(world)
    if not ok then fail('UNPROVEN: '..reason)end
    return world
end
M.open=open

----------------------------------------------------------------------------------------------------- the table --
local function trailer(original,records)
    return L.magic..u64(original)..b.encode(BW.index,'u32')..b.encode(records,'u32')
end
local function trailer_at(entry)return entry.table+BW.recordBase+entry.records*BW.recordStride end

-- Where the game reads the BeamWeapon table, re-derived and checked: t.mode 'in_place' (the entity allocation's own
-- table), 'owned' (exactly this module's registered copy over this original) or 'foreign' (t.reason).
local function locate_table(world)
    local manager=world.view.pointer(world.game+MG.global)
    if not manager then fail('TARGET_UNAVAILABLE: the entity manager is not initialised')end
    local t={manager=manager,slot_at=manager+MG.slotBase+8*BW.index}
    if t.slot_at%8~=0 then fail('the BeamWeapon slot is not 8-byte aligned')end
    t.slot=world.view.pointer(t.slot_at)
    if not t.slot then fail('TARGET_UNAVAILABLE: the BeamWeapon slot is unreadable')end
    local esh=world.view.pointer(manager+MG.eshSlot)
    if not esh then fail('TARGET_UNAVAILABLE: the entity map slot is unreadable')end
    t.base=esh-28
    if world.view.read(t.base,28)~=b.unhex(profile.map_header)then
        fail('CONFLICT: the game reads its EntitySettingsHashmap from another place (another mod moved it)')
    end
    local c=assert(profile.components[BW.component],'BeamWeapon profile component')
    assert(c.index==BW.index and c.indices==BW.capacity and c.records==BW.fileRecords and c.stride==BW.recordStride
        and c.record_offset==BW.recordBase,'the BeamWeapon schema differs from the research')
    t.original=t.base+c.offset+CT.tableFromProfileOffset
    t.framing=world.view.read(t.original-L.framing,L.framing)
    if not(t.framing and b.u32(t.framing,0)==c.index and t.framing:sub(5,32)==b.unhex(c.header))then
        fail('the BeamWeapon table framing changed')
    end
    t.file=world.view.read(t.original,BW.recordBase+BW.fileRecords*BW.recordStride)
    if not t.file then fail('TARGET_UNAVAILABLE: the BeamWeapon table is unreadable')end
    local mr=region(world,t.slot_at)
    local page=t.slot_at-t.slot_at%PAGE
    if not(mr and mr.protect==READWRITE and mr.base<=page and page+PAGE<=mr.base+mr.size)then
        t.slot_unwritable='the BeamWeapon slot\'s page is not one read-write private region'
    else
        t.manager_owner={base=mr.allocation_base,size=page+PAGE-mr.allocation_base,type=PRIVATE,protect=READWRITE}
    end
    local entry=owned.get(BW.component)
    if entry and entry.owner~=M.OWNER then
        -- Another HD2Runtime module (the beam experiments) owns the table this session: never mixed.
        if t.slot==entry.table and entry.original==t.original then
            t.mode='foreign'
            t.reason='CONFLICT: the BeamWeapon table is the copy of '..tostring(entry.owner)..' this session (an '
                ..'experiment proof): restore it with that proof, or restart the game'
            return t
        end
        entry=nil
    end
    if t.slot==t.original then
        t.mode='in_place'
        if entry then
            owned.clear(BW.component)
            t.reloaded=true
            log('RELOAD DETECTED: the slot holds the entity file\'s own table again: the conversion copy is dead '
                ..'(never freed) and forgotten; the BeamWeapon table is vanilla')
        end
        return t
    end
    if entry and t.slot==entry.table and entry.original==t.original then
        local q=region(world,entry.table)
        if not(q and block_ok(world,entry.allocation,entry.size))then
            fail('HD2Runtime\'s BeamWeapon copy is not the allocation it built')
        end
        if world.view.read(entry.table-L.framing,L.framing)~=t.framing then fail('the BeamWeapon copy framing changed')end
        if world.view.read(trailer_at(entry),L.trailerSize)~=trailer(entry.original,entry.records)then
            fail('the BeamWeapon copy trailer changed')
        end
        t.copy=world.view.read(entry.table,BW.recordBase+entry.records*BW.recordStride)
        if not t.copy then fail('TARGET_UNAVAILABLE: the BeamWeapon copy is unreadable')end
        t.mode='owned';t.entry=entry
        t.copy_owner={base=entry.allocation,size=entry.size,type=PRIVATE,protect=q.protect}
        return t
    end
    t.mode='foreign'
    if entry then
        owned.clear(BW.component)
        log('the slot no longer holds HD2Runtime\'s conversion copy: another program changed it; the copy is forgotten')
    end
    t.reason='CONFLICT: the game reads its BeamWeapon table from another place (another mod moved it, e.g. True '
        ..'Lasgun Beam Overhaul): HD2Runtime never chains onto a foreign copy'
    return t
end

-- How many copies this game process built (never freed); a new one is refused past L.maxCopies.
function M.copies()return session().copies end
local function owned_available(world,t)
    if t.mode=='owned'then return true end
    if not t.manager_owner then return nil,t.slot_unwritable end
    if type(world.runtime.permanent_block)~='function'then return nil,'this Runtime adapter cannot allocate memory'end
    if session().copies>=L.maxCopies then
        return nil,('%d copies were built this session (each stays allocated): restart the game'):format(session().copies)
    end
    return true
end

-- The copy's bytes: framing, rows (the file's, `rows` = {[row] = 16 bytes} written in), records 0..23 = the file's,
-- one record per catalogued weapon (`records` = {[index] = 120 bytes}, else the donor), then the trailer.
local function copy_bytes(t,rows,records)
    local body={t.framing}
    for row=0,BW.capacity-1 do
        local raw=t.file:sub(row*BW.rowStride+1,(row+1)*BW.rowStride)
        if rows[row]then
            assert(raw==ZERO16,'row '..row..' of the file table is not empty')
            raw=rows[row]
        end
        body[#body+1]=raw
    end
    body[#body+1]=t.file:sub(BW.recordBase+1,BW.recordBase+BW.fileRecords*BW.recordStride)
    for index=BW.fileRecords,L.records-1 do
        local rec=records[index]or DONOR
        assert(#rec==BW.recordStride,'record bytes')
        body[#body+1]=rec
    end
    body[#body+1]=trailer(t.original,L.records)
    local bytes=table.concat(body)
    assert(#bytes<=65536,'the copy is too large')
    return bytes
end
M.copy_bytes=copy_bytes

-- Builds the copy (NOT live): a permanent block, read back and checked; returns the entry (not registered).
local function build(world,t,rows,records)
    assert(t.mode=='in_place','a copy is built only while the game reads the file\'s own table')
    local ok,why=owned_available(world,t)
    if not ok then fail('REFUSED: the owned table is unavailable: '..tostring(why))end
    local bytes=copy_bytes(t,rows,records)
    local address=world.runtime.permanent_block(bytes)
    session().copies=session().copies+1
    assert(type(address)=='number'and address>0 and address%PAGE==0,'the permanent block is not page-aligned')
    local size=#bytes+(PAGE-#bytes%PAGE)%PAGE
    if not block_ok(world,address,size,READONLY)then
        fail('the copy is not one read-only private allocation')
    end
    if world.view.read(address,#bytes)~=bytes then fail('the copy did not read back as built')end
    log(('copy %d built: %d bytes (framing, 46 rows, records 0..23 as the file, %d conversion records, trailer) at a '
        ..'new private read-only block (never freed); not live yet'):format(session().copies,#bytes,
        L.records-BW.fileRecords))
    return {owner=M.OWNER,index=BW.index,table=address+L.framing,allocation=address,size=size,original=t.original,
        records=L.records}
end

-------------------------------------------------------------------------------------------- the add layout's lists --
-- ONE Runtime-owned block per game process (never freed, read-only after the fill): the magic, then every catalogued
-- add root's grown list (its file list plus BeamWeapon, sorted: domains/beam_conversion.lua root.add.listHex) at its
-- catalogued slot. Its content is fixed by the catalogue, so a block found again after a module reload (the row names
-- it) is adopted only when it is byte for byte the block this catalogue builds.
local function list_block_bytes()
    local size=LS.bytes
    local parts,at={},0
    local magic=LS.magic..string.rep('\0',LS.framing-#LS.magic)
    parts[1]=magic;at=#magic
    local slots={}
    for _,w in ipairs(C.weapons)do
        if w.layout=='add'then
            for _,root in ipairs(w.roots)do slots[#slots+1]={at=root.add.slot,bytes=b.unhex(root.add.listHex)}end
        end
    end
    table.sort(slots,function(a,c)return a.at<c.at end)
    for _,x in ipairs(slots)do
        assert(x.at>=at,'list slots overlap')
        parts[#parts+1]=string.rep('\0',x.at-at);parts[#parts+1]=x.bytes;at=x.at+#x.bytes
    end
    parts[#parts+1]=string.rep('\0',size-at)
    local bytes=table.concat(parts)
    assert(#bytes==size,'list block size')
    return bytes
end
local LIST_BYTES
local function list_bytes()LIST_BYTES=LIST_BYTES or list_block_bytes();return LIST_BYTES end
M.list_block_bytes=list_bytes

-- The block this session built (or adopted), validated: {allocation, size} or nil.
local function list_block(world)
    local blk=session().lists
    if not blk then return nil end
    if not(block_ok(world,blk.allocation,blk.size,READONLY)and world.view.read(blk.allocation,LS.bytes)==list_bytes())
    then
        fail('HD2Runtime\'s membership list block is not as it built it (another program changed it): restart the game')
    end
    return blk
end
-- A pointer an add root's row holds that lies in a block this session does not know (a module reload): adopted when
-- the whole allocation is exactly this catalogue's block. Returns the block or nil.
local function adopt_list_block(world,pointer)
    local q=region(world,pointer)
    if not(q and q.allocation_base)then return nil end
    local allocation=q.allocation_base
    local size=LS.bytes+(PAGE-LS.bytes%PAGE)%PAGE
    if not block_ok(world,allocation,size,READONLY)then return nil end
    if world.view.read(allocation,LS.bytes)~=list_bytes()then return nil end
    session().lists={allocation=allocation,size=size}
    log('the membership list block was found again (a module reload) and adopted: byte for byte this catalogue\'s')
    return session().lists
end
-- Builds the block (once per game process): a permanent block, read back and checked.
local function build_lists(world)
    local blk=session().lists
    if blk then return list_block(world)end
    if type(world.runtime.permanent_block)~='function'then
        fail('REFUSED: this Runtime adapter cannot allocate memory (the add layout needs its list block)')
    end
    local bytes=list_bytes()
    local address=world.runtime.permanent_block(bytes)
    assert(type(address)=='number'and address>0 and address%PAGE==0,'the permanent block is not page-aligned')
    local size=#bytes+(PAGE-#bytes%PAGE)%PAGE
    if not block_ok(world,address,size,READONLY)then fail('the list block is not one read-only private allocation')end
    if world.view.read(address,#bytes)~=bytes then fail('the list block did not read back as built')end
    session().lists={allocation=address,size=size}
    log(('membership list block built: %d bytes (every add-layout root\'s list plus BeamWeapon, sorted) at a new '
        ..'private read-only block (never freed); no row names it yet'):format(#bytes))
    return session().lists
end

-- The ProjectileWeapon rate a converted HEAT weapon gets (research/docs/beam-conversion-add-layout-F5FEE03DCFDB.md
-- section 4): the heat step runs on every pulse AND on every projectile-update shot; the beam update runs first in the
-- world update and each pulse pushes the projectile timer by one projectile interval, so a projectile rate no faster
-- than the slowest pulse cadence keeps the timer ahead and heat comes once per pulse. 90 % of the slowest effective
-- pulse rate from 30 to 240 fps, at least 1 rpm.
function M.heat_projectile_rate(rate,pulse)
    local slowest
    for fps=30,240 do
        local r=M.effective_rate(rate,pulse,fps)
        if not slowest or r<slowest then slowest=r end
    end
    return math.max(1,math.floor(slowest*0.9))
end
local function f32(value)return b.encode(value,'f32')end

---------------------------------------------------------------------------------------------------- index rows --
-- rows: the 46 x 16 index bytes of a table. The row of a resource by the game's probe (key 0 stops), or nil.
local function find_row(rows,resource)
    local key=key_bytes(resource)
    local at=home(resource,BW.capacity)
    for _=1,BW.capacity do
        local raw=rows:sub(at*16+1,at*16+8)
        if raw==key then return at end
        if raw==ZERO8 then return nil end
        at=(at+1)%BW.capacity
    end
    return nil
end
M.find_row=find_row
local function free_rows(rows)
    local n=0
    for row=0,BW.capacity-1 do if rows:sub(row*16+1,row*16+8)==ZERO8 then n=n+1 end end
    return n
end
-- The first empty row on a resource's probe path (an insert), or nil.
local function insert_row(rows,resource)
    local at=home(resource,BW.capacity)
    for _=1,BW.capacity do
        if rows:sub(at*16+1,at*16+8)==ZERO8 then return at end
        at=(at+1)%BW.capacity
    end
    return nil
end
M.insert_row=insert_row
local function key_home(rows,row)
    return home(b.resource(rows,row*16),BW.capacity)
end
-- Linear-probing deletion of row e (Knuth's algorithm R): {moves = {{from, to}}, clear = the last vacated row}.
-- A row moves when its home is not cyclically in (vacated, its row]. Only converted rows may move.
local function delete_plan(rows,e,movable)
    local moves={}
    local i,j=e,e
    for _=1,BW.capacity do
        j=(j+1)%BW.capacity
        if rows:sub(j*16+1,j*16+8)==ZERO8 then break end
        local k=key_home(rows,j)
        local stays
        if i<=j then stays=i<k and k<=j else stays=i<k or k<=j end
        if not stays then
            local resource=b.resource(rows,j*16)
            if not movable(resource)then
                fail(('CONFLICT: removing BeamWeapon row %d would strand row %d (%s), which is not a conversion row')
                    :format(e,j,resource))
            end
            moves[#moves+1]={from=j,to=i,resource=resource}
            i=j
        end
    end
    return {moves=moves,clear=i}
end
M.delete_plan=delete_plan
-- Applies a delete plan to a rows string (offline: what the rows become).
local function apply_delete(rows,plan)
    local out=rows
    for _,m in ipairs(plan.moves)do
        out=out:sub(1,m.to*16)..rows:sub(m.from*16+1,m.from*16+16)..out:sub(m.to*16+17)
    end
    return out:sub(1,plan.clear*16)..ZERO16..out:sub(plan.clear*16+17)
end
M.apply_delete=apply_delete

-------------------------------------------------------------------------------------------------- the locate --
local function component_table(world,manager,base,name)
    local c=assert(profile.components[name],'unknown component '..name)
    local at=world.view.pointer(manager+MG.slotBase+8*c.index)
    if at~=base+c.offset+CT.tableFromProfileOffset then
        fail('CONFLICT: the game reads its '..name..' table from another place (another mod moved it)')
    end
    local framing=world.view.read(at-32,32)
    if not(framing and b.u32(framing,0)==c.index and framing:sub(5,32)==b.unhex(c.header))then
        fail(name..' framing changed')
    end
    return at,c
end

-- One root's targets, re-derived and checked. rows: the index rows the game reads.
local function locate_root(world,s,w,root)
    local R={w=w,root=root}
    local prow=world.view.read(s.ptable+root.projectile.row*16,16)
    if not(prow and b.resource(prow,0)==root.resource and b.u32(prow,8)==root.projectile.record and b.u32(prow,12)==0)
    then
        fail('CONFLICT: the '..w.name..'\'s ProjectileWeapon row is not as reviewed (another mod changed it)')
    end
    local found
    local at=root.membership.home
    for _=1,C.membership.rows do
        local key=world.view.read(s.esh+at*C.membership.rowStride,8)
        if not key then fail('TARGET_UNAVAILABLE: the entity map is unreadable')end
        if key==ZERO8 then break end
        if b.resource(key,0)==root.resource then found=at;break end
        at=(at+1)%C.membership.rows
    end
    if found~=root.membership.row then
        fail(('the %s\'s entity map row is not row %d (found %s)'):format(w.name,root.membership.row,tostring(found)))
    end
    R.row_at=s.esh+found*C.membership.rowStride
    local settings_row=world.view.read(R.row_at,C.membership.rowStride)
    if not settings_row then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s entity map row is unreadable')end
    if not(b.u32(settings_row,20)==0 and b.u32(settings_row,24)==root.membership.networkType)then
        fail('the '..w.name..'\'s entity map row (network type) is not as reviewed')
    end
    -- The row names the file's own packed list (vanilla, or the swap layout's in-place edit) or, for the add layout,
    -- exactly its slot in HD2Runtime's list block with the grown count. Anything else is another program's.
    local list=s.esh+root.membership.listOffsetInBody
    local pointer,count_now=b.pointer(settings_row,8),b.u32(settings_row,16)
    R.row_pointer,R.row_count=pointer,count_now
    if pointer==list and count_now==root.membership.count then R.pointer='file'
    else
        local blk=root.add and count_now==root.add.count and(s.lists or adopt_list_block(world,pointer))
        if blk then s.lists=blk end
        if blk and pointer==blk.allocation+root.add.slot then R.pointer='owned'
        else
            fail('CONFLICT: the '..w.name..'\'s entity map row names another membership list (another mod moved or '
                ..'grew it, e.g. True Lasgun Beam Overhaul): HD2Runtime never chains onto it')
        end
    end
    local count=root.membership.count
    if root.add and s.lists then R.lists_slot=s.lists.allocation+root.add.slot end
    R.list=list
    R.list_bytes=world.view.read(list,count*2)
    if not R.list_bytes then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s membership list is unreadable')end
    local first=list+root.membership.firstChanged
    local finish=list+root.membership.endChanged
    R.window=first-first%4
    R.window_size=finish+(-finish)%4-R.window
    if not(R.window_size==4 or R.window_size==8 or R.window_size==12)then
        fail('the '..w.name..'\'s list window is not 4, 8 or 12 bytes')
    end
    -- A window across a page boundary (the LAS-12 Sai) is written as one 4-byte change on each side of it.
    if R.window%PAGE+R.window_size>PAGE and(PAGE-R.window%PAGE)%4~=0 then
        fail('the '..w.name..'\'s list window crosses a page off a 4-byte boundary')
    end
    R.list_context_at=list-16
    R.list_context=world.view.read(R.list_context_at,count*2+48)
    if not R.list_context then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s membership list context is unreadable')end
    local mz=root.magazine
    if mz then
        local mfound
        local mat=mz.home
        for _=1,MZ.capacity do
            local key=s.mrows:sub(mat*16+1,mat*16+8)
            if key==ZERO8 then break end
            if b.resource(key,0)==root.resource then mfound=mat;break end
            mat=(mat+1)%MZ.capacity
        end
        if mfound~=mz.row then
            fail(('the %s\'s WeaponMagazine row is not row %d (found %s)'):format(w.name,mz.row,tostring(mfound)))
        end
        if hex(s.mrows:sub(mz.row*16+1,mz.row*16+16))~=mz.rowBytes then
            fail('CONFLICT: the '..w.name..'\'s WeaponMagazine row is not as reviewed (another mod changed it)')
        end
        for n=0,MZ.capacity-1 do
            local raw=s.mrows:sub(n*16+1,n*16+16)
            if n~=mz.row and raw:sub(1,8)~=ZERO8 and b.u32(raw,8)==mz.record then
                fail(('CONFLICT: another WeaponMagazine row names record %d (the %s\'s)'):format(mz.record,w.name))
            end
        end
        R.mrecord_at=s.mtable+MZ.recordBase+mz.record*MZ.recordStride
        R.mrecord=world.view.read(R.mrecord_at,MZ.recordStride)
        if not R.mrecord then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s magazine record is unreadable')end
        R.chamber_at=s.mtable+mz.windowOffset
        R.chamber=hex(R.mrecord:sub(MZ.window+1,MZ.window+4))
    end
    if root.add then
        -- Its own unique-owner ProjectileWeapon record (the coverage proved the owner): +0 the type, +8 the rate.
        R.pw_at=s.ptable+PJ.recordBase+root.projectile.record*PJ.recordStride
        R.pw_record=world.view.read(R.pw_at,PJ.recordStride)
        if not R.pw_record then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s ProjectileWeapon record is unreadable')end
        R.pw_type=hex(R.pw_record:sub(PJ.typeOffset+1,PJ.typeOffset+4))
        R.pw_rate=hex(R.pw_record:sub(PJ.rateOffset+1,PJ.rateOffset+4))
        R.row_context_at=R.row_at                 -- the 32-byte row itself: the targets lie inside it
        R.row_context=world.view.read(R.row_context_at,C.membership.rowStride)
        if not R.row_context then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s entity map row is unreadable')end
    end
    local extents
    local split=R.window%PAGE+R.window_size>PAGE and PAGE-R.window%PAGE or nil
    if split then extents={{R.window,split},{R.window+split,R.window_size-split}}else extents={{R.window,R.window_size}}end
    R.split=split
    if mz then extents[#extents+1]={R.chamber_at,4}end
    if root.add then
        extents[#extents+1]={R.row_at+8,12}       -- the row's list pointer and count (map + 28 + 32 x row: page offset
        extents[#extents+1]={R.pw_at,12}          -- 4 mod 32, never across a page) and the record's +0..+11
    end
    R.tops={}
    for _,extent in ipairs(extents)do
        local q=region(world,extent[1])
        if not(q and q.allocation_base==s.base and q.protect==READONLY and extent[1]+extent[2]<=q.base+q.size)then
            fail('a target page of the '..w.name..' is not in the entity allocation\'s read-only memory')
        end
        if extent[1]%4~=0 or extent[1]%PAGE+extent[2]>PAGE then
            fail('a target of the '..w.name..' crosses a page or is misaligned')
        end
        R.tops[#R.tops+1]=q.base+q.size
    end
    -- The state of this root. list: 'vanilla' (the file's list, as shipped), 'swapped' (the swap layout's in-place
    -- edit), 'added' (the add layout: the row names HD2Runtime's grown list; the file list stays as shipped) or
    -- FOREIGN. projectile (add-capable roots): 'vanilla' (its own type), 'zero' (the add layout's type 0) or FOREIGN.
    local lb=hex(R.list_bytes)
    local lst
    if R.pointer=='owned'then lst=lb==root.membership.before and'added'or'FOREIGN'
    else lst=lb==root.membership.before and'vanilla'or lb==root.membership.after and'swapped'or'FOREIGN'end
    local mag='n/a'
    if mz then mag=R.chamber==mz.before and'vanilla'or R.chamber==mz.after and'converted'or'FOREIGN'end
    local pw='n/a'
    if root.add then pw=R.pw_type==root.add.typeBefore and'vanilla'or R.pw_type=='00000000'and'zero'or'FOREIGN'end
    R.row=find_row(s.rows,root.resource)
    local expected_record=s.path_mode=='owned'and w.record or BW.defaultRecord
    local row='none'
    if R.row then
        local raw=s.rows:sub(R.row*16+1,R.row*16+16)
        row=(b.u32(raw,8)==expected_record and b.u32(raw,12)==0)and'own'or'FOREIGN'
    end
    local mag_v=mag=='vanilla'or mag=='n/a'
    local mag_c=mag=='converted'or mag=='n/a'
    local pw_v=pw=='vanilla'or pw=='n/a'
    R.layout=lst=='added'and'add'or lst=='swapped'and'swap'or nil
    if lst=='vanilla'and row=='none'and mag_v and pw_v then R.state='vanilla'
    elseif lst=='swapped'and row=='own'and mag_c and pw_v then R.state='converted'
    elseif lst=='added'and row=='own'and mag_c and pw=='zero'then R.state='converted'
    elseif lst=='swapped'and row=='none'and mag_c and pw_v then R.state='orphaned'
    elseif lst=='added'and row=='none'and mag_c and pw=='zero'then R.state='orphaned'
    elseif lst=='vanilla'and row~='FOREIGN'and mag~='FOREIGN'and pw~='FOREIGN'and root.add then
        -- The file's list again under a changed row, magazine or record: the entity loader reloaded the file (0xFDB860)
        -- or an add conversion died half-way: restored as a whole.
        R.state='orphaned';R.layout='add';R.reloaded=true
    else R.state='foreign'end
    R.parts={list=lst,row=row,magazine=mag,projectile=pw}
    R.detail=('list %s, row %s%s, magazine chamber %s%s'):format(lst,R.row and tostring(R.row)or'-',
        row=='FOREIGN'and' FOREIGN'or'',mag,root.add and(', projectile type '..pw)or'')
    return R
end

-- The weapon's state from its roots: 'vanilla' | 'converted' | 'orphaned' | 'foreign' | 'refused' (not supported).
local function weapon_state(roots)
    local seen,layouts={},{}
    for _,R in ipairs(roots)do
        seen[R.state]=true
        if R.layout then layouts[R.layout]=true end
    end
    if layouts.add and layouts.swap then return'foreign'end
    local layout=layouts.add and'add'or layouts.swap and'swap'or nil
    if seen.foreign then return'foreign'end
    if seen.converted and not seen.vanilla and not seen.orphaned then return'converted',layout end
    if seen.vanilla and not seen.converted and not seen.orphaned then return'vanilla'end
    if seen.orphaned and not seen.converted then return'orphaned',layout end
    return'foreign'
end

-- Everything an operation needs, re-derived and checked. Returns s or raises.
local function locate(world)
    local t=locate_table(world)
    if t.mode=='foreign'then fail(t.reason)end
    local s={tb=t,manager=t.manager,base=t.base,esh=t.base+28,weapons={},by_resource={}}
    s.table,s.table_bytes=t.original,t.file
    s.path_mode=t.mode=='owned'and'owned'or nil
    -- The file's rows must be the reviewed vanilla rows, but for conversion rows in vanilla-empty rows (shared path).
    local file_rows=t.file:sub(1,BW.capacity*16)
    for row=0,BW.capacity-1 do
        local now,was=file_rows:sub(row*16+1,row*16+16),VANILLA_ROWS:sub(row*16+1,row*16+16)
        if now~=was then
            local mine=was==ZERO16 and BY_RESOURCE[b.resource(now,0)]and b.u32(now,8)==BW.defaultRecord
                and b.u32(now,12)==0
            if not mine then
                fail(('CONFLICT: BeamWeapon row %d of the file table is not as reviewed (another mod changed it)')
                    :format(row))
            end
            s.shared_rows=true
        end
    end
    local trident=file_rows:sub(C.trident.row*16+1,C.trident.row*16+16)
    if b.resource(trident,0)~=C.trident.resource or b.u32(trident,8)~=C.trident.record then
        fail('CONFLICT: BeamWeapon row '..C.trident.row..' is not the Trident\'s (another mod changed it)')
    end
    local source=t.file:sub(BW.recordBase+C.trident.record*BW.recordStride+1,
        BW.recordBase+(C.trident.record+1)*BW.recordStride)
    if source~=DONOR then
        fail('CONFLICT: the Trident\'s BeamWeapon record differs from the reviewed copy source (another mod changed it)')
    end
    local r23=t.file:sub(BW.recordBase+BW.defaultRecord*BW.recordStride+1,
        BW.recordBase+(BW.defaultRecord+1)*BW.recordStride)
    s.record23=r23==VANILLA_RECORD23 and'vanilla'or r23==DONOR and'copy'or'foreign'
    if s.record23=='foreign'then fail('CONFLICT: BeamWeapon record 23 is in a state HD2Runtime did not make')end
    s.record23_at=t.original+BW.recordBase+BW.defaultRecord*BW.recordStride
    local q=region(world,s.record23_at)
    if not(q and q.allocation_base==t.base and q.protect==READONLY and s.record23_at%4==0)then
        fail('the BeamWeapon file table is not in the entity allocation\'s read-only memory')
    end
    local tops={q.base+q.size}
    if t.mode=='owned'then
        if s.shared_rows or s.record23=='copy'then
            fail('REFUSED: the shared-record path left rows or record 23 in the file table while the owned copy is '
                ..'live (mixed paths): restart the game')
        end
        s.rows=t.copy:sub(1,BW.capacity*16)
        s.ctable=t.entry.table
        if t.entry.records~=L.records then fail('the conversion copy has another record count')end
        -- Rows: the file's, or a conversion row in a file-empty row naming its weapon's own record.
        for row=0,BW.capacity-1 do
            local now,was=s.rows:sub(row*16+1,row*16+16),file_rows:sub(row*16+1,row*16+16)
            if now~=was then
                local hit=was==ZERO16 and BY_RESOURCE[b.resource(now,0)]
                if not(hit and b.u32(now,8)==hit.weapon.record and b.u32(now,12)==0)then
                    fail(('CONFLICT: row %d of HD2Runtime\'s BeamWeapon copy differs from the file (not a conversion '
                        ..'row): restart the game'):format(row))
                end
            end
        end
        s.drift={}
        for r=0,BW.fileRecords-1 do
            local at=BW.recordBase+r*BW.recordStride
            if t.copy:sub(at+1,at+BW.recordStride)~=t.file:sub(at+1,at+BW.recordStride)then s.drift[#s.drift+1]=r end
        end
    else
        s.rows=file_rows
        s.drift={}
        s.path_mode=(s.shared_rows or s.record23=='copy')and'shared'or nil
    end
    s.ptable,s.pcomponent=component_table(world,s.manager,s.base,PJ.component)
    s.mtable=component_table(world,s.manager,s.base,MZ.component)
    assert(s.pcomponent.record_offset==PJ.recordBase and s.pcomponent.stride==PJ.recordStride
        and s.pcomponent.indices==PJ.capacity,'the ProjectileWeapon schema differs from the research')
    -- The add layout's list block, when this session built (or adopted) one: validated before any row names it.
    s.lists=session().lists and list_block(world)or nil
    s.rs=require("hd2runtime/runtime/beam_conversion_rows").locate(world)
    s.pair_user={}
    s.mrows=world.view.read(s.mtable,MZ.capacity*MZ.rowStride)
    if not s.mrows then fail('TARGET_UNAVAILABLE: the WeaponMagazine table is unreadable')end
    for _,w in ipairs(C.weapons)do
        if w.supported then
            local roots={}
            for _,root in ipairs(w.roots)do
                local R=locate_root(world,s,w,root)
                roots[#roots+1]=R
                s.by_resource[root.resource]=R
                for _,top in ipairs(R.tops)do tops[#tops+1]=top end
            end
            local W={w=w,roots=roots}
            W.state,W.layout=weapon_state(roots)
            if t.mode=='owned'then
                local at=BW.recordBase+w.record*BW.recordStride
                W.record_at=s.ctable+at
                W.record=t.copy:sub(at+1,at+BW.recordStride)
                -- Its own record: the Trident's but for its settings (+104..+115) and, with own rows, +0 = the
                -- borrowed BeamType of an owned pair (runtime/beam_conversion_rows.lua).
                local donor_but_settings=W.record:sub(5,SETTINGS_FROM)==DONOR:sub(5,SETTINGS_FROM)
                    and W.record:sub(SETTINGS_TO+1)==DONOR:sub(SETTINGS_TO+1)
                local beam_type=b.u32(W.record,0)
                if beam_type~=C.rows.tridentBeamType then
                    for i,P in ipairs(s.rs.pairs)do
                        if P.k==beam_type and P.state=='owned'and not s.pair_user[i]then W.pair=i end
                    end
                    if W.pair then s.pair_user[W.pair]=w.name else donor_but_settings=false end
                end
                if not donor_but_settings or(W.state~='converted'and W.record~=DONOR)then
                    W.state='foreign';W.record_foreign=true
                end
            end
            -- A converted heat weapon of the add layout: its ProjectileWeapon rate is the bound of its record's pulse
            -- settings (M.heat_projectile_rate), anything else is another write's.
            if W.state=='converted'and W.layout=='add'and w.add and w.add.heat then
                local settings=M.decode_settings(t.mode=='owned'and W.record or DONOR)
                W.heat_rate=hex(f32(M.heat_projectile_rate(settings.fire_rate,settings.pulse_seconds)))
                for _,R in ipairs(roots)do
                    if R.pw_rate~=W.heat_rate then
                        W.state='foreign';R.detail=R.detail..', projectile rate not its conversion\'s (another write)'
                    end
                end
            end
            s.weapons[w.name]=W
        end
    end
    s.owner={base=t.base,size=math.max(unpack(tops))-t.base,type=PRIVATE,protect=READONLY}
    return s
end
M.locate=function(world)return locate(world)end

----------------------------------------------------------------------------------------------------- the gates --
-- Live entities per catalogued root resource, and of the Trident.
local function census(world,manager)
    if hooks.census then return hooks.census(world,manager)end
    local invalid=world.view.u32(world.game+MG.invalidEntity)
    local raw=world.view.read(manager+MG.descriptors,MG.descriptorStride*MG.descriptorCount)
    if not(invalid and raw)then return nil,'the entity descriptor table is unreadable'end
    local out={live=0,tridents=0,by={}}
    for k=0,MG.descriptorCount-1 do
        local at=k*MG.descriptorStride
        if b.u32(raw,at+MG.descriptorEntity)~=invalid and(b.u32(raw,at)~=0 or b.u32(raw,at+4)~=0)then
            out.live=out.live+1
            local kind=b.resource(raw,at)
            if BY_RESOURCE[kind]then out.by[kind]=(out.by[kind]or 0)+1
            elseif kind==C.trident.resource then out.tridents=out.tridents+1 end
        end
    end
    return out
end
M.census=function(world,manager)return census(world,manager)end
local function live_of(count,w)
    local n=0
    for _,root in ipairs(w.roots or{})do n=n+(count.by[root.resource]or 0)end
    return n
end

-- Lobby: 'solo', why | 'others', why | nil, why (unreadable).
local function lobby(world)
    if hooks.solo then
        local ok,why=hooks.solo(world)
        if ok==nil then return nil,why end
        return ok and'solo'or'others',why
    end
    local players=world_module.players(world)or{}
    if#players>1 then return'others',#players..' players in the game\'s player list'end
    local channel=require('hd2runtime/runtime/peer_channel')
    local ok,why=channel.prove(world)
    if not ok then return nil,'the lobby state cannot be proven ('..tostring(why)..')'end
    local found,code,reason=channel.lobby(world)
    if found then
        if#found.members>1 then return'others',#found.members..' lobby members'end
        return'solo','a lobby of 1 (this machine)'
    end
    if code=='NOT_JOINED'or code=='NO_SESSION'then return'solo','no lobby ('..tostring(reason)..')'end
    return nil,'the lobby state is unreadable ('..tostring(code)..': '..tostring(reason)..')'
end
M.lobby=function(world)return lobby(world)end

-- The Trident's package: 'resident' | ... , detail.
local function assets_state(world)
    if hooks.assets then return hooks.assets(world)end
    local assets=require('hd2runtime/core/assets')
    local dep=assets.dependency(C.trident.dependency)
    if not dep then return'unknown','no catalogued Trident package'end
    local ok,state=pcall(assets.state,world.runtime,dep.package)
    if not ok then return'unknown',clean(state)end
    return state,dep.name
end

-- The multiplayer gate of an apply (or a settings change) while another player is present: the swap layout is solo
-- only; the add layout needs every other member to hold the identical conversion already (runtime/beam_conversion_
-- sync.lua allow_apply over the entries this weapon will post). Solo: nothing to check.
local function mp_gate(world,layout,entries)
    local state,detail=lobby(world)
    if state=='solo'then return end
    local sync=require('hd2runtime/runtime/beam_conversion_sync')
    if layout=='add'and state=='others'then
        local d=sync.allow_apply(entries)
        if d.allowed then return end
        fail(('TARGET_UNAVAILABLE: NOT_AGREED: another player is present (%s) and the add-layout conversion is allowed '
            ..'only when every other member already holds it identically (%s: %s)'):format(tostring(detail),d.code,
            d.reason))
    end
    local okd,sync_text=pcall(function()return sync.describe(true)end)
    fail('TARGET_UNAVAILABLE: NOT_SOLO: '..(layout=='add'and'the lobby state cannot be read ('..tostring(detail)..')'
        or('swap-layout beam conversions apply only in a solo game ('..tostring(detail)..'); a weapon of a swap-'
        ..'converted type that another player owns crashes a converted game, even when every player converted it the '
        ..'same way'))..(okd and('; '..tostring(sync_text))or''))
end

-- ZERO live instances of every root of every weapon in `weapons` (names), the multiplayer gate for an apply, the
-- package resident.
local function gates(world,s,weapons,apply,layout,entries)
    local count,why=census(world,s.manager)
    if not count then fail('TARGET_UNAVAILABLE: '..tostring(why))end
    local live={}
    for _,w in ipairs(weapons)do
        local n=live_of(count,w)
        if n>0 then live[#live+1]=('%d live %s'):format(n,w.name)end
    end
    if#live>0 then
        fail('TARGET_UNAVAILABLE: BUSY: '..table.concat(live,', ')..' (the ship preview, the armory, a loadout or a '
            ..'pickup): the conversion is written only while none exists; equip other weapons and do not open the '
            ..'armory until it applies')
    end
    if apply then
        mp_gate(world,layout or'swap',entries)
        local asset,asset_detail=assets_state(world)
        if asset~='resident'then
            fail('TARGET_UNAVAILABLE: the Trident\'s package is '..tostring(asset)..' ('..tostring(asset_detail)..')')
        end
    end
    return count
end

------------------------------------------------------------------------------------------------- the settings --
-- The settings of a record (+104..+115 decoded).
local function decode_settings(record)
    local out={}
    for _,def in ipairs(C.settings)do out[def.id]=b.value(record,def.offset,def.storage)end
    return out
end
M.decode_settings=decode_settings
M.DONOR_SETTINGS=decode_settings(DONOR)

-- The pulse the conversion writes for a rate (research/docs/beam-pulse-rate-F5FEE03DCFDB.md): an explicit pulse is
-- kept; without one, the Trident's 0.15 s when it fits the shot interval, else the longest pulse that never decides it
-- (max(60 / (2 rate), 60 / rate - 1/30) s), never below the setting's minimum (the one-frame no-damage floor at 30 fps).
local function ceil_eps(x)return math.ceil(x-1e-9)end
function M.pulse_updates(rate,pulse,fps)
    local dt=1/fps
    return math.max(ceil_eps(60/(rate*dt)),math.max(1,ceil_eps(pulse/dt))+1)
end
function M.effective_rate(rate,pulse,fps)return 60*fps/M.pulse_updates(rate,pulse,fps)end
function M.pulse_limit(rate)
    local interval=60/rate
    return math.max(interval/2,interval-1/30)
end
function M.fitted_pulse(rate,explicit)
    local def=SETTING.pulse_seconds
    if explicit~=nil then return explicit,false end
    local donor=M.DONOR_SETTINGS.pulse_seconds
    local limit=M.pulse_limit(rate)
    if donor<=limit+1e-6 then return donor,false end
    return math.max(limit,def.min),true
end
-- The record bytes a weapon's own record holds for its settings: the donor's but for +104..+115.
local function settings_record(values)
    local out={}
    for i,def in ipairs(C.settings)do
        local value=values[def.id]
        out[i]=value~=nil and b.encode(value,def.storage)or DONOR:sub(def.offset+1,def.offset+4)
    end
    return DONOR:sub(1,SETTINGS_FROM)..table.concat(out)..DONOR:sub(SETTINGS_TO+1)
end
M.settings_record=settings_record

--------------------------------------------------------------------------------------------------- the changes --
local function list_window_bytes(world,R,hexlist)
    local list=b.unhex(hexlist)
    local cur=world.view.read(R.window,R.window_size)
    if not cur then fail('TARGET_UNAVAILABLE: the '..R.w.name..'\'s membership list is unreadable')end
    local offset=R.window-R.list
    local inside=list:sub(offset+1,math.min(offset+R.window_size,#list))
    return inside..cur:sub(#inside+1)
end
-- {label, address, before, desired, owner}
local function list_changes(world,R,forward)
    local root=R.root
    local x,y=list_window_bytes(world,R,root.membership.before),list_window_bytes(world,R,root.membership.after)
    local out={}
    if R.split then
        local a,c=forward and x or y,forward and y or x
        out[1]={R.w.id..'.list+'..(R.window-R.list),R.window,a:sub(1,R.split),c:sub(1,R.split)}
        out[2]={R.w.id..'.list+'..(R.window+R.split-R.list),R.window+R.split,a:sub(R.split+1),c:sub(R.split+1)}
    else
        out[1]={R.w.id..'.list+'..(R.window-R.list),R.window,forward and x or y,forward and y or x}
    end
    if root.magazine then
        local mx,my=b.unhex(root.magazine.before),b.unhex(root.magazine.after)
        local mag={R.w.id..'.magazine'..root.magazine.record..'+'..MZ.window,R.chamber_at,forward and mx or my,
            forward and my or mx}
        if forward then out[#out+1]=mag else table.insert(out,1,mag)end
    end
    return out
end
-- The add layout of one root ({label, address, before, desired}), in the order to write them. Forward (apply): its
-- ProjectileWeapon +0 -> 0 (and, on a heat weapon, +8 -> the heat bound), the chamber magazine, then the entity map
-- row's list pointer -> its slot in the list block, then the count -> N + 1 (between the two a reader would see the
-- first N entries of the grown list, never a byte past it). Backward (restore): every part that is not vanilla, in
-- reverse: the count, the pointer, the magazine, the record. heat_rate: the 4 bytes +8 gets (forward, heat weapons).
local function add_changes(world,R,forward,heat_rate)
    local root,id=R.root,R.w.id..'.'..R.root.resource:sub(-4)
    local file_list=R.list
    local out={}
    local pw={}
    local function pw_change(offset,want,label)
        local at=R.pw_at+offset
        local cur=R.pw_record:sub(offset+1,offset+4)
        if cur~=want then pw[#pw+1]={id..'.projectile'..root.projectile.record..label,at,cur,want}end
    end
    local mag
    if root.magazine and R.chamber then
        local mx,my=b.unhex(root.magazine.before),b.unhex(root.magazine.after)
        local cur=b.unhex(R.chamber)
        local want=forward and my or mx
        if cur~=want then mag={id..'.magazine'..root.magazine.record..'+'..MZ.window,R.chamber_at,cur,want}end
    end
    if forward then
        pw_change(PJ.typeOffset,string.rep('\0',4),'+0')
        if heat_rate then pw_change(PJ.rateOffset,heat_rate,'+8')end
        for _,c in ipairs(pw)do out[#out+1]=c end
        if mag then out[#out+1]=mag end
        local target=R.lists_slot
        assert(target,'the list block slot')
        out[#out+1]={id..'.list_pointer',R.row_at+8,u64(file_list),u64(target)}
        out[#out+1]={id..'.list_count',R.row_at+16,b.encode(root.membership.count,'u32'),b.encode(root.add.count,'u32')}
        return out
    end
    if R.pointer=='owned'then
        out[#out+1]={id..'.list_count',R.row_at+16,b.encode(root.add.count,'u32'),b.encode(root.membership.count,'u32')}
        out[#out+1]={id..'.list_pointer',R.row_at+8,u64(R.row_pointer),u64(file_list)}
    end
    if mag then out[#out+1]=mag end
    if R.pw_type and R.pw_type~=root.add.typeBefore then pw_change(PJ.typeOffset,b.unhex(root.add.typeBefore),'+0')end
    if R.pw_rate and R.pw_rate~=root.add.rateBefore then pw_change(PJ.rateOffset,b.unhex(root.add.rateBefore),'+8')end
    for _,c in ipairs(pw)do out[#out+1]=c end
    return out
end
local function row_write(prefix,at,row_bytes,owner)
    -- record index first, then the key: the key makes the row findable only once its record is right.
    return {{prefix..'.record',at+8,nil,row_bytes:sub(9,16),owner},{prefix..'.key',at,nil,row_bytes:sub(1,8),owner}}
end
local function row_clear(prefix,at,owner)
    return {{prefix..'.key',at,nil,ZERO8,owner},{prefix..'.record',at+8,nil,ZERO8,owner}}
end

-- The plan for the guarded transaction (core/guarded_transaction.lua). changes = {{label, address, before (nil:
-- read now), desired, owner (nil: the entity allocation)}}, contexts = {{owner, address, bytes}}.
local function make_plan(world,s,changes,contexts,roots)
    local plan={snapshots={{owner=s.owner,offset=s.table-s.base,bytes=s.table_bytes}},changes={}}
    for _,R in ipairs(roots)do
        plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.list_context_at-s.base,bytes=R.list_context}
        if R.mrecord then
            plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.mrecord_at-s.base,bytes=R.mrecord}
        end
        if R.row_context then
            plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.row_context_at-s.base,bytes=R.row_context}
        end
        if R.pw_record then
            plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.pw_at-s.base,bytes=R.pw_record}
        end
    end
    for _,x in ipairs(contexts or{})do
        plan.snapshots[#plan.snapshots+1]={owner=x[1],offset=x[2]-x[1].base,bytes=x[3]}
    end
    -- Overlapping contexts of one owner (adjacent lists of two roots) become one: a target must lie in exactly one.
    table.sort(plan.snapshots,function(a,c)
        if a.owner.base~=c.owner.base then return a.owner.base<c.owner.base end
        return a.offset<c.offset
    end)
    local merged={}
    for _,x in ipairs(plan.snapshots)do
        local last=merged[#merged]
        if last and last.owner.base==x.owner.base and x.offset<=last.offset+#last.bytes then
            local overlap=last.offset+#last.bytes-x.offset
            if overlap>#x.bytes then overlap=#x.bytes end
            if last.bytes:sub(#last.bytes-(last.offset+#last.bytes-x.offset)+1,
                #last.bytes-(last.offset+#last.bytes-x.offset)+overlap)~=x.bytes:sub(1,overlap)then
                fail('TARGET_UNAVAILABLE: unstable ownership/data snapshot (overlapping contexts differ)')
            end
            if x.offset+#x.bytes>last.offset+#last.bytes then
                last.bytes=last.bytes..x.bytes:sub(overlap+1)
            end
            if x.owner.size>last.owner.size then last.owner=x.owner end
        else
            merged[#merged+1]={owner=x.owner,offset=x.offset,bytes=x.bytes}
        end
    end
    plan.snapshots=merged
    for _,c in ipairs(changes)do
        local owner=c[5]or s.owner
        local before=c[3]or world.view.read(c[2],#c[4])
        if not before then fail('TARGET_UNAVAILABLE: a conversion target is unreadable')end
        plan.changes[#plan.changes+1]={label='beam_conversion.'..c[1],owner=owner,offset=c[2]-owner.base,
            expected=c[3]and c[3]or before,desired=c[4],before=before,already_desired=before==c[4],
            packed=c[2]%4~=0 or nil,identity={component='BeamWeaponComponentData',component_type='native',
            record_type='beam_conversion',unique_owner=true,owner_count=1},chain={}}
    end
    return plan
end

-- reviewed_edits (core/reviewed_edits.lua): a converted root's exact state, or nothing.
local function refuse_projectile(w)
    return('BEAM CONVERSION: the %s fires Trident pulses (its ProjectileWeapon component is dormant while converted); '
        ..'writes to its fire rate, projectile, ammunition and the rows they link to are refused until the conversion '
        ..'is restored (owner: HD2Runtime beam conversion)'):format(w.name)
end
local function refuse_record(w)
    return('BEAM CONVERSION: the %s\'s own beam record belongs to its beam conversion: set its rate and pulse on '
        ..'hd2.weapon(name):beam_conversion() (owner: HD2Runtime beam conversion)'):format(w.name)
end
local function refuse_projectile_add(w)
    return('BEAM CONVERSION: the %s fires Trident pulses (add layout: its ProjectileWeapon type is 0 so its projectile '
        ..'path fires nothing%s); writes to its ProjectileWeapon record and the rows it links to are refused until the '
        ..'conversion is restored (owner: HD2Runtime beam conversion)'):format(w.name,
        w.add and w.add.heat and', and its rate is the heat bound of its pulse'or'')
end
local function record_edits(s)
    for _,W in pairs(s.weapons)do
        for _,R in ipairs(W.roots)do
            local root=R.root
            if R.state=='converted'and R.layout=='add'then
                local rows={[BW.component]={row=R.row,record=s.path_mode=='owned'and W.w.record or BW.defaultRecord},
                    [PJ.component]={row=root.projectile.row,record=root.projectile.record}}
                if root.magazine then rows[MZ.component]={row=root.magazine.row,record=root.magazine.record}end
                edits.set(root.resource,{owner=M.OWNER,stage='converted (add layout)',
                    membership=b.unhex(root.add.listHex),rows=rows,absent={},
                    refuse={[PJ.component]=refuse_projectile_add(W.w),[BW.component]=refuse_record(W.w)}})
            elseif R.state=='converted'then
                local rows={[BW.component]={row=R.row,record=s.path_mode=='owned'and W.w.record or BW.defaultRecord},
                    [PJ.component]={row=root.projectile.row,record=root.projectile.record}}
                if root.magazine then rows[MZ.component]={row=root.magazine.row,record=root.magazine.record}end
                edits.set(root.resource,{owner=M.OWNER,stage='converted',membership=b.unhex(root.membership.after),
                    rows=rows,absent={[PJ.component]=true},
                    refuse={[PJ.component]=refuse_projectile(W.w),[BW.component]=refuse_record(W.w)}})
            else
                local e=edits.get(root.resource)
                if e and e.owner==M.OWNER then edits.clear(root.resource)end
            end
            -- The catalogue's acceptance of exactly this row's relocated list (core/owned_tables.lua).
            if R.pointer=='owned'and s.lists then
                owned.set_list(root.resource,{owner=M.OWNER,row=root.membership.row,list=s.lists.allocation+root.add.slot,
                    count=root.add.count,bytes=b.unhex(root.add.listHex),allocation=s.lists.allocation,size=s.lists.size,
                    original=R.list,original_count=root.membership.count})
            else
                local e=owned.get_list(root.resource)
                if e and e.owner==M.OWNER then owned.clear_list(root.resource)end
            end
        end
    end
end
M.record_edits=record_edits

------------------------------------------------------------------------------------------------- the operation --
-- request = {weapon = catalogue entry, enabled = bool, settings = {fire_rate, pulse_beams, pulse_seconds} (values
-- the record must hold; nil members: the donor's), rows = {[field id] = value} (the weapon's own beam / damage row
-- values; nil or all the Trident's: no own rows needed)}. Returns {plan (with notes), commit, state, path} or raises.
-- A converted weapon with other settings: only its record and its own rows (no gate). Enable: gates, then [the row
-- block values, the borrowed slots], the copy / rows / lists / magazine bytes. Disable: gates (census; a live shot of
-- its borrowed BeamType), then magazine bytes, lists, index rows (algorithm R), its record back to the donor, the
-- borrowed slots back; the last disable puts the slot back.
function M.prepare(world,s,request)
    local w=assert(request.weapon,'beam conversion weapon')
    if not w.supported then fail('REFUSED: '..w.reasonCode..': '..w.reason)end
    local W=assert(s.weapons[w.name],'located weapon')
    local R=require('hd2runtime/runtime/beam_conversion_rows')
    local notes={}
    if W.state=='foreign'then
        local d={}
        for _,root in ipairs(W.roots)do d[#d+1]=root.detail end
        fail('CONFLICT: the '..w.name..' is in a state the beam conversion did not make ('..table.concat(d,'; ')
            ..(W.record_foreign and'; its own record'or'')..')')
    end
    local rows_values=request.rows or{}
    local rows_needed=R.needed(rows_values)
    local t=s.tb
    local changes,contexts,roots={},{},{}
    local commit={}
    local function anchor()
        -- Nothing to write: the lists as they are (the ensure's steady-state check keeps watching them).
        for _,X in ipairs(W.roots)do
            local cur=world.view.read(X.window,X.window_size)
            local n=X.split or X.window_size
            changes[#changes+1]={X.w.id..'.list+'..(X.window-X.list),X.window,cur:sub(1,n),cur:sub(1,n)}
            roots[#roots+1]=X
        end
    end
    local function record_changes(current,want)
        for at=0,BW.recordStride-4,4 do
            local x,y=current:sub(at+1,at+4),want:sub(at+1,at+4)
            if x~=y then changes[#changes+1]={('%s.record%d+%d'):format(w.id,w.record,at),W.record_at+at,x,y,
                t.copy_owner}end
        end
    end
    -- Own rows: the pair this weapon holds, or a free one borrowed now (owned table path only). Returns the pair.
    local function own_rows(path)
        if not rows_needed and not W.pair then return nil end
        if path~='owned'then
            fail('REFUSED: SHARED_RECORD_FALLBACK: per-weapon damage, AP and range need the owned table (the conversion '
                ..'runs on the shared record 23)')
        end
        if s.rs.unavailable then fail('REFUSED: '..s.rs.unavailable)end
        local i=W.pair
        if not i then
            for n,P in ipairs(s.rs.pairs)do
                if not i and not s.pair_user[n]and(P.state=='free'or P.state=='owned')then i=n end
            end
            if not i then
                local why={}
                for n,P in ipairs(s.rs.pairs)do
                    why[#why+1]=('pair %d: %s'):format(n,s.pair_user[n]and('the '..s.pair_user[n])or P.state
                        ..(P.reason and(' ('..P.reason..')')or''))
                end
                fail('REFUSED: ROWS_FULL: every borrowed beam / damage row pair is in use or unavailable ('
                    ..table.concat(why,'; ')..'): at most '..R.PAIRS..' converted weapons have their own damage, AP '
                    ..'and range at once')
            end
            local busy,why=R.ring_busy(world,s.rs.pairs[i].k,s.rs.pairs[i].d)
            if busy then fail('TARGET_UNAVAILABLE: BUSY: '..tostring(why))end
            R.build(world,s.rs)
            notes[#notes+1]=('own rows: BeamType %d and DamageInfo %d (borrowed spare slots, interim, this build '
                ..'only) now hold the %s\'s beam and damage'):format(s.rs.pairs[i].k,s.rs.pairs[i].d,w.name)
        end
        for _,c in ipairs(R.value_changes(s.rs,i,rows_values))do changes[#changes+1]=c end
        if s.rs.pairs[i].state=='free'then
            local cs,ctx=R.assign_changes(s.rs,i)
            for _,c in ipairs(cs)do changes[#changes+1]=c end
            for _,x in ipairs(ctx)do contexts[#contexts+1]=x end
        end
        contexts[#contexts+1]={s.rs.block_owner,s.rs.block.allocation,s.rs.block_bytes}
        return i
    end
    local function want_record(pair)
        local rec=settings_record(request.settings or{})
        if pair then rec=b.encode(s.rs.pairs[pair].k,'u32')..rec:sub(5)end
        return rec
    end
    -- The hd2bc entries this weapon will post after the request (runtime/beam_conversion_sync.lua): its layout, path,
    -- the record it will hold and its own rows, pair-independent.
    local function prospective(layout,path)
        local sync=require('hd2runtime/runtime/beam_conversion_sync')
        local beam,damage
        if rows_needed then beam,damage=R.rows_for(1,rows_values)end
        local record=path=='owned'and settings_record(request.settings or{})or DONOR
        return sync.weapon_entries(w,layout,path=='owned'and'o'or's',record,beam,damage)
    end
    -- The ProjectileWeapon rate (+8) a heat weapon of the add layout gets for the record it will hold.
    local function heat_rate_for(record)
        if not(w.add and w.add.heat)then return nil end
        local settings=decode_settings(record)
        return f32(M.heat_projectile_rate(settings.fire_rate,settings.pulse_seconds))
    end
    if request.enabled then
        if W.state=='orphaned'then
            fail('REFUSED: the '..w.name..'\'s list is still converted but no table row names it (an owned copy that '
                ..'died): disable the conversion first to restore it')
        end
        if W.state=='converted'then
            if s.path_mode=='shared'then
                if settings_record(request.settings or{})~=DONOR or rows_needed then
                    fail('REFUSED: SHARED_RECORD_FALLBACK: the conversion runs on the shared record 23 (the owned '
                        ..'table was unavailable when it was applied): every converted weapon fires the Trident\'s '
                        ..'own rate, pulse and damage; disable every conversion and enable it again for per-weapon '
                        ..'settings')
                end
                anchor()
            else
                local want=settings_record(request.settings or{})
                if W.layout=='add'then
                    -- A change of what this weapon posts (its record but the BeamType, or its own rows) needs the
                    -- others' agreement while they are present.
                    local changing=W.record:sub(5)~=want:sub(5)or(rows_needed and not W.pair)
                    if not changing and W.pair then
                        local P=s.rs.pairs[W.pair]
                        local nb,nd=R.rows_for(W.pair,rows_values)
                        changing=nb~=P.beam or nd~=P.damage
                    end
                    if changing then mp_gate(world,'add',prospective('add','owned'))end
                end
                local pair=own_rows('owned')
                record_changes(W.record,want_record(pair))
                local rate=W.layout=='add'and heat_rate_for(want_record(pair))
                if rate then
                    for _,X in ipairs(W.roots)do
                        if X.pw_rate~=hex(rate)then
                            changes[#changes+1]={X.w.id..'.'..X.root.resource:sub(-4)..'.projectile'
                                ..X.root.projectile.record..'+8',X.pw_at+PJ.rateOffset,b.unhex(X.pw_rate),rate}
                            roots[#roots+1]=X
                        end
                    end
                end
                if#changes==0 then anchor()else contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}end
                commit.pair=pair
            end
            return {plan=make_plan(world,s,changes,contexts,roots),state='converted',path=s.path_mode,notes=notes,
                commit=commit}
        end
        -- vanilla -> converted
        local layout=w.layout
        if layout~='add'and layout~='swap'then fail('REFUSED: the '..w.name..' has no beam conversion layout')end
        if layout=='add'and not session().lists and type(world.runtime.permanent_block)~='function'then
            -- The proven path stays the fallback: without its list block the add layout cannot relocate a list.
            layout='swap'
            notes[#notes+1]='the add layout needs its list block, which this Runtime adapter cannot allocate: the swap '
                ..'layout is used (solo only; restart the game after using it)'
        end
        local path=s.path_mode
        if not path then
            local ok,why=owned_available(world,t)
            if ok then path='owned'
            else
                path='shared'
                notes[#notes+1]='the owned table is unavailable ('..tostring(why)..'): the shared record 23 is used '
                    ..'(one Trident rate and pulse for every converted weapon)'
            end
        end
        if path=='shared'and settings_record(request.settings or{})~=DONOR then
            fail('REFUSED: SHARED_RECORD_FALLBACK: the owned table is unavailable, so the conversion would share the '
                ..'Trident\'s record 23 with every converted weapon: per-weapon rate and pulse need the owned table')
        end
        gates(world,s,{w},true,layout,prospective(layout,path))
        local heat_rate
        if layout=='add'then
            -- Pinned before-bytes of the records the add layout writes: its own type (the vanilla state checked it)
            -- and, on a heat weapon, its own rate (another write's rate is not overwritten).
            heat_rate=heat_rate_for(path=='owned'and settings_record(request.settings or{})or DONOR)
            for _,X in ipairs(W.roots)do
                if heat_rate and X.pw_rate~=X.root.add.rateBefore then
                    fail('CONFLICT: the '..w.name..'\'s ProjectileWeapon fire rate is not its vanilla value (another '
                        ..'write changed it, e.g. weapon.fire_rate): the add layout pins it; restore it first')
                end
            end
            local blk=build_lists(world)
            s.lists=blk
            for _,X in ipairs(W.roots)do X.lists_slot=blk.allocation+X.root.add.slot end
            contexts[#contexts+1]={{base=blk.allocation,size=blk.size,type=PRIVATE,protect=READONLY},blk.allocation,
                list_bytes()}
        end
        local pair=own_rows(path)
        -- Index rows: one per root, each the first empty row on its probe path in the table the game reads (with the
        -- rows already placed in this operation), always leaving one row empty.
        local rows=s.rows
        local placed={}
        local record_index=path=='owned'and w.record or BW.defaultRecord
        for _,X in ipairs(W.roots)do
            local at=insert_row(rows,X.root.resource)
            if not at or free_rows(rows)<=L.minFreeRows then
                fail('REFUSED: TABLE_FULL: the BeamWeapon table has no free row for the '..w.name
                    ..' (every row but the last free one is used): disable another conversion first')
            end
            local bytes=key_bytes(X.root.resource)..b.encode(record_index,'u32')..b.encode(0,'u32')
            rows=rows:sub(1,at*16)..bytes..rows:sub(at*16+17)
            placed[#placed+1]={X=X,row=at,bytes=bytes}
        end
        if path=='owned'and t.mode=='in_place'then
            -- Build the copy with these rows and this record, then ONE transaction: [own rows], the slot, the lists.
            local new_rows={}
            for _,p in ipairs(placed)do new_rows[p.row]=p.bytes end
            local entry=build(world,t,new_rows,{[w.record]=want_record(pair)})
            local copy=world.view.read(entry.allocation,entry.size)
            local copy_owner={base=entry.allocation,size=entry.size,type=PRIVATE,protect=READONLY}
            changes[#changes+1]={'slot270',t.slot_at,u64(t.original),u64(entry.table),t.manager_owner}
            contexts[#contexts+1]={t.manager_owner,t.slot_at,u64(t.original)}
            contexts[#contexts+1]={copy_owner,entry.allocation,copy}
            commit.register=entry
        elseif path=='owned'then
            record_changes(W.record,want_record(pair))
            for _,p in ipairs(placed)do
                for _,c in ipairs(row_write(w.id..'.row'..p.row,s.ctable+p.row*16,p.bytes,t.copy_owner))do
                    c[3]=ZERO8;changes[#changes+1]=c
                end
            end
            contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}
        else
            if s.record23=='vanilla'then
                for i=0,BW.recordStride-4,4 do
                    local p,q=VANILLA_RECORD23:sub(i+1,i+4),DONOR:sub(i+1,i+4)
                    if p~=q then changes[#changes+1]={('record23+%d'):format(i),s.record23_at+i,p,q}end
                end
            end
            for _,p in ipairs(placed)do
                for _,c in ipairs(row_write(w.id..'.row'..p.row,s.table+p.row*16,p.bytes))do
                    c[3]=ZERO8;changes[#changes+1]=c
                end
            end
        end
        for _,X in ipairs(W.roots)do
            local list=layout=='add'and add_changes(world,X,true,heat_rate)or list_changes(world,X,true)
            for _,c in ipairs(list)do changes[#changes+1]=c end
            roots[#roots+1]=X
        end
        commit.converted=w;commit.path=path;commit.pair=pair;commit.layout=layout
        return {plan=make_plan(world,s,changes,contexts,roots),state='vanilla',path=path,notes=notes,commit=commit}
    end
    -- disable
    if W.state=='vanilla'then
        anchor()
        return {plan=make_plan(world,s,changes,contexts,roots),state='vanilla',path=s.path_mode,notes=notes,
            commit=commit}
    end
    -- Gates: the census of this weapon's roots (no solo gate: a restore makes this machine agree with the others), and
    -- no live shot of its borrowed BeamType (one pulse).
    gates(world,s,{w},false)
    if W.pair then
        local busy,why=R.ring_busy(world,s.rs.pairs[W.pair].k,s.rs.pairs[W.pair].d)
        if busy then fail('TARGET_UNAVAILABLE: BUSY: '..tostring(why))end
    end
    for _,X in ipairs(W.roots)do
        local list
        if X.root.add and(X.pointer=='owned'or X.parts.projectile=='zero'or X.reloaded)then
            list=add_changes(world,X,false)
        else
            list=list_changes(world,X,false)
        end
        for _,c in ipairs(list)do changes[#changes+1]=c end
        roots[#roots+1]=X
    end
    -- Index rows: remove each root's row (algorithm R) from the table the game reads.
    local rows=s.rows
    local owned_path=s.path_mode=='owned'
    local base_at=owned_path and s.ctable or s.table
    local row_owner=owned_path and t.copy_owner or nil
    for _,X in ipairs(W.roots)do
        if X.row then
            local plan=delete_plan(rows,X.row,function(resource)
                local hit=BY_RESOURCE[resource]
                return hit~=nil and hit.weapon~=w
            end)
            local after=apply_delete(rows,plan)
            for _,m in ipairs(plan.moves)do
                local bytes=rows:sub(m.from*16+1,m.from*16+16)
                for _,c in ipairs(row_write(w.id..'.move'..m.from..'to'..m.to,base_at+m.to*16,bytes,row_owner))do
                    changes[#changes+1]=c
                end
                notes[#notes+1]=('row %d (%s) moved to row %d (linear-probing deletion)'):format(m.from,m.resource,
                    m.to)
            end
            for _,c in ipairs(row_clear(w.id..'.clear'..plan.clear,base_at+plan.clear*16,row_owner))do
                changes[#changes+1]=c
            end
            rows=after
        end
    end
    -- The weapon's own record back to the donor (owned), then its borrowed slots back.
    if owned_path then record_changes(W.record,DONOR)end
    if W.pair then
        local cs,ctx=R.release_changes(s.rs,W.pair)
        for _,c in ipairs(cs)do changes[#changes+1]=c end
        for _,x in ipairs(ctx)do contexts[#contexts+1]=x end
        notes[#notes+1]=('own rows released: BeamType %d and DamageInfo %d point at their vanilla rows again')
            :format(s.rs.pairs[W.pair].k,s.rs.pairs[W.pair].d)
    end
    -- The last conversion: the slot back (owned, no drift), or record 23 back (shared).
    local remaining=0
    for name,X in pairs(s.weapons)do
        if name~=w.name and(X.state=='converted'or X.state=='orphaned')then remaining=remaining+1 end
    end
    if remaining==0 then
        if owned_path then
            if#s.drift==0 then
                changes[#changes+1]={'slot270',t.slot_at,u64(t.entry.table),u64(t.original),t.manager_owner}
                contexts[#contexts+1]={t.manager_owner,t.slot_at,u64(t.entry.table)}
                commit.forget=true
            else
                notes[#notes+1]=('the owned copy stays live: record%s %s changed in it while it was live (a typed '
                    ..'write such as a mod\'s beam.fire_rate); the game would lose that write if it read the file\'s '
                    ..'table again'):format(#s.drift==1 and''or's',table.concat(s.drift,', '))
            end
        elseif s.record23=='copy'then
            for i=0,BW.recordStride-4,4 do
                local p,q=DONOR:sub(i+1,i+4),VANILLA_RECORD23:sub(i+1,i+4)
                if p~=q then changes[#changes+1]={('record23+%d'):format(i),s.record23_at+i,p,q}end
            end
        end
    end
    if owned_path then contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}end
    if W.pair then contexts[#contexts+1]={s.rs.block_owner,s.rs.block.allocation,s.rs.block_bytes}end
    commit.restored=w
    return {plan=make_plan(world,s,changes,contexts,roots),state=W.state,path=s.path_mode,notes=notes,commit=commit}
end

-- After the transaction: register the copy, record the reviewed edits, the restart notice and the lobby watch.
function M.commit(world,prepared,report)
    if not(report and(report.status=='APPLIED'or report.status=='ALREADY_DESIRED'))then return end
    local commit=prepared.commit or{}
    if commit.register then owned.set(BW.component,commit.register)end
    if commit.forget then owned.clear(BW.component)end
    if commit.converted and commit.layout=='add'then
        log(('%s CONVERTED [add layout, %s]: spawned from now on it fires LAS-13 Trident pulses; it keeps '
            ..'ProjectileWeapon (type 0: its projectile path fires nothing) and gains BeamWeapon through a Runtime-owned '
            ..'list; with other players only when every member holds the identical conversion'):format(
            commit.converted.name,M.PATHS[commit.path]or tostring(commit.path)))
    elseif commit.converted then
        session().used=true
        log(('%s CONVERTED [swap layout, %s]: spawned from now on it fires LAS-13 Trident pulses; solo only; RESTART '
            ..'THE GAME after using it'):format(commit.converted.name,M.PATHS[commit.path]or tostring(commit.path)))
    end
    if commit.restored then log(commit.restored.name..' RESTORED: every byte of its conversion is vanilla again')end
    local ok,s=pcall(locate,world)
    if ok then
        record_edits(s)
        require('hd2runtime/runtime/beam_conversion_watch').sync(s)
        -- The lobby's view of this machine's conversions (runtime/beam_conversion_sync.lua, the hd2bc key).
        pcall(function()require('hd2runtime/runtime/beam_conversion_sync').note(s)end)
    else
        log('after the write the state could not be re-read: '..clean(s))
    end
end

------------------------------------------------------------------------------------------------------ the status --
-- Read-only: {ok, path, table, copies, restart_required, lobby, lists, weapons = {[name] = {state, layout, multiplayer,
-- settings, live, roots}}}.
function M.status()
    local ok,result=pcall(function()
        local world=open()
        local s=locate(world)
        local count=census(world,s.manager)
        local lob,why=lobby(world)
        local out={ok=true,path=s.path_mode and M.PATHS[s.path_mode]or'none',table=s.tb.mode,copies=session().copies,
            restart_required=session().used,lobby=lob or'unknown',lobby_reason=why,
            drift=#s.drift>0 and s.drift or nil,lists=s.lists and'built'or'none',weapons={}}
        for name,W in pairs(s.weapons)do
            local layout=W.layout or W.w.layout
            local entry={state=W.state,live=count and live_of(count,W.w)or nil,roots={},layout=layout,
                multiplayer=layout=='add'and'identical conversions only'or layout=='swap'and'solo only'or nil}
            if W.state=='converted'then
                entry.settings=s.path_mode=='owned'and decode_settings(W.record)or decode_settings(DONOR)
                entry.rows=M.rows_of(s,W)
                if W.pair then entry.pair={beamType=s.rs.pairs[W.pair].k,damageInfo=s.rs.pairs[W.pair].d}end
            end
            for _,R in ipairs(W.roots)do entry.roots[#entry.roots+1]={resource=R.root.resource,state=R.state,
                detail=R.detail}end
            out.weapons[name]=entry
        end
        record_edits(s)
        return out
    end)
    if ok then return result end
    return {ok=false,reason=clean(result)}
end
-- Quiet: the converted weapon names now (nil, why when unreadable).
function M.converted()
    local ok,result=pcall(function()
        local s=locate(open())
        local out={}
        for name,W in pairs(s.weapons)do if W.state=='converted'or W.state=='orphaned'then out[#out+1]=name end end
        table.sort(out)
        return out,s
    end)
    if ok then return result end
    return nil,clean(result)
end
function M.restart_required()return session().used end

-- A located weapon's own beam / damage row values (its borrowed pair's, else the Trident's).
function M.rows_of(s,W)
    local R=require('hd2runtime/runtime/beam_conversion_rows')
    if W.pair then local P=s.rs.pairs[W.pair];return R.values_of(P.beam,P.damage)end
    return R.defaults()
end

-- Tests only.
function M.set_hooks_for_tests(h)hooks=h or{}end
function M.reset_for_tests()
    proven={};hooks={};rawset(_G,STATE_KEY,nil)
    require('hd2runtime/runtime/beam_conversion_sync').reset_for_tests()
    require('hd2runtime/runtime/beam_conversion_rows').reset_for_tests()
    for _,w in ipairs(C.weapons)do for _,root in ipairs(w.roots or{})do
        local e=edits.get(root.resource)
        if e and e.owner==M.OWNER then edits.clear(root.resource)end
    end end
    local e=owned.get(BW.component)
    if e and e.owner==M.OWNER then owned.clear(BW.component)end
    for _,w in ipairs(C.weapons)do for _,root in ipairs(w.roots or{})do
        local l=owned.get_list(root.resource)
        if l and l.owner==M.OWNER then owned.clear_list(root.resource)end
    end end
    LIST_BYTES=nil
end
return M
