-- BEAM CONVERSION (solo only): a projectile weapon fires LAS-13 Trident pulses (docs/beam-conversion.md;
-- research/docs/beam-conversion-coverage-F5FEE03DCFDB.md; domains/beam_conversion.lua, generated by
-- scripts/generate_beam_conversion.py). The productised form of the live-proven experiments (runtime/experiment_
-- liberator_beam.lua, runtime/experiment_beam_swap.lua and runtime/experiment_beam_table.lua, kept unchanged as the
-- proven fallbacks for their proofs), written through hd2.ensure / transactions on hd2.weapon(name):beam_conversion()
-- (domains/beam_conversion_writes.lua). Per converted root resource of a weapon, in this order (restore in reverse):
--   1. its BeamWeapon index row (record index, then key) in the table the game reads: the first empty row on its probe
--      path (home = resource mod 46, +1 with wrap). A restore removes the row with linear-probing deletion (Knuth's
--      algorithm R): a later converted row whose probe crossed the freed row moves into it before the last vacated
--      row is cleared, so every lookup finds its row at every step; a vanilla row never needs to move (vanilla rows
--      never cross a vanilla-empty row) and the module fails closed if one would;
--   2. its membership list: ProjectileWeapon (321) out, BeamWeapon (270) in, sorted, the same count, the pointer
--      unchanged (one 4-aligned window); its ProjectileWeapon row stays (the round spend reads it);
--   3. chamber magazines only (WeaponMagazine +156 = 1, a record the weapon owns alone): +156..+159 -> 0, the 40-K
--      Meltagun's no-chamber model (only a ProjectileWeapon instance fills a chamber).
-- Two paths, never mixed:
--   OWNED (the default): a Runtime-owned, never-freed copy of the BeamWeapon table (records 0..23 byte-identical to the
--     file, then one record per catalogued weapon, each a copy of the Trident's record 18), made live by ONE aligned
--     8-byte store into slot 270; rows go into the copy. Each weapon has its OWN record: its own rate of fire (+104),
--     beams per pulse (+108) and pulse length (+112). The last restore puts the slot back (when no record 0..23 of the
--     copy drifted: a typed write made while the copy was live would otherwise be lost).
--   SHARED (the fallback when the owned table is unavailable: a pin, the adapter, the copy budget): the file table's
--     one unowned record 23 := the Trident's record 18, rows in the file's own table; every converted weapon shares
--     it, so per-weapon settings other than the Trident's are refused on this path.
-- Every call re-proves the pins, re-derives every address and checks every target; any third state of a table, a row,
-- a list or a magazine byte is FOREIGN and refused (another mod: True Lasgun Beam Overhaul moves this table).
-- Gates (fail closed): ZERO live instances of every root written, at the write AND at the restore (the descriptor
-- census: ship previews, the armory, the loadout, pickups); solo for an apply (player list + lobby; unreadable fails
-- closed); the Trident's package resident (the request's asset dependency loads and holds it). A busy gate is
-- TARGET_UNAVAILABLE, so a transaction retries and an ensure with `recover` waits until it is clear.
-- A weapon spawned while converted may leave a ProjectileWeapon private copy nothing removes (a default ammunition
-- or muzzle delta that patches ProjectileWeapon): RESTART THE GAME after using a conversion (logged, and in status).
if rawget(_G,'jit')then jit.off(true,true)end
local world_module=require('hd2runtime/runtime/event_world')
local log_module=require('hd2runtime/runtime/log')
local edits=require('hd2runtime/core/reviewed_edits')
local owned=require('hd2runtime/core/owned_tables')
local b=require('hd2runtime/core/bytes')
local profile=require('hd2runtime/schemas/current')
local C=require('hd2runtime/domains/beam_conversion')
local CT=require('hd2runtime/domains/component_tables')
local unpack=unpack or table.unpack
local M={}
M.VERSION='1.0.0'
M.OWNER='HD2Runtime beam conversion'
M.PATHS={owned='owned table',shared='shared record'}
M.ACKNOWLEDGEMENT='allow_component_swap'
local PRIVATE,COMMIT,READONLY,READWRITE,PAGE=0x20000,0x1000,0x2,0x4,4096
local BW,MG,MZ,PJ,L=C.beam,C.manager,C.magazine,C.projectile,C.copy
local DONOR=b.unhex(C.trident.recordHex)            -- the Trident's record 18 (the reviewed copy source)
local VANILLA_ROWS=b.unhex(BW.vanillaRowsHex)       -- the file table's 46 index rows as reviewed
local VANILLA_RECORD23=b.unhex(BW.vanillaRecord23Hex)
local ZERO8,ZERO16=string.rep('\0',8),string.rep('\0',16)
local STATE_KEY='HD2RuntimeBeamConversionV1'        -- survives a module reload: the copy outlives every Lua module
local proven={}
local hooks={}

local SETTING,SETTINGS_FROM,SETTINGS_TO={},nil,nil
M.SETTINGS={}
for _,s in ipairs(C.settings)do
    SETTING[s.id]=s;M.SETTINGS[#M.SETTINGS+1]=s
    SETTINGS_FROM=math.min(SETTINGS_FROM or s.offset,s.offset);SETTINGS_TO=math.max(SETTINGS_TO or 0,s.offset+4)
end
local BY_NAME,BY_RESOURCE,RECORD_OF={},{},{}
for _,w in ipairs(C.weapons)do
    BY_NAME[w.name]=w
    for _,root in ipairs(w.roots or{})do BY_RESOURCE[root.resource]={weapon=w,root=root}end
end

local function session()
    local s=rawget(_G,STATE_KEY)
    if not s then s={used=false,copies=0,join_warned={}};rawset(_G,STATE_KEY,s)end
    return s
end
local function log(text)log_module.emit('BEAM CONVERSION: '..text)end
local function clean(why)return(tostring(why):gsub('^%[string "[^"]*"%]:%d+: ',''):gsub('^[^%s:]+:%d+: ',''))end
local function fail(text)error(text,0)end
local hex=b.hex
local function u64(value)
    local lo=value%4294967296
    return b.encode(lo,'u32')..b.encode((value-lo)/4294967296,'u32')
end
-- resource '0x...' -> {lo, hi} and its 8 little-endian key bytes.
local function key_bytes(resource)return b.unhex(resource:sub(3)):reverse()end
local TWO32=4294967296
local function home(resource,capacity)
    local hi,lo=tonumber(resource:sub(3,10),16),tonumber(resource:sub(11,18),16)
    return((hi%capacity)*(TWO32%capacity)+lo%capacity)%capacity
end
M.home=home

------------------------------------------------------------------------------------------------------- catalogue --
function M.catalogue()return C end
function M.weapon(name)return BY_NAME[name]end
-- The converted-record index of a weapon in the owned copy (records 24..).
function M.record_of(name)local w=BY_NAME[name];return w and w.record end

---------------------------------------------------------------------------------------------------------- proofs --
local function prove(world)
    local key=world.key
    if proven[key]==true then return true end
    if proven[key]then return nil,proven[key]end
    local why
    if C.source.gameDllSha256~=profile.dll_sha or CT.source.gameDllSha256~=profile.dll_sha then
        why='the beam conversion research covers another game.dll build'
    end
    local lists={C.pins,CT.pins,CT.lookups[BW.component]or{},CT.lookups[PJ.component]or{},CT.lookups[MZ.component]or{}}
    for _,list in ipairs(lists)do
        for _,pin in ipairs(list)do
            if not why and not world.view.proves(world.game+pin.rva,pin.hex)then
                why=('native code not as reviewed at game.dll+0x%X (%s)'):format(pin.rva,pin.label)
            end
        end
    end
    proven[key]=why or true
    if why then return nil,why end
    return true
end

local function region(world,at)
    local r=world.runtime.query(at)
    if not(r and r.state==COMMIT and r.type==PRIVATE and r.allocation_base and r.allocation_base>0
        and at>=r.base and at<r.base+r.size)then
        return nil
    end
    return r
end

-- A permanent block as the adapter left it: committed private pages of one allocation, every page readable
-- (READONLY, or READWRITE while a guarded transaction has it open).
local function block_ok(world,allocation,size,protect)
    for page=allocation,allocation+size-PAGE,PAGE do
        local q=world.runtime.query(page)
        if not(q and q.state==COMMIT and q.type==PRIVATE and q.allocation_base==allocation
            and(q.protect==(protect or READONLY)or not protect and q.protect==READWRITE))then
            return false
        end
    end
    return true
end
M.block_ok=block_ok

local function open()
    local world,why=world_module.open()
    if not world then fail('TARGET_UNAVAILABLE: '..tostring(why))end
    local ok,reason=prove(world)
    if not ok then fail('UNPROVEN: '..reason)end
    return world
end
M.open=open

----------------------------------------------------------------------------------------------------- the table --
local function trailer(original,records)
    return L.magic..u64(original)..b.encode(BW.index,'u32')..b.encode(records,'u32')
end
local function trailer_at(entry)return entry.table+BW.recordBase+entry.records*BW.recordStride end

-- Where the game reads the BeamWeapon table, re-derived and checked: t.mode 'in_place' (the entity allocation's own
-- table), 'owned' (exactly this module's registered copy over this original) or 'foreign' (t.reason).
local function locate_table(world)
    local manager=world.view.pointer(world.game+MG.global)
    if not manager then fail('TARGET_UNAVAILABLE: the entity manager is not initialised')end
    local t={manager=manager,slot_at=manager+MG.slotBase+8*BW.index}
    if t.slot_at%8~=0 then fail('the BeamWeapon slot is not 8-byte aligned')end
    t.slot=world.view.pointer(t.slot_at)
    if not t.slot then fail('TARGET_UNAVAILABLE: the BeamWeapon slot is unreadable')end
    local esh=world.view.pointer(manager+MG.eshSlot)
    if not esh then fail('TARGET_UNAVAILABLE: the entity map slot is unreadable')end
    t.base=esh-28
    if world.view.read(t.base,28)~=b.unhex(profile.map_header)then
        fail('CONFLICT: the game reads its EntitySettingsHashmap from another place (another mod moved it)')
    end
    local c=assert(profile.components[BW.component],'BeamWeapon profile component')
    assert(c.index==BW.index and c.indices==BW.capacity and c.records==BW.fileRecords and c.stride==BW.recordStride
        and c.record_offset==BW.recordBase,'the BeamWeapon schema differs from the research')
    t.original=t.base+c.offset+CT.tableFromProfileOffset
    t.framing=world.view.read(t.original-L.framing,L.framing)
    if not(t.framing and b.u32(t.framing,0)==c.index and t.framing:sub(5,32)==b.unhex(c.header))then
        fail('the BeamWeapon table framing changed')
    end
    t.file=world.view.read(t.original,BW.recordBase+BW.fileRecords*BW.recordStride)
    if not t.file then fail('TARGET_UNAVAILABLE: the BeamWeapon table is unreadable')end
    local mr=region(world,t.slot_at)
    local page=t.slot_at-t.slot_at%PAGE
    if not(mr and mr.protect==READWRITE and mr.base<=page and page+PAGE<=mr.base+mr.size)then
        t.slot_unwritable='the BeamWeapon slot\'s page is not one read-write private region'
    else
        t.manager_owner={base=mr.allocation_base,size=page+PAGE-mr.allocation_base,type=PRIVATE,protect=READWRITE}
    end
    local entry=owned.get(BW.component)
    if entry and entry.owner~=M.OWNER then
        -- Another HD2Runtime module (the beam experiments) owns the table this session: never mixed.
        if t.slot==entry.table and entry.original==t.original then
            t.mode='foreign'
            t.reason='CONFLICT: the BeamWeapon table is the copy of '..tostring(entry.owner)..' this session (an '
                ..'experiment proof): restore it with that proof, or restart the game'
            return t
        end
        entry=nil
    end
    if t.slot==t.original then
        t.mode='in_place'
        if entry then
            owned.clear(BW.component)
            t.reloaded=true
            log('RELOAD DETECTED: the slot holds the entity file\'s own table again: the conversion copy is dead '
                ..'(never freed) and forgotten; the BeamWeapon table is vanilla')
        end
        return t
    end
    if entry and t.slot==entry.table and entry.original==t.original then
        local q=region(world,entry.table)
        if not(q and block_ok(world,entry.allocation,entry.size))then
            fail('HD2Runtime\'s BeamWeapon copy is not the allocation it built')
        end
        if world.view.read(entry.table-L.framing,L.framing)~=t.framing then fail('the BeamWeapon copy framing changed')end
        if world.view.read(trailer_at(entry),L.trailerSize)~=trailer(entry.original,entry.records)then
            fail('the BeamWeapon copy trailer changed')
        end
        t.copy=world.view.read(entry.table,BW.recordBase+entry.records*BW.recordStride)
        if not t.copy then fail('TARGET_UNAVAILABLE: the BeamWeapon copy is unreadable')end
        t.mode='owned';t.entry=entry
        t.copy_owner={base=entry.allocation,size=entry.size,type=PRIVATE,protect=q.protect}
        return t
    end
    t.mode='foreign'
    if entry then
        owned.clear(BW.component)
        log('the slot no longer holds HD2Runtime\'s conversion copy: another program changed it; the copy is forgotten')
    end
    t.reason='CONFLICT: the game reads its BeamWeapon table from another place (another mod moved it, e.g. True '
        ..'Lasgun Beam Overhaul): HD2Runtime never chains onto a foreign copy'
    return t
end

-- How many copies this game process built (never freed); a new one is refused past L.maxCopies.
function M.copies()return session().copies end
local function owned_available(world,t)
    if t.mode=='owned'then return true end
    if not t.manager_owner then return nil,t.slot_unwritable end
    if type(world.runtime.permanent_block)~='function'then return nil,'this Runtime adapter cannot allocate memory'end
    if session().copies>=L.maxCopies then
        return nil,('%d copies were built this session (each stays allocated): restart the game'):format(session().copies)
    end
    return true
end

-- The copy's bytes: framing, rows (the file's, `rows` = {[row] = 16 bytes} written in), records 0..23 = the file's,
-- one record per catalogued weapon (`records` = {[index] = 120 bytes}, else the donor), then the trailer.
local function copy_bytes(t,rows,records)
    local body={t.framing}
    for row=0,BW.capacity-1 do
        local raw=t.file:sub(row*BW.rowStride+1,(row+1)*BW.rowStride)
        if rows[row]then
            assert(raw==ZERO16,'row '..row..' of the file table is not empty')
            raw=rows[row]
        end
        body[#body+1]=raw
    end
    body[#body+1]=t.file:sub(BW.recordBase+1,BW.recordBase+BW.fileRecords*BW.recordStride)
    for index=BW.fileRecords,L.records-1 do
        local rec=records[index]or DONOR
        assert(#rec==BW.recordStride,'record bytes')
        body[#body+1]=rec
    end
    body[#body+1]=trailer(t.original,L.records)
    local bytes=table.concat(body)
    assert(#bytes<=65536,'the copy is too large')
    return bytes
end
M.copy_bytes=copy_bytes

-- Builds the copy (NOT live): a permanent block, read back and checked; returns the entry (not registered).
local function build(world,t,rows,records)
    assert(t.mode=='in_place','a copy is built only while the game reads the file\'s own table')
    local ok,why=owned_available(world,t)
    if not ok then fail('REFUSED: the owned table is unavailable: '..tostring(why))end
    local bytes=copy_bytes(t,rows,records)
    local address=world.runtime.permanent_block(bytes)
    session().copies=session().copies+1
    assert(type(address)=='number'and address>0 and address%PAGE==0,'the permanent block is not page-aligned')
    local size=#bytes+(PAGE-#bytes%PAGE)%PAGE
    if not block_ok(world,address,size,READONLY)then
        fail('the copy is not one read-only private allocation')
    end
    if world.view.read(address,#bytes)~=bytes then fail('the copy did not read back as built')end
    log(('copy %d built: %d bytes (framing, 46 rows, records 0..23 as the file, %d conversion records, trailer) at a '
        ..'new private read-only block (never freed); not live yet'):format(session().copies,#bytes,
        L.records-BW.fileRecords))
    return {owner=M.OWNER,index=BW.index,table=address+L.framing,allocation=address,size=size,original=t.original,
        records=L.records}
end

---------------------------------------------------------------------------------------------------- index rows --
-- rows: the 46 x 16 index bytes of a table. The row of a resource by the game's probe (key 0 stops), or nil.
local function find_row(rows,resource)
    local key=key_bytes(resource)
    local at=home(resource,BW.capacity)
    for _=1,BW.capacity do
        local raw=rows:sub(at*16+1,at*16+8)
        if raw==key then return at end
        if raw==ZERO8 then return nil end
        at=(at+1)%BW.capacity
    end
    return nil
end
M.find_row=find_row
local function free_rows(rows)
    local n=0
    for row=0,BW.capacity-1 do if rows:sub(row*16+1,row*16+8)==ZERO8 then n=n+1 end end
    return n
end
-- The first empty row on a resource's probe path (an insert), or nil.
local function insert_row(rows,resource)
    local at=home(resource,BW.capacity)
    for _=1,BW.capacity do
        if rows:sub(at*16+1,at*16+8)==ZERO8 then return at end
        at=(at+1)%BW.capacity
    end
    return nil
end
M.insert_row=insert_row
local function key_home(rows,row)
    return home(b.resource(rows,row*16),BW.capacity)
end
-- Linear-probing deletion of row e (Knuth's algorithm R): {moves = {{from, to}}, clear = the last vacated row}.
-- A row moves when its home is not cyclically in (vacated, its row]. Only converted rows may move.
local function delete_plan(rows,e,movable)
    local moves={}
    local i,j=e,e
    for _=1,BW.capacity do
        j=(j+1)%BW.capacity
        if rows:sub(j*16+1,j*16+8)==ZERO8 then break end
        local k=key_home(rows,j)
        local stays
        if i<=j then stays=i<k and k<=j else stays=i<k or k<=j end
        if not stays then
            local resource=b.resource(rows,j*16)
            if not movable(resource)then
                fail(('CONFLICT: removing BeamWeapon row %d would strand row %d (%s), which is not a conversion row')
                    :format(e,j,resource))
            end
            moves[#moves+1]={from=j,to=i,resource=resource}
            i=j
        end
    end
    return {moves=moves,clear=i}
end
M.delete_plan=delete_plan
-- Applies a delete plan to a rows string (offline: what the rows become).
local function apply_delete(rows,plan)
    local out=rows
    for _,m in ipairs(plan.moves)do
        out=out:sub(1,m.to*16)..rows:sub(m.from*16+1,m.from*16+16)..out:sub(m.to*16+17)
    end
    return out:sub(1,plan.clear*16)..ZERO16..out:sub(plan.clear*16+17)
end
M.apply_delete=apply_delete

-------------------------------------------------------------------------------------------------- the locate --
local function component_table(world,manager,base,name)
    local c=assert(profile.components[name],'unknown component '..name)
    local at=world.view.pointer(manager+MG.slotBase+8*c.index)
    if at~=base+c.offset+CT.tableFromProfileOffset then
        fail('CONFLICT: the game reads its '..name..' table from another place (another mod moved it)')
    end
    local framing=world.view.read(at-32,32)
    if not(framing and b.u32(framing,0)==c.index and framing:sub(5,32)==b.unhex(c.header))then
        fail(name..' framing changed')
    end
    return at,c
end

-- One root's targets, re-derived and checked. rows: the index rows the game reads.
local function locate_root(world,s,w,root)
    local R={w=w,root=root}
    local prow=world.view.read(s.ptable+root.projectile.row*16,16)
    if not(prow and b.resource(prow,0)==root.resource and b.u32(prow,8)==root.projectile.record and b.u32(prow,12)==0)
    then
        fail('CONFLICT: the '..w.name..'\'s ProjectileWeapon row is not as reviewed (another mod changed it)')
    end
    local found
    local at=root.membership.home
    for _=1,C.membership.rows do
        local key=world.view.read(s.esh+at*C.membership.rowStride,8)
        if not key then fail('TARGET_UNAVAILABLE: the entity map is unreadable')end
        if key==ZERO8 then break end
        if b.resource(key,0)==root.resource then found=at;break end
        at=(at+1)%C.membership.rows
    end
    if found~=root.membership.row then
        fail(('the %s\'s entity map row is not row %d (found %s)'):format(w.name,root.membership.row,tostring(found)))
    end
    local settings_row=world.view.read(s.esh+found*C.membership.rowStride,C.membership.rowStride)
    local list=b.pointer(settings_row,8)
    if not(b.u32(settings_row,16)==root.membership.count and b.u32(settings_row,20)==0
        and b.u32(settings_row,24)==root.membership.networkType)then
        fail('the '..w.name..'\'s entity map row (count, network type) is not as reviewed')
    end
    if list-s.esh~=root.membership.listOffsetInBody then
        fail('CONFLICT: the '..w.name..'\'s membership list is not at its reviewed place (another mod moved it)')
    end
    local count=root.membership.count
    R.list=list
    R.list_bytes=world.view.read(list,count*2)
    if not R.list_bytes then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s membership list is unreadable')end
    local first=list+root.membership.firstChanged
    local finish=list+root.membership.endChanged
    R.window=first-first%4
    R.window_size=finish+(-finish)%4-R.window
    if not(R.window_size==4 or R.window_size==8 or R.window_size==12)then
        fail('the '..w.name..'\'s list window is not 4, 8 or 12 bytes')
    end
    -- A window across a page boundary (the LAS-12 Sai) is written as one 4-byte change on each side of it.
    if R.window%PAGE+R.window_size>PAGE and(PAGE-R.window%PAGE)%4~=0 then
        fail('the '..w.name..'\'s list window crosses a page off a 4-byte boundary')
    end
    R.list_context_at=list-16
    R.list_context=world.view.read(R.list_context_at,count*2+48)
    if not R.list_context then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s membership list context is unreadable')end
    local mz=root.magazine
    if mz then
        local mfound
        local mat=mz.home
        for _=1,MZ.capacity do
            local key=s.mrows:sub(mat*16+1,mat*16+8)
            if key==ZERO8 then break end
            if b.resource(key,0)==root.resource then mfound=mat;break end
            mat=(mat+1)%MZ.capacity
        end
        if mfound~=mz.row then
            fail(('the %s\'s WeaponMagazine row is not row %d (found %s)'):format(w.name,mz.row,tostring(mfound)))
        end
        if hex(s.mrows:sub(mz.row*16+1,mz.row*16+16))~=mz.rowBytes then
            fail('CONFLICT: the '..w.name..'\'s WeaponMagazine row is not as reviewed (another mod changed it)')
        end
        for n=0,MZ.capacity-1 do
            local raw=s.mrows:sub(n*16+1,n*16+16)
            if n~=mz.row and raw:sub(1,8)~=ZERO8 and b.u32(raw,8)==mz.record then
                fail(('CONFLICT: another WeaponMagazine row names record %d (the %s\'s)'):format(mz.record,w.name))
            end
        end
        R.mrecord_at=s.mtable+MZ.recordBase+mz.record*MZ.recordStride
        R.mrecord=world.view.read(R.mrecord_at,MZ.recordStride)
        if not R.mrecord then fail('TARGET_UNAVAILABLE: the '..w.name..'\'s magazine record is unreadable')end
        R.chamber_at=s.mtable+mz.windowOffset
        R.chamber=hex(R.mrecord:sub(MZ.window+1,MZ.window+4))
    end
    local extents
    local split=R.window%PAGE+R.window_size>PAGE and PAGE-R.window%PAGE or nil
    if split then extents={{R.window,split},{R.window+split,R.window_size-split}}else extents={{R.window,R.window_size}}end
    R.split=split
    if mz then extents[#extents+1]={R.chamber_at,4}end
    R.tops={}
    for _,extent in ipairs(extents)do
        local q=region(world,extent[1])
        if not(q and q.allocation_base==s.base and q.protect==READONLY and extent[1]+extent[2]<=q.base+q.size)then
            fail('a target page of the '..w.name..' is not in the entity allocation\'s read-only memory')
        end
        if extent[1]%4~=0 or extent[1]%PAGE+extent[2]>PAGE then
            fail('a target of the '..w.name..' crosses a page or is misaligned')
        end
        R.tops[#R.tops+1]=q.base+q.size
    end
    -- The state of this root.
    local lb=hex(R.list_bytes)
    local lst=lb==root.membership.before and'vanilla'or lb==root.membership.after and'converted'or'FOREIGN'
    local mag='n/a'
    if mz then mag=R.chamber==mz.before and'vanilla'or R.chamber==mz.after and'converted'or'FOREIGN'end
    R.row=find_row(s.rows,root.resource)
    local expected_record=s.path_mode=='owned'and w.record or BW.defaultRecord
    local row='none'
    if R.row then
        local raw=s.rows:sub(R.row*16+1,R.row*16+16)
        row=(b.u32(raw,8)==expected_record and b.u32(raw,12)==0)and'own'or'FOREIGN'
    end
    local mag_v=mag=='vanilla'or mag=='n/a'
    local mag_c=mag=='converted'or mag=='n/a'
    if lst=='vanilla'and row=='none'and mag_v then R.state='vanilla'
    elseif lst=='converted'and row=='own'and mag_c then R.state='converted'
    elseif lst=='converted'and row=='none'and mag_c then R.state='orphaned'
    else R.state='foreign'end
    R.detail=('list %s, row %s%s, magazine chamber %s'):format(lst,R.row and tostring(R.row)or'-',
        row=='FOREIGN'and' FOREIGN'or'',mag)
    return R
end

-- The weapon's state from its roots: 'vanilla' | 'converted' | 'orphaned' | 'foreign' | 'refused' (not supported).
local function weapon_state(roots)
    local seen={}
    for _,R in ipairs(roots)do seen[R.state]=true end
    if seen.foreign then return'foreign'end
    if seen.converted and not seen.vanilla and not seen.orphaned then return'converted'end
    if seen.vanilla and not seen.converted and not seen.orphaned then return'vanilla'end
    if seen.orphaned and not seen.converted then return'orphaned'end
    return'foreign'
end

-- Everything an operation needs, re-derived and checked. Returns s or raises.
local function locate(world)
    local t=locate_table(world)
    if t.mode=='foreign'then fail(t.reason)end
    local s={tb=t,manager=t.manager,base=t.base,esh=t.base+28,weapons={},by_resource={}}
    s.table,s.table_bytes=t.original,t.file
    s.path_mode=t.mode=='owned'and'owned'or nil
    -- The file's rows must be the reviewed vanilla rows, but for conversion rows in vanilla-empty rows (shared path).
    local file_rows=t.file:sub(1,BW.capacity*16)
    for row=0,BW.capacity-1 do
        local now,was=file_rows:sub(row*16+1,row*16+16),VANILLA_ROWS:sub(row*16+1,row*16+16)
        if now~=was then
            local mine=was==ZERO16 and BY_RESOURCE[b.resource(now,0)]and b.u32(now,8)==BW.defaultRecord
                and b.u32(now,12)==0
            if not mine then
                fail(('CONFLICT: BeamWeapon row %d of the file table is not as reviewed (another mod changed it)')
                    :format(row))
            end
            s.shared_rows=true
        end
    end
    local trident=file_rows:sub(C.trident.row*16+1,C.trident.row*16+16)
    if b.resource(trident,0)~=C.trident.resource or b.u32(trident,8)~=C.trident.record then
        fail('CONFLICT: BeamWeapon row '..C.trident.row..' is not the Trident\'s (another mod changed it)')
    end
    local source=t.file:sub(BW.recordBase+C.trident.record*BW.recordStride+1,
        BW.recordBase+(C.trident.record+1)*BW.recordStride)
    if source~=DONOR then
        fail('CONFLICT: the Trident\'s BeamWeapon record differs from the reviewed copy source (another mod changed it)')
    end
    local r23=t.file:sub(BW.recordBase+BW.defaultRecord*BW.recordStride+1,
        BW.recordBase+(BW.defaultRecord+1)*BW.recordStride)
    s.record23=r23==VANILLA_RECORD23 and'vanilla'or r23==DONOR and'copy'or'foreign'
    if s.record23=='foreign'then fail('CONFLICT: BeamWeapon record 23 is in a state HD2Runtime did not make')end
    s.record23_at=t.original+BW.recordBase+BW.defaultRecord*BW.recordStride
    local q=region(world,s.record23_at)
    if not(q and q.allocation_base==t.base and q.protect==READONLY and s.record23_at%4==0)then
        fail('the BeamWeapon file table is not in the entity allocation\'s read-only memory')
    end
    local tops={q.base+q.size}
    if t.mode=='owned'then
        if s.shared_rows or s.record23=='copy'then
            fail('REFUSED: the shared-record path left rows or record 23 in the file table while the owned copy is '
                ..'live (mixed paths): restart the game')
        end
        s.rows=t.copy:sub(1,BW.capacity*16)
        s.ctable=t.entry.table
        if t.entry.records~=L.records then fail('the conversion copy has another record count')end
        -- Rows: the file's, or a conversion row in a file-empty row naming its weapon's own record.
        for row=0,BW.capacity-1 do
            local now,was=s.rows:sub(row*16+1,row*16+16),file_rows:sub(row*16+1,row*16+16)
            if now~=was then
                local hit=was==ZERO16 and BY_RESOURCE[b.resource(now,0)]
                if not(hit and b.u32(now,8)==hit.weapon.record and b.u32(now,12)==0)then
                    fail(('CONFLICT: row %d of HD2Runtime\'s BeamWeapon copy differs from the file (not a conversion '
                        ..'row): restart the game'):format(row))
                end
            end
        end
        s.drift={}
        for r=0,BW.fileRecords-1 do
            local at=BW.recordBase+r*BW.recordStride
            if t.copy:sub(at+1,at+BW.recordStride)~=t.file:sub(at+1,at+BW.recordStride)then s.drift[#s.drift+1]=r end
        end
    else
        s.rows=file_rows
        s.drift={}
        s.path_mode=(s.shared_rows or s.record23=='copy')and'shared'or nil
    end
    s.ptable=component_table(world,s.manager,s.base,PJ.component)
    s.mtable=component_table(world,s.manager,s.base,MZ.component)
    s.rs=require("hd2runtime/runtime/beam_conversion_rows").locate(world)
    s.pair_user={}
    s.mrows=world.view.read(s.mtable,MZ.capacity*MZ.rowStride)
    if not s.mrows then fail('TARGET_UNAVAILABLE: the WeaponMagazine table is unreadable')end
    for _,w in ipairs(C.weapons)do
        if w.supported then
            local roots={}
            for _,root in ipairs(w.roots)do
                local R=locate_root(world,s,w,root)
                roots[#roots+1]=R
                s.by_resource[root.resource]=R
                for _,top in ipairs(R.tops)do tops[#tops+1]=top end
            end
            local W={w=w,roots=roots,state=weapon_state(roots)}
            if t.mode=='owned'then
                local at=BW.recordBase+w.record*BW.recordStride
                W.record_at=s.ctable+at
                W.record=t.copy:sub(at+1,at+BW.recordStride)
                -- Its own record: the Trident's but for its settings (+104..+115) and, with own rows, +0 = the
                -- borrowed BeamType of an owned pair (runtime/beam_conversion_rows.lua).
                local donor_but_settings=W.record:sub(5,SETTINGS_FROM)==DONOR:sub(5,SETTINGS_FROM)
                    and W.record:sub(SETTINGS_TO+1)==DONOR:sub(SETTINGS_TO+1)
                local beam_type=b.u32(W.record,0)
                if beam_type~=C.rows.tridentBeamType then
                    for i,P in ipairs(s.rs.pairs)do
                        if P.k==beam_type and P.state=='owned'and not s.pair_user[i]then W.pair=i end
                    end
                    if W.pair then s.pair_user[W.pair]=w.name else donor_but_settings=false end
                end
                if not donor_but_settings or(W.state~='converted'and W.record~=DONOR)then
                    W.state='foreign';W.record_foreign=true
                end
            end
            s.weapons[w.name]=W
        end
    end
    s.owner={base=t.base,size=math.max(unpack(tops))-t.base,type=PRIVATE,protect=READONLY}
    return s
end
M.locate=function(world)return locate(world)end

----------------------------------------------------------------------------------------------------- the gates --
-- Live entities per catalogued root resource, and of the Trident.
local function census(world,manager)
    if hooks.census then return hooks.census(world,manager)end
    local invalid=world.view.u32(world.game+MG.invalidEntity)
    local raw=world.view.read(manager+MG.descriptors,MG.descriptorStride*MG.descriptorCount)
    if not(invalid and raw)then return nil,'the entity descriptor table is unreadable'end
    local out={live=0,tridents=0,by={}}
    for k=0,MG.descriptorCount-1 do
        local at=k*MG.descriptorStride
        if b.u32(raw,at+MG.descriptorEntity)~=invalid and(b.u32(raw,at)~=0 or b.u32(raw,at+4)~=0)then
            out.live=out.live+1
            local kind=b.resource(raw,at)
            if BY_RESOURCE[kind]then out.by[kind]=(out.by[kind]or 0)+1
            elseif kind==C.trident.resource then out.tridents=out.tridents+1 end
        end
    end
    return out
end
M.census=function(world,manager)return census(world,manager)end
local function live_of(count,w)
    local n=0
    for _,root in ipairs(w.roots or{})do n=n+(count.by[root.resource]or 0)end
    return n
end

-- Lobby: 'solo', why | 'others', why | nil, why (unreadable).
local function lobby(world)
    if hooks.solo then
        local ok,why=hooks.solo(world)
        if ok==nil then return nil,why end
        return ok and'solo'or'others',why
    end
    local players=world_module.players(world)or{}
    if#players>1 then return'others',#players..' players in the game\'s player list'end
    local channel=require('hd2runtime/runtime/peer_channel')
    local ok,why=channel.prove(world)
    if not ok then return nil,'the lobby state cannot be proven ('..tostring(why)..')'end
    local found,code,reason=channel.lobby(world)
    if found then
        if#found.members>1 then return'others',#found.members..' lobby members'end
        return'solo','a lobby of 1 (this machine)'
    end
    if code=='NOT_JOINED'or code=='NO_SESSION'then return'solo','no lobby ('..tostring(reason)..')'end
    return nil,'the lobby state is unreadable ('..tostring(code)..': '..tostring(reason)..')'
end
M.lobby=function(world)return lobby(world)end

-- The Trident's package: 'resident' | ... , detail.
local function assets_state(world)
    if hooks.assets then return hooks.assets(world)end
    local assets=require('hd2runtime/core/assets')
    local dep=assets.dependency(C.trident.dependency)
    if not dep then return'unknown','no catalogued Trident package'end
    local ok,state=pcall(assets.state,world.runtime,dep.package)
    if not ok then return'unknown',clean(state)end
    return state,dep.name
end

-- ZERO live instances of every root of every weapon in `weapons` (names), solo for an apply, the package resident.
local function gates(world,s,weapons,apply)
    local count,why=census(world,s.manager)
    if not count then fail('TARGET_UNAVAILABLE: '..tostring(why))end
    local live={}
    for _,w in ipairs(weapons)do
        local n=live_of(count,w)
        if n>0 then live[#live+1]=('%d live %s'):format(n,w.name)end
    end
    if#live>0 then
        fail('TARGET_UNAVAILABLE: BUSY: '..table.concat(live,', ')..' (the ship preview, the armory, a loadout or a '
            ..'pickup): the conversion is written only while none exists; equip other weapons and do not open the '
            ..'armory until it applies')
    end
    if apply then
        local state,detail=lobby(world)
        if state~='solo'then
            fail('TARGET_UNAVAILABLE: NOT_SOLO: beam conversions apply only in a solo game ('..tostring(detail)
                ..'); another player\'s game would build the weapon without the beam')
        end
        local asset,asset_detail=assets_state(world)
        if asset~='resident'then
            fail('TARGET_UNAVAILABLE: the Trident\'s package is '..tostring(asset)..' ('..tostring(asset_detail)..')')
        end
    end
    return count
end

------------------------------------------------------------------------------------------------- the settings --
-- The settings of a record (+104..+115 decoded).
local function decode_settings(record)
    local out={}
    for _,def in ipairs(C.settings)do out[def.id]=b.value(record,def.offset,def.storage)end
    return out
end
M.decode_settings=decode_settings
M.DONOR_SETTINGS=decode_settings(DONOR)

-- The pulse the conversion writes for a rate (research/docs/beam-pulse-rate-F5FEE03DCFDB.md): an explicit pulse is
-- kept; without one, the Trident's 0.15 s when it fits the shot interval, else the longest pulse that never decides it
-- (max(60 / (2 rate), 60 / rate - 1/30) s), never below the setting's minimum (the one-frame no-damage floor at 30 fps).
local function ceil_eps(x)return math.ceil(x-1e-9)end
function M.pulse_updates(rate,pulse,fps)
    local dt=1/fps
    return math.max(ceil_eps(60/(rate*dt)),math.max(1,ceil_eps(pulse/dt))+1)
end
function M.effective_rate(rate,pulse,fps)return 60*fps/M.pulse_updates(rate,pulse,fps)end
function M.pulse_limit(rate)
    local interval=60/rate
    return math.max(interval/2,interval-1/30)
end
function M.fitted_pulse(rate,explicit)
    local def=SETTING.pulse_seconds
    if explicit~=nil then return explicit,false end
    local donor=M.DONOR_SETTINGS.pulse_seconds
    local limit=M.pulse_limit(rate)
    if donor<=limit+1e-6 then return donor,false end
    return math.max(limit,def.min),true
end
-- The record bytes a weapon's own record holds for its settings: the donor's but for +104..+115.
local function settings_record(values)
    local out={}
    for i,def in ipairs(C.settings)do
        local value=values[def.id]
        out[i]=value~=nil and b.encode(value,def.storage)or DONOR:sub(def.offset+1,def.offset+4)
    end
    return DONOR:sub(1,SETTINGS_FROM)..table.concat(out)..DONOR:sub(SETTINGS_TO+1)
end
M.settings_record=settings_record

--------------------------------------------------------------------------------------------------- the changes --
local function list_window_bytes(world,R,hexlist)
    local list=b.unhex(hexlist)
    local cur=world.view.read(R.window,R.window_size)
    if not cur then fail('TARGET_UNAVAILABLE: the '..R.w.name..'\'s membership list is unreadable')end
    local offset=R.window-R.list
    local inside=list:sub(offset+1,math.min(offset+R.window_size,#list))
    return inside..cur:sub(#inside+1)
end
-- {label, address, before, desired, owner}
local function list_changes(world,R,forward)
    local root=R.root
    local x,y=list_window_bytes(world,R,root.membership.before),list_window_bytes(world,R,root.membership.after)
    local out={}
    if R.split then
        local a,c=forward and x or y,forward and y or x
        out[1]={R.w.id..'.list+'..(R.window-R.list),R.window,a:sub(1,R.split),c:sub(1,R.split)}
        out[2]={R.w.id..'.list+'..(R.window+R.split-R.list),R.window+R.split,a:sub(R.split+1),c:sub(R.split+1)}
    else
        out[1]={R.w.id..'.list+'..(R.window-R.list),R.window,forward and x or y,forward and y or x}
    end
    if root.magazine then
        local mx,my=b.unhex(root.magazine.before),b.unhex(root.magazine.after)
        local mag={R.w.id..'.magazine'..root.magazine.record..'+'..MZ.window,R.chamber_at,forward and mx or my,
            forward and my or mx}
        if forward then out[#out+1]=mag else table.insert(out,1,mag)end
    end
    return out
end
local function row_write(prefix,at,row_bytes,owner)
    -- record index first, then the key: the key makes the row findable only once its record is right.
    return {{prefix..'.record',at+8,nil,row_bytes:sub(9,16),owner},{prefix..'.key',at,nil,row_bytes:sub(1,8),owner}}
end
local function row_clear(prefix,at,owner)
    return {{prefix..'.key',at,nil,ZERO8,owner},{prefix..'.record',at+8,nil,ZERO8,owner}}
end

-- The plan for the guarded transaction (core/guarded_transaction.lua). changes = {{label, address, before (nil:
-- read now), desired, owner (nil: the entity allocation)}}, contexts = {{owner, address, bytes}}.
local function make_plan(world,s,changes,contexts,roots)
    local plan={snapshots={{owner=s.owner,offset=s.table-s.base,bytes=s.table_bytes}},changes={}}
    for _,R in ipairs(roots)do
        plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.list_context_at-s.base,bytes=R.list_context}
        if R.mrecord then
            plan.snapshots[#plan.snapshots+1]={owner=s.owner,offset=R.mrecord_at-s.base,bytes=R.mrecord}
        end
    end
    for _,x in ipairs(contexts or{})do
        plan.snapshots[#plan.snapshots+1]={owner=x[1],offset=x[2]-x[1].base,bytes=x[3]}
    end
    -- Overlapping contexts of one owner (adjacent lists of two roots) become one: a target must lie in exactly one.
    table.sort(plan.snapshots,function(a,c)
        if a.owner.base~=c.owner.base then return a.owner.base<c.owner.base end
        return a.offset<c.offset
    end)
    local merged={}
    for _,x in ipairs(plan.snapshots)do
        local last=merged[#merged]
        if last and last.owner.base==x.owner.base and x.offset<=last.offset+#last.bytes then
            local overlap=last.offset+#last.bytes-x.offset
            if overlap>#x.bytes then overlap=#x.bytes end
            if last.bytes:sub(#last.bytes-(last.offset+#last.bytes-x.offset)+1,
                #last.bytes-(last.offset+#last.bytes-x.offset)+overlap)~=x.bytes:sub(1,overlap)then
                fail('TARGET_UNAVAILABLE: unstable ownership/data snapshot (overlapping contexts differ)')
            end
            if x.offset+#x.bytes>last.offset+#last.bytes then
                last.bytes=last.bytes..x.bytes:sub(overlap+1)
            end
            if x.owner.size>last.owner.size then last.owner=x.owner end
        else
            merged[#merged+1]={owner=x.owner,offset=x.offset,bytes=x.bytes}
        end
    end
    plan.snapshots=merged
    for _,c in ipairs(changes)do
        local owner=c[5]or s.owner
        local before=c[3]or world.view.read(c[2],#c[4])
        if not before then fail('TARGET_UNAVAILABLE: a conversion target is unreadable')end
        plan.changes[#plan.changes+1]={label='beam_conversion.'..c[1],owner=owner,offset=c[2]-owner.base,
            expected=c[3]and c[3]or before,desired=c[4],before=before,already_desired=before==c[4],
            packed=c[2]%4~=0 or nil,identity={component='BeamWeaponComponentData',component_type='native',
            record_type='beam_conversion',unique_owner=true,owner_count=1},chain={}}
    end
    return plan
end

-- reviewed_edits (core/reviewed_edits.lua): a converted root's exact state, or nothing.
local function refuse_projectile(w)
    return('BEAM CONVERSION: the %s fires Trident pulses (its ProjectileWeapon component is dormant while converted); '
        ..'writes to its fire rate, projectile, ammunition and the rows they link to are refused until the conversion '
        ..'is restored (owner: HD2Runtime beam conversion)'):format(w.name)
end
local function refuse_record(w)
    return('BEAM CONVERSION: the %s\'s own beam record belongs to its beam conversion: set its rate and pulse on '
        ..'hd2.weapon(name):beam_conversion() (owner: HD2Runtime beam conversion)'):format(w.name)
end
local function record_edits(s)
    for _,W in pairs(s.weapons)do
        for _,R in ipairs(W.roots)do
            local root=R.root
            if R.state=='converted'then
                local rows={[BW.component]={row=R.row,record=s.path_mode=='owned'and W.w.record or BW.defaultRecord},
                    [PJ.component]={row=root.projectile.row,record=root.projectile.record}}
                if root.magazine then rows[MZ.component]={row=root.magazine.row,record=root.magazine.record}end
                edits.set(root.resource,{owner=M.OWNER,stage='converted',membership=b.unhex(root.membership.after),
                    rows=rows,absent={[PJ.component]=true},
                    refuse={[PJ.component]=refuse_projectile(W.w),[BW.component]=refuse_record(W.w)}})
            else
                local e=edits.get(root.resource)
                if e and e.owner==M.OWNER then edits.clear(root.resource)end
            end
        end
    end
end
M.record_edits=record_edits

------------------------------------------------------------------------------------------------- the operation --
-- request = {weapon = catalogue entry, enabled = bool, settings = {fire_rate, pulse_beams, pulse_seconds} (values
-- the record must hold; nil members: the donor's), rows = {[field id] = value} (the weapon's own beam / damage row
-- values; nil or all the Trident's: no own rows needed)}. Returns {plan (with notes), commit, state, path} or raises.
-- A converted weapon with other settings: only its record and its own rows (no gate). Enable: gates, then [the row
-- block values, the borrowed slots], the copy / rows / lists / magazine bytes. Disable: gates (census; a live shot of
-- its borrowed BeamType), then magazine bytes, lists, index rows (algorithm R), its record back to the donor, the
-- borrowed slots back; the last disable puts the slot back.
function M.prepare(world,s,request)
    local w=assert(request.weapon,'beam conversion weapon')
    if not w.supported then fail('REFUSED: '..w.reasonCode..': '..w.reason)end
    local W=assert(s.weapons[w.name],'located weapon')
    local R=require('hd2runtime/runtime/beam_conversion_rows')
    local notes={}
    if W.state=='foreign'then
        local d={}
        for _,root in ipairs(W.roots)do d[#d+1]=root.detail end
        fail('CONFLICT: the '..w.name..' is in a state the beam conversion did not make ('..table.concat(d,'; ')
            ..(W.record_foreign and'; its own record'or'')..')')
    end
    local rows_values=request.rows or{}
    local rows_needed=R.needed(rows_values)
    local t=s.tb
    local changes,contexts,roots={},{},{}
    local commit={}
    local function anchor()
        -- Nothing to write: the lists as they are (the ensure's steady-state check keeps watching them).
        for _,X in ipairs(W.roots)do
            local cur=world.view.read(X.window,X.window_size)
            local n=X.split or X.window_size
            changes[#changes+1]={X.w.id..'.list+'..(X.window-X.list),X.window,cur:sub(1,n),cur:sub(1,n)}
            roots[#roots+1]=X
        end
    end
    local function record_changes(current,want)
        for at=0,BW.recordStride-4,4 do
            local x,y=current:sub(at+1,at+4),want:sub(at+1,at+4)
            if x~=y then changes[#changes+1]={('%s.record%d+%d'):format(w.id,w.record,at),W.record_at+at,x,y,
                t.copy_owner}end
        end
    end
    -- Own rows: the pair this weapon holds, or a free one borrowed now (owned table path only). Returns the pair.
    local function own_rows(path)
        if not rows_needed and not W.pair then return nil end
        if path~='owned'then
            fail('REFUSED: SHARED_RECORD_FALLBACK: per-weapon damage, AP and range need the owned table (the conversion '
                ..'runs on the shared record 23)')
        end
        if s.rs.unavailable then fail('REFUSED: '..s.rs.unavailable)end
        local i=W.pair
        if not i then
            for n,P in ipairs(s.rs.pairs)do
                if not i and not s.pair_user[n]and(P.state=='free'or P.state=='owned')then i=n end
            end
            if not i then
                local why={}
                for n,P in ipairs(s.rs.pairs)do
                    why[#why+1]=('pair %d: %s'):format(n,s.pair_user[n]and('the '..s.pair_user[n])or P.state
                        ..(P.reason and(' ('..P.reason..')')or''))
                end
                fail('REFUSED: ROWS_FULL: every borrowed beam / damage row pair is in use or unavailable ('
                    ..table.concat(why,'; ')..'): at most '..R.PAIRS..' converted weapons have their own damage, AP '
                    ..'and range at once')
            end
            local busy,why=R.ring_busy(world,s.rs.pairs[i].k,s.rs.pairs[i].d)
            if busy then fail('TARGET_UNAVAILABLE: BUSY: '..tostring(why))end
            R.build(world,s.rs)
            notes[#notes+1]=('own rows: BeamType %d and DamageInfo %d (borrowed spare slots, interim, this build '
                ..'only) now hold the %s\'s beam and damage'):format(s.rs.pairs[i].k,s.rs.pairs[i].d,w.name)
        end
        for _,c in ipairs(R.value_changes(s.rs,i,rows_values))do changes[#changes+1]=c end
        if s.rs.pairs[i].state=='free'then
            local cs,ctx=R.assign_changes(s.rs,i)
            for _,c in ipairs(cs)do changes[#changes+1]=c end
            for _,x in ipairs(ctx)do contexts[#contexts+1]=x end
        end
        contexts[#contexts+1]={s.rs.block_owner,s.rs.block.allocation,s.rs.block_bytes}
        return i
    end
    local function want_record(pair)
        local rec=settings_record(request.settings or{})
        if pair then rec=b.encode(s.rs.pairs[pair].k,'u32')..rec:sub(5)end
        return rec
    end
    if request.enabled then
        if W.state=='orphaned'then
            fail('REFUSED: the '..w.name..'\'s list is still converted but no table row names it (an owned copy that '
                ..'died): disable the conversion first to restore it')
        end
        if W.state=='converted'then
            if s.path_mode=='shared'then
                if settings_record(request.settings or{})~=DONOR or rows_needed then
                    fail('REFUSED: SHARED_RECORD_FALLBACK: the conversion runs on the shared record 23 (the owned '
                        ..'table was unavailable when it was applied): every converted weapon fires the Trident\'s '
                        ..'own rate, pulse and damage; disable every conversion and enable it again for per-weapon '
                        ..'settings')
                end
                anchor()
            else
                local pair=own_rows('owned')
                record_changes(W.record,want_record(pair))
                if#changes==0 then anchor()else contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}end
                commit.pair=pair
            end
            return {plan=make_plan(world,s,changes,contexts,roots),state='converted',path=s.path_mode,notes=notes,
                commit=commit}
        end
        -- vanilla -> converted
        gates(world,s,{w},true)
        local path=s.path_mode
        if not path then
            local ok,why=owned_available(world,t)
            if ok then path='owned'
            else
                path='shared'
                notes[#notes+1]='the owned table is unavailable ('..tostring(why)..'): the shared record 23 is used '
                    ..'(one Trident rate and pulse for every converted weapon)'
            end
        end
        if path=='shared'and settings_record(request.settings or{})~=DONOR then
            fail('REFUSED: SHARED_RECORD_FALLBACK: the owned table is unavailable, so the conversion would share the '
                ..'Trident\'s record 23 with every converted weapon: per-weapon rate and pulse need the owned table')
        end
        local pair=own_rows(path)
        -- Index rows: one per root, each the first empty row on its probe path in the table the game reads (with the
        -- rows already placed in this operation), always leaving one row empty.
        local rows=s.rows
        local placed={}
        local record_index=path=='owned'and w.record or BW.defaultRecord
        for _,X in ipairs(W.roots)do
            local at=insert_row(rows,X.root.resource)
            if not at or free_rows(rows)<=L.minFreeRows then
                fail('REFUSED: TABLE_FULL: the BeamWeapon table has no free row for the '..w.name
                    ..' (every row but the last free one is used): disable another conversion first')
            end
            local bytes=key_bytes(X.root.resource)..b.encode(record_index,'u32')..b.encode(0,'u32')
            rows=rows:sub(1,at*16)..bytes..rows:sub(at*16+17)
            placed[#placed+1]={X=X,row=at,bytes=bytes}
        end
        if path=='owned'and t.mode=='in_place'then
            -- Build the copy with these rows and this record, then ONE transaction: [own rows], the slot, the lists.
            local new_rows={}
            for _,p in ipairs(placed)do new_rows[p.row]=p.bytes end
            local entry=build(world,t,new_rows,{[w.record]=want_record(pair)})
            local copy=world.view.read(entry.allocation,entry.size)
            local copy_owner={base=entry.allocation,size=entry.size,type=PRIVATE,protect=READONLY}
            changes[#changes+1]={'slot270',t.slot_at,u64(t.original),u64(entry.table),t.manager_owner}
            contexts[#contexts+1]={t.manager_owner,t.slot_at,u64(t.original)}
            contexts[#contexts+1]={copy_owner,entry.allocation,copy}
            commit.register=entry
        elseif path=='owned'then
            record_changes(W.record,want_record(pair))
            for _,p in ipairs(placed)do
                for _,c in ipairs(row_write(w.id..'.row'..p.row,s.ctable+p.row*16,p.bytes,t.copy_owner))do
                    c[3]=ZERO8;changes[#changes+1]=c
                end
            end
            contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}
        else
            if s.record23=='vanilla'then
                for i=0,BW.recordStride-4,4 do
                    local p,q=VANILLA_RECORD23:sub(i+1,i+4),DONOR:sub(i+1,i+4)
                    if p~=q then changes[#changes+1]={('record23+%d'):format(i),s.record23_at+i,p,q}end
                end
            end
            for _,p in ipairs(placed)do
                for _,c in ipairs(row_write(w.id..'.row'..p.row,s.table+p.row*16,p.bytes))do
                    c[3]=ZERO8;changes[#changes+1]=c
                end
            end
        end
        for _,X in ipairs(W.roots)do
            for _,c in ipairs(list_changes(world,X,true))do changes[#changes+1]=c end
            roots[#roots+1]=X
        end
        commit.converted=w;commit.path=path;commit.pair=pair
        return {plan=make_plan(world,s,changes,contexts,roots),state='vanilla',path=path,notes=notes,commit=commit}
    end
    -- disable
    if W.state=='vanilla'then
        anchor()
        return {plan=make_plan(world,s,changes,contexts,roots),state='vanilla',path=s.path_mode,notes=notes,
            commit=commit}
    end
    -- Gates: the census of this weapon's roots (no solo gate: a restore makes this machine agree with the others), and
    -- no live shot of its borrowed BeamType (one pulse).
    gates(world,s,{w},false)
    if W.pair then
        local busy,why=R.ring_busy(world,s.rs.pairs[W.pair].k,s.rs.pairs[W.pair].d)
        if busy then fail('TARGET_UNAVAILABLE: BUSY: '..tostring(why))end
    end
    for _,X in ipairs(W.roots)do
        for _,c in ipairs(list_changes(world,X,false))do changes[#changes+1]=c end
        roots[#roots+1]=X
    end
    -- Index rows: remove each root's row (algorithm R) from the table the game reads.
    local rows=s.rows
    local owned_path=s.path_mode=='owned'
    local base_at=owned_path and s.ctable or s.table
    local row_owner=owned_path and t.copy_owner or nil
    for _,X in ipairs(W.roots)do
        if X.row then
            local plan=delete_plan(rows,X.row,function(resource)
                local hit=BY_RESOURCE[resource]
                return hit~=nil and hit.weapon~=w
            end)
            local after=apply_delete(rows,plan)
            for _,m in ipairs(plan.moves)do
                local bytes=rows:sub(m.from*16+1,m.from*16+16)
                for _,c in ipairs(row_write(w.id..'.move'..m.from..'to'..m.to,base_at+m.to*16,bytes,row_owner))do
                    changes[#changes+1]=c
                end
                notes[#notes+1]=('row %d (%s) moved to row %d (linear-probing deletion)'):format(m.from,m.resource,
                    m.to)
            end
            for _,c in ipairs(row_clear(w.id..'.clear'..plan.clear,base_at+plan.clear*16,row_owner))do
                changes[#changes+1]=c
            end
            rows=after
        end
    end
    -- The weapon's own record back to the donor (owned), then its borrowed slots back.
    if owned_path then record_changes(W.record,DONOR)end
    if W.pair then
        local cs,ctx=R.release_changes(s.rs,W.pair)
        for _,c in ipairs(cs)do changes[#changes+1]=c end
        for _,x in ipairs(ctx)do contexts[#contexts+1]=x end
        notes[#notes+1]=('own rows released: BeamType %d and DamageInfo %d point at their vanilla rows again')
            :format(s.rs.pairs[W.pair].k,s.rs.pairs[W.pair].d)
    end
    -- The last conversion: the slot back (owned, no drift), or record 23 back (shared).
    local remaining=0
    for name,X in pairs(s.weapons)do
        if name~=w.name and(X.state=='converted'or X.state=='orphaned')then remaining=remaining+1 end
    end
    if remaining==0 then
        if owned_path then
            if#s.drift==0 then
                changes[#changes+1]={'slot270',t.slot_at,u64(t.entry.table),u64(t.original),t.manager_owner}
                contexts[#contexts+1]={t.manager_owner,t.slot_at,u64(t.entry.table)}
                commit.forget=true
            else
                notes[#notes+1]=('the owned copy stays live: record%s %s changed in it while it was live (a typed '
                    ..'write such as a mod\'s beam.fire_rate); the game would lose that write if it read the file\'s '
                    ..'table again'):format(#s.drift==1 and''or's',table.concat(s.drift,', '))
            end
        elseif s.record23=='copy'then
            for i=0,BW.recordStride-4,4 do
                local p,q=DONOR:sub(i+1,i+4),VANILLA_RECORD23:sub(i+1,i+4)
                if p~=q then changes[#changes+1]={('record23+%d'):format(i),s.record23_at+i,p,q}end
            end
        end
    end
    if owned_path then contexts[#contexts+1]={t.copy_owner,s.ctable,t.copy}end
    if W.pair then contexts[#contexts+1]={s.rs.block_owner,s.rs.block.allocation,s.rs.block_bytes}end
    commit.restored=w
    return {plan=make_plan(world,s,changes,contexts,roots),state=W.state,path=s.path_mode,notes=notes,commit=commit}
end

-- After the transaction: register the copy, record the reviewed edits, the restart notice and the lobby watch.
function M.commit(world,prepared,report)
    if not(report and(report.status=='APPLIED'or report.status=='ALREADY_DESIRED'))then return end
    local commit=prepared.commit or{}
    if commit.register then owned.set(BW.component,commit.register)end
    if commit.forget then owned.clear(BW.component)end
    if commit.converted then
        session().used=true
        log(('%s CONVERTED [%s]: spawned from now on it fires LAS-13 Trident pulses; solo only; RESTART THE GAME after '
            ..'using a conversion'):format(commit.converted.name,M.PATHS[commit.path]or tostring(commit.path)))
    end
    if commit.restored then log(commit.restored.name..' RESTORED: every byte of its conversion is vanilla again')end
    local ok,s=pcall(locate,world)
    if ok then
        record_edits(s)
        require('hd2runtime/runtime/beam_conversion_watch').sync(s)
    else
        log('after the write the state could not be re-read: '..clean(s))
    end
end

------------------------------------------------------------------------------------------------------ the status --
-- Read-only: {ok, path, table, copies, restart_required, solo, weapons = {[name] = {state, settings, live, roots}}}.
function M.status()
    local ok,result=pcall(function()
        local world=open()
        local s=locate(world)
        local count=census(world,s.manager)
        local lob,why=lobby(world)
        local out={ok=true,path=s.path_mode and M.PATHS[s.path_mode]or'none',table=s.tb.mode,copies=session().copies,
            restart_required=session().used,lobby=lob or'unknown',lobby_reason=why,
            drift=#s.drift>0 and s.drift or nil,weapons={}}
        for name,W in pairs(s.weapons)do
            local entry={state=W.state,live=count and live_of(count,W.w)or nil,roots={}}
            if W.state=='converted'then
                entry.settings=s.path_mode=='owned'and decode_settings(W.record)or decode_settings(DONOR)
                entry.rows=M.rows_of(s,W)
                if W.pair then entry.pair={beamType=s.rs.pairs[W.pair].k,damageInfo=s.rs.pairs[W.pair].d}end
            end
            for _,R in ipairs(W.roots)do entry.roots[#entry.roots+1]={resource=R.root.resource,state=R.state,
                detail=R.detail}end
            out.weapons[name]=entry
        end
        record_edits(s)
        return out
    end)
    if ok then return result end
    return {ok=false,reason=clean(result)}
end
-- Quiet: the converted weapon names now (nil, why when unreadable).
function M.converted()
    local ok,result=pcall(function()
        local s=locate(open())
        local out={}
        for name,W in pairs(s.weapons)do if W.state=='converted'or W.state=='orphaned'then out[#out+1]=name end end
        table.sort(out)
        return out,s
    end)
    if ok then return result end
    return nil,clean(result)
end
function M.restart_required()return session().used end

-- A located weapon's own beam / damage row values (its borrowed pair's, else the Trident's).
function M.rows_of(s,W)
    local R=require('hd2runtime/runtime/beam_conversion_rows')
    if W.pair then local P=s.rs.pairs[W.pair];return R.values_of(P.beam,P.damage)end
    return R.defaults()
end

-- Tests only.
function M.set_hooks_for_tests(h)hooks=h or{}end
function M.reset_for_tests()
    proven={};hooks={};rawset(_G,STATE_KEY,nil)
    require('hd2runtime/runtime/beam_conversion_rows').reset_for_tests()
    for _,w in ipairs(C.weapons)do for _,root in ipairs(w.roots or{})do
        local e=edits.get(root.resource)
        if e and e.owner==M.OWNER then edits.clear(root.resource)end
    end end
    local e=owned.get(BW.component)
    if e and e.owner==M.OWNER then owned.clear(BW.component)end
end
return M
