"""Build the installed-once runtime, authoring-only SDK, and independent examples."""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile

import build
import generate_sdk
import generate_weapon_authoring
import generate_support_weapon_sdk
import generate_support_weapon_authoring
import generate_stratagem_authoring
import generate_entity_authoring
import generate_attachment_authoring
import generate_booster_authoring
import generate_weapon_composition
import generate_fire_mode_authoring
import generate_vehicle_weapon_authoring
import generate_pod_payload_authoring
import generate_throwable_authoring
import generate_package_residency
import apply_projectile_residency
import generate_status_catalog
import generate_weapon_movement
import generate_enemy_authoring
import generate_live_evidence
import generate_attack_outputs
from build_live_validation import revision,verify_installed
from hd2_archive import ARCHIVE_NAME,make_archive,resource_hash,lua_resource
import validate_packaged_runtime
import validate_examples
import parallel

ROOT=build.ROOT
sys.path.insert(0,str(ROOT/'sdk'))
import hd2

PACKAGE_MODULES='hd2runtime/runtime/package_modules'


def runtime_resources():
    resources={k:v for k,v in build.resources(writable=True).items()
               if not k.startswith('hd2runtime/examples/') and k!='mods/skyeshade/hd2runtime_report'}
    resources[hd2.MODULE]=(ROOT/'packaging/library.lua').read_bytes()
    # Every internal module, so the library entry can capture all loaders at startup.
    internal=sorted(name for name in resources if name.startswith('hd2runtime/'))
    resources[PACKAGE_MODULES]=('-- Generated by scripts/build_release.py at packaging time.\nreturn {\n'
        +''.join('    '+json.dumps(name)+',\n' for name in internal)+'}\n').encode()
    return resources


def build_runtime(version,report_bytes=b'{}\n',folder=None):
    """Write the installed-once runtime ZIP exactly as released and return its path."""
    spec=json.loads((ROOT/'hd2runtime.json').read_text());sources=runtime_resources()
    archive=make_archive({resource_hash(k):lua_resource(v) for k,v in sources.items()})
    description='Shared HD2Runtime API 1. Requires Bingus Shared Loader v15+ / API 1. Install once; no gameplay changes until a dependent mod requests them.'
    manifest={'Version':1,'Guid':spec['guid'],'Name':'HD2Runtime '+version,'Description':description,
              'Options':[{'Name':'Shared runtime','Description':description,'Include':['runtime']}]}
    runtime_zip=Path(folder or ROOT/'build')/('HD2Runtime-'+version+'-runtime.zip')
    hd2.zip_files(runtime_zip,{'manifest.json':json.dumps(manifest,indent=2).encode(),
        'hd2runtime.json':json.dumps(spec,indent=2).encode(),'runtime/'+ARCHIVE_NAME:archive,
        'runtime/'+ARCHIVE_NAME+'.stream':b'','runtime/'+ARCHIVE_NAME+'.gpu_resources':b'',
        'README.md':(ROOT/'sdk/README.md').read_bytes(),'build-report.json':report_bytes,
        'provenance.json':(ROOT/'docs/provenance.json').read_bytes()})
    return runtime_zip


def starter_files():
    return {path.relative_to(ROOT/'starter').as_posix():path.read_bytes()
            for path in sorted((ROOT/'starter').rglob('*')) if path.is_file()
            and 'build' not in path.relative_to(ROOT/'starter').parts}


def build_starter(version,folder=None):
    path=Path(folder or ROOT/'build')/('HD2Runtime-ModTemplate-'+version+'.zip')
    hd2.zip_files(path,starter_files())
    return path


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--luals',type=Path,help='Optional LuaLS executable for real type/completion checks')
    parser.add_argument('--output',type=Path,default=ROOT/'build',
        help='folder for the release ZIPs and report (default build/; use a scratch folder for test builds)')
    parallel.add_argument(parser)
    args=parser.parse_args()
    parallel.configure(args.jobs)
    out=args.output;out.mkdir(parents=True,exist_ok=True)
    apply_projectile_residency.generate(check=True)
    generate_status_catalog.generate(check=True)
    generate_weapon_composition.generate(check=True)
    generate_support_weapon_sdk.generate(check=True)
    generate_support_weapon_authoring.generate(check=True)
    generate_entity_authoring.generate(check=True)
    generate_attachment_authoring.generate(check=True)
    generate_booster_authoring.generate(check=True)
    generate_stratagem_authoring.generate(check=True)
    generate_weapon_authoring.generate(check=True)
    generate_fire_mode_authoring.generate(check=True)
    generate_vehicle_weapon_authoring.generate(check=True)
    generate_pod_payload_authoring.generate(check=True)
    generate_throwable_authoring.generate(check=True)
    generate_package_residency.generate(check=True)
    generate_weapon_movement.generate(check=True)
    generate_enemy_authoring.generate(check=True)
    generate_live_evidence.generate(check=True)
    generate_attack_outputs.generate(check=True)
    generate_sdk.generate(check=True)
    schema=hd2.database();version=(ROOT/'VERSION').read_text().strip()
    assert version==schema['runtime_version'],'Version/schema mismatch'
    commit=revision();installed=verify_installed()
    # The unit tests, the example validation and the shipped-artifact validation are independent (none writes
    # what another reads), so they run concurrently; their verdicts are still raised in this order.
    with ThreadPoolExecutor(max_workers=3) as pool,tempfile.TemporaryDirectory(dir=ROOT/'build') as folder:
        tests=pool.submit(subprocess.run,[sys.executable,'-B','scripts/run_tests.py','-v','--jobs',
            str(parallel.resolve(args.jobs))],cwd=ROOT,capture_output=True,text=True)
        examples=pool.submit(validate_examples.validate)
        # Run the shipped artifact itself, with late resource lookup disabled as in game.
        artifact=pool.submit(lambda:validate_packaged_runtime.validate(build_runtime(version,folder=folder),
            jobs=args.jobs))
        run=tests.result()
        print(run.stderr,end='')
        if run.returncode:raise RuntimeError('Release tests failed: '+run.stdout)
        examples_report=examples.result();artifact_report=artifact.result()
    assert revision()==commit,'Source changed during build'
    report={'version':version,'commit':commit,'tests':run.stderr,'installed_files':installed,
            'deployed':False,'game_launched':False,'live_process_access':False,
            'prior_gameplay_confirmation':'User confirmed 0.4.0 live gameplay proof',
            'new_live_gameplay_test':False,'fixture_fallback':'disabled'}
    support_capabilities=json.loads((ROOT/'sdk/SupportWeaponAuthoringCapabilities.json').read_text())
    support_validation=json.loads((ROOT/'research/support-weapon-authoring-validation-F5FEE03DCFDB.json').read_text())
    report['support_weapon_authoring']=support_capabilities['summary']
    report['support_weapon_capability_contract']={
        'schemaVersion':support_capabilities['schemaVersion'],
        'contract':support_capabilities['contract'],
        'instanceAudit':support_capabilities['instanceAudit'],
        'backingObjects':len(support_capabilities['backingObjects']),
        'operationGroups':len(support_capabilities['operationGroups'])}
    report['support_weapon_snapshot_validation']=support_validation
    report['support_weapon_proof_packages']=[
        'SupportAMRProof','RecoillessProof','ArcThrowerProof','C4Proof']
    stratagem_capabilities=json.loads((ROOT/'sdk/StratagemAuthoringCapabilities.json').read_text())
    report['stratagem_authoring']=stratagem_capabilities['summary']
    report['stratagem_snapshot_validation']=json.loads(
        (ROOT/'validation/stratagem-authoring-snapshot.json').read_text())
    call_in_links=support_capabilities['supportCallInLinks']
    assert call_in_links==stratagem_capabilities['supportCallInLinks'],'Support call-in linkage diverged'
    assert call_in_links['audit']['bidirectionalMismatches']==0,'Support call-in linkage is one-way'
    report['support_call_in_linkage']=call_in_links['audit']
    vehicle_capabilities=json.loads((ROOT/'sdk/VehicleAuthoringCapabilities.json').read_text())
    backpack_capabilities=json.loads((ROOT/'sdk/BackpackAuthoringCapabilities.json').read_text())
    report['vehicle_authoring']=vehicle_capabilities['summary']
    report['backpack_authoring']=backpack_capabilities['summary']
    report['magazine_attachment_authoring']=json.loads(
        (ROOT/'sdk/MagazineAttachmentCapabilities.json').read_text())['summary']
    report['magazine_attachment_snapshot_validation']=json.loads(
        (ROOT/'validation/magazine-attachment-snapshot.json').read_text())
    report['booster_authoring']=json.loads(
        (ROOT/'sdk/BoosterAuthoringCapabilities.json').read_text())['summary']
    report['reticle_authoring_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/reticle-authoring-snapshot.json').read_text()).items() if key!='weapons'}
    report['fire_mode_authoring_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/fire-mode-authoring-snapshot.json').read_text()).items() if key!='weapons'}
    report['weapon_fire_modes']=json.loads((ROOT/'sdk/WeaponFireModeCapabilities.json').read_text())['summary']
    ammo_research=json.loads((ROOT/'research/backpack-ammo-F5FEE03DCFDB.json').read_text())
    report['backpack_ammo']={'backpackFedWeapons':{item['supportWeapon']:{'capacity':item['deposit']['values']['0'],
        'startAmount':item['deposit']['values']['4'],'refillAmount':item['deposit']['values']['8'],
        'fingerprintExact':item['fingerprintExact'],'weaponOwnsMagazine':item['weaponOwnsMagazine']}
        for item in ammo_research['backpackFedWeapons']},'liveEquality':ammo_research['liveEquality']}
    report['backpack_ammo_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/backpack-ammo-snapshot.json').read_text()).items() if key!='backpacks'}
    report['pod_payloads']=json.loads((ROOT/'sdk/PodPayloadCapabilities.json').read_text())['summary']
    report['pod_payload_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/pod-payload-snapshot.json').read_text()).items() if key!='scenarios'}
    report['vehicle_weapons']=json.loads((ROOT/'sdk/VehicleWeaponCapabilities.json').read_text())['summary']
    report['vehicle_weapon_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/vehicle-weapon-authoring-snapshot.json').read_text()).items() if key!='scenarios'}
    report['reference_mod_inventory']={name:{key:item[key] for key in ('sha256','recreation','recreationStatus')}
        for name,item in json.loads((ROOT/'research/reference-mod-inventory-F5FEE03DCFDB.json').read_text())
        ['referenceMods'].items()}
    report['weapon_attachment_catalog']=json.loads(
        (ROOT/'sdk/WeaponAttachmentCatalog.json').read_text())['summary']
    report['magazine_attachment_authoring']=json.loads(
        (ROOT/'sdk/MagazineAttachmentCapabilities.json').read_text())['summary']
    report['options_binding_validation']=json.loads(
        (ROOT/'validation/options-binding-snapshot.json').read_text())
    report['booster_snapshot_validation']=json.loads(
        (ROOT/'validation/booster-authoring-snapshot.json').read_text())
    report['throwable_authoring']=json.loads(
        (ROOT/'sdk/ThrowableAuthoringCapabilities.json').read_text())['summary']
    report['throwable_snapshot_validation']=json.loads(
        (ROOT/'validation/throwable-authoring-snapshot.json').read_text())
    report['weapon_movement']=json.loads((ROOT/'sdk/WeaponMovementCapabilities.json').read_text())['summary']
    report['asset_dependencies']=json.loads(
        (ROOT/'sdk/AssetDependencyCapabilities.json').read_text())['summary']
    report['asset_residency_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/asset-residency-snapshot.json').read_text()).items() if key!='snapshots'}
    report['entity_snapshot_validation']=json.loads(
        (ROOT/'validation/entity-authoring-snapshot.json').read_text())
    recreations=json.loads((ROOT/'validation/reference-mod-recreations.json').read_text())
    assert recreations['status']=='EXACT_MATCH','Reference mod recreation is not exact'
    report['reference_mod_recreations']={name:{key:item[key] for key in
        ('status','physicalWrites','referenceWrites','referenceSources','omittedReferenceWrites')}
        for name,item in recreations['recreations'].items()}
    report['stratagem_proof_packages']=['OrbitalLaserProof','OrbitalPrecisionProof',
        'OrbitalBarrageProof','EagleProof','SupportStratagemCooldownProof',
        'AntiTankEmplacementProof','ConventionalSentryProof','ExplosiveSentryProof',
        'UnusualSentryProof','ShieldRelayRecreation','BastionReArmoredRecreation',
        'FRVWeaponSwapRecreation','JumpPackRecreation','ConcussiveDrumMagazine',
        'ArmedResupplyTurret','CombatStimBoost','BoosterTuning','IncendiaryHellpods',
        'LiberatorDamageOptions','ReticleAmrRecreation','JAR5FullAuto','ExosuitUnlimitedUses',
        'EmancipatorAmmo','LumbererAmmo','M103TurretMagazine','PatriotExosuitBuffs','MaxigunBackpackAmmo','SurplusEatPodSwap']
    # Every shipped example (projects, live examples, the ModTemplate) must pass current Runtime validation,
    # including snapshot baselines, acknowledgements and minimum versions; a rotten example fails the release.
    if examples_report['status']!='VALIDATED':
        raise RuntimeError('Example validation failed: '+', '.join(examples_report['failed']))
    report['example_validation']={'status':examples_report['status'],'examples':examples_report['examples'],
        'failed':examples_report['failed'],'baselineChanges':sum(item['baselineChanges'] or 0
            for item in examples_report['results'].values())}
    if args.luals:
        from check_sdk_luals import check
        report['luals']={'sdk':check(args.luals),'starter':check(args.luals,ROOT/'starter')}
    report['runtime_artifact_validation']=artifact_report
    report_bytes=(json.dumps(report,indent=2)+'\n').encode()
    runtime_zip=build_runtime(version,report_bytes,folder=out)
    sdk_zip=out/('HD2Runtime-'+version+'-sdk.zip')
    sdk_files={p.relative_to(ROOT/'sdk').as_posix():p.read_bytes() for p in (ROOT/'sdk').rglob('*')
               if p.is_file() and '__pycache__' not in p.parts and p.suffix!='.pyc'}
    from tools.snapshot_scan import bundle_bytes
    sdk_files['tools/snapshot_scan_modules.json']=bundle_bytes()
    sdk_files['build-report.json']=report_bytes
    hd2.zip_files(sdk_zip,sdk_files)
    example_files={}
    starter_zip=build_starter(version,folder=out)
    artifacts=[runtime_zip,sdk_zip,starter_zip]
    for project in sorted((ROOT/'examples/projects').iterdir()):
        if not project.is_dir():continue
        artifacts.append(hd2.build_project(project))
        for path in project.rglob('*'):
            if path.is_file() and not {'build','__pycache__','.idea'}.intersection(path.relative_to(project).parts):
                example_files[path.relative_to(ROOT/'examples/projects').as_posix()]=path.read_bytes()
    example_files['README.md']=b'Example source projects. Run python <SDK>/hd2.py configure <project> --sdk <SDK> after extraction, then python build.py. Install runtime once and each desired gameplay mod separately.\n'
    examples_zip=out/('HD2Runtime-'+version+'-example-projects.zip')
    hd2.zip_files(examples_zip,example_files);artifacts.append(examples_zip)
    report['artifacts']=[{'file':str(p.resolve().relative_to(ROOT) if p.resolve().is_relative_to(ROOT) else p),
        'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in artifacts]
    (out/'sdk-release-report.json').write_text(json.dumps(report,indent=2)+'\n')
    for p in artifacts:print(p)
    print('commit='+commit)


if __name__=='__main__':main()
