"""Build the installed-once runtime, authoring-only SDK, and independent examples."""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile

import build
import generate_sdk
import generate_weapon_authoring
import generate_support_weapon_sdk
import generate_support_weapon_authoring
import generate_stratagem_authoring
import generate_entity_authoring
import generate_attachment_authoring
import generate_booster_authoring
import generate_weapon_composition
import generate_fire_mode_authoring
import generate_weapon_modes
import generate_weapon_presentation
import generate_vehicle_weapon_authoring
import generate_pod_payload_authoring
import generate_throwable_authoring
import generate_package_residency
import apply_projectile_residency
import generate_status_catalog
import generate_weapon_movement
import generate_enemy_authoring
import generate_helldiver_fields
import generate_armor_stats
import generate_player_passives
import generate_live_evidence
import generate_events
import generate_event_natives
import generate_projectile_rows
import generate_stratagem_calldown
import generate_image_resources
import generate_text_resources
import generate_stratagem_slots
import generate_bombardment_payload
import generate_slot_cooldown
import generate_beacon_redirect
import generate_pelican
import generate_weapon_sounds
import generate_sound_events
import generate_wwise_plugin
import generate_stratagem_selector
import generate_stratagem_blocking
import generate_event_entities
import generate_attack_outputs
import generate_legacy_acknowledgements
from build_live_validation import revision,verify_installed
from hd2_archive import ARCHIVE_NAME,LUA_TYPE,make_archive,make_resource_archive,resource_hash,lua_resource
import validate_packaged_runtime
import validate_examples
import parallel

ROOT=build.ROOT
sys.path.insert(0,str(ROOT/'sdk'))
import hd2

PACKAGE_MODULES='hd2runtime/runtime/package_modules'


def runtime_resources():
    resources={k:v for k,v in build.resources(writable=True).items()
               if not k.startswith('hd2runtime/examples/') and k!='mods/skyeshade/hd2runtime_report'}
    resources[hd2.MODULE]=(ROOT/'packaging/library.lua').read_bytes()
    # Every internal module, so the library entry can capture all loaders at startup.
    internal=sorted(name for name in resources if name.startswith('hd2runtime/'))
    resources[PACKAGE_MODULES]=('-- Generated by scripts/build_release.py at packaging time.\nreturn {\n'
        +''.join('    '+json.dumps(name)+',\n' for name in internal)+'}\n').encode()
    return resources


RUNTIME_THUMBNAIL='thumbnail.png'   # packaging/thumbnail.png: the HD2Runtime logo, 512 x 512


def runtime_fonts():
    """The Runtime-owned FS Sinclair engine fonts (scripts/hd2_font.py; domains/ui_fonts.lua records their digest):
    {(type, name hash): (main, gpu)} from build/.font-cache, rebuilt from the installed game when the cache lacks them,
    and exactly the resources the domain describes (else refused). {} when neither the cache nor the game has them: the
    panel then draws in monaco, the engine font it falls back to."""
    import re
    import generate_ui_fonts
    text=(ROOT/generate_ui_fonts.OUTPUT).read_text(encoding='utf-8')
    m=re.search(r'\["resources"\]="([0-9a-f]{64})"',text)
    if not m:raise ValueError('domains/ui_fonts.lua has no resource digest')
    digest=m.group(1)
    found=generate_ui_fonts.cached_resources(digest)
    if found is None:
        try:
            domain,found=generate_ui_fonts.build_all(generate_ui_fonts.game_sources())
        except Exception as error:   # no installed game: the build goes on without the fonts
            print('runtime fonts unavailable ('+str(error)+'): the panel draws in monaco')
            return {}
        if domain['source']['resources']!=digest:
            raise ValueError('the fonts of the installed game build other resources than domains/ui_fonts.lua records: '
                'run scripts/generate_ui_fonts.py')
        generate_ui_fonts.store(found)
    return found


WHEEL_HOOK_OFF_FOLDER='runtime_wheel_hook_off'
WHEEL_HOOK_OFF_SETTING='hd2runtime/settings/wheel_hook_off'
WHEEL_HOOK_OFF_SOURCE=b'-- The "mouse wheel hook off" install option (runtime/mouse_wheel.lua).' + bytes([10]) + b'return true' + bytes([10])


def build_runtime(version,report_bytes=b'{}\n',folder=None):
    """Write the installed-once runtime ZIP exactly as released and return its path."""
    spec=json.loads((ROOT/'hd2runtime.json').read_text());sources=runtime_resources()
    fonts=runtime_fonts()
    gpu_resources=b''
    if fonts:
        # Lua and the fonts in the layout of the game's own archives (as a mod with images).
        resources={(LUA_TYPE,resource_hash(k)):(lua_resource(v),b'') for k,v in sources.items()}
        resources.update(fonts)
        archive,gpu_resources=make_resource_archive(resources)
    else:
        archive=make_archive({resource_hash(k):lua_resource(v) for k,v in sources.items()})
    description='Shared HD2Runtime API 1. Requires Bingus Shared Loader v15+ / API 1. Install once; no gameplay changes until a dependent mod requests them.'
    # The HD2Runtime logo for the mod manager (HD2 Arsenal): the manifest's IconPath and the option's Image, as other
    # mods ship theirs; outside runtime/, so the game never reads it.
    # 0.30.2: a second option, chosen in the mod manager (Arsenal, Echelon), also deploys a one-resource archive whose
    # presence turns the native mouse wheel hook off (runtime/mouse_wheel.lua M.SETTING); the first stays the default.
    hook_off=('Same runtime with the native mouse wheel hook off. Try this if the game closes with a GameGuard error '
        '(1015, "Suspicious program detected"): it may fix it. Mod windows then scroll by wheel only over a game menu.')
    manifest={'Version':1,'Guid':spec['guid'],'Name':'HD2Runtime '+version,'Description':description,
              'Options':[{'Name':'Shared runtime','Description':description,'Include':['runtime'],
                          'Image':RUNTIME_THUMBNAIL},
                         {'Name':'Shared runtime, mouse wheel hook off (may fix GameGuard crashes)',
                          'Description':hook_off,'Include':['runtime',WHEEL_HOOK_OFF_FOLDER],
                          'Image':RUNTIME_THUMBNAIL}],'IconPath':RUNTIME_THUMBNAIL}
    setting=make_archive({resource_hash(WHEEL_HOOK_OFF_SETTING):lua_resource(WHEEL_HOOK_OFF_SOURCE)})
    runtime_zip=Path(folder or ROOT/'build')/('HD2Runtime-'+version+'-runtime.zip')
    hd2.zip_files(runtime_zip,{'manifest.json':json.dumps(manifest,indent=2).encode(),
        'hd2runtime.json':json.dumps(spec,indent=2).encode(),'runtime/'+ARCHIVE_NAME:archive,
        'runtime/'+ARCHIVE_NAME+'.stream':b'','runtime/'+ARCHIVE_NAME+'.gpu_resources':gpu_resources,
        WHEEL_HOOK_OFF_FOLDER+'/'+ARCHIVE_NAME:setting,WHEEL_HOOK_OFF_FOLDER+'/'+ARCHIVE_NAME+'.stream':b'',
        WHEEL_HOOK_OFF_FOLDER+'/'+ARCHIVE_NAME+'.gpu_resources':b'',
        'README.md':(ROOT/'sdk/README.md').read_bytes(),'build-report.json':report_bytes,
        'provenance.json':(ROOT/'docs/provenance.json').read_bytes(),
        RUNTIME_THUMBNAIL:(ROOT/'packaging'/RUNTIME_THUMBNAIL).read_bytes()})
    return runtime_zip


def starter_files():
    return {path.relative_to(ROOT/'starter').as_posix():path.read_bytes()
            for path in sorted((ROOT/'starter').rglob('*')) if path.is_file()
            and 'build' not in path.relative_to(ROOT/'starter').parts}


def build_starter(version,folder=None):
    path=Path(folder or ROOT/'build')/('HD2Runtime-ModTemplate-'+version+'.zip')
    hd2.zip_files(path,starter_files())
    return path


def example_config(data,version):
    """An example's hd2runtime.json as shipped: its SDK paths for the example-projects ZIP and the SDK ZIP extracted
    side by side (the repository's own ../../../sdk means nothing there)."""
    config=json.loads(data)
    sdk='../../HD2Runtime-'+version+'-sdk'
    config.update({'sdk':sdk,'ide_library':sdk+'/stubs'})
    return json.dumps(config,separators=(',',':')).encode()


def examples_readme(version):
    return '''# HD2Runtime {v} example projects

Each folder is one small, working gameplay mod. Its source is `<Example>/src/addon.lua`; its README says what it does
and how to test it.

## Building an example

The examples build with the SDK's Python CLI (Python 3.10+). Extract this ZIP and `HD2Runtime-{v}-sdk.zip` side by
side:

    HD2Mods/
      HD2Runtime-{v}-sdk/                the SDK (holds hd2.py and metadata.json)
      HD2Runtime-{v}-example-projects/   this ZIP
        KillHealTest/
          build.py

Then run `python build.py` in an example's folder, or double-click it. The mod is written to the example's `build/`
folder; import that ZIP into your mod manager.

`build.py` finds the SDK by itself, in this order:
- the `HD2RUNTIME_SDK` environment variable;
- the `sdk` path in the example's `hd2runtime.json`;
- the example's folder and every folder above it: the folder itself when it is the SDK, or a subfolder named `sdk` or
  ending in `-sdk`.

With the SDK anywhere else, run this once:

    python <SDK>/hd2.py configure <example folder> --sdk <SDK>

## Installing

Install Bingus Shared Loader and `HD2Runtime-{v}-runtime.zip` once, then each example you want as its own mod. Never
install the SDK or this ZIP.
'''.format(v=version).encode()


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--luals',type=Path,help='Optional LuaLS executable for real type/completion checks')
    parser.add_argument('--output',type=Path,default=ROOT/'build',
        help='folder for the release ZIPs and report (default build/; use a scratch folder for test builds)')
    parallel.add_argument(parser)
    args=parser.parse_args()
    parallel.configure(args.jobs)
    out=args.output;out.mkdir(parents=True,exist_ok=True)
    apply_projectile_residency.generate(check=True)
    generate_status_catalog.generate(check=True)
    generate_weapon_composition.generate(check=True)
    generate_support_weapon_sdk.generate(check=True)
    generate_support_weapon_authoring.generate(check=True)
    generate_entity_authoring.generate(check=True)
    generate_attachment_authoring.generate(check=True)
    generate_booster_authoring.generate(check=True)
    generate_stratagem_authoring.generate(check=True)
    generate_weapon_authoring.generate(check=True)
    generate_fire_mode_authoring.generate(check=True)
    generate_vehicle_weapon_authoring.generate(check=True)
    generate_pod_payload_authoring.generate(check=True)
    generate_throwable_authoring.generate(check=True)
    generate_package_residency.generate(check=True)
    generate_weapon_movement.generate(check=True)
    generate_enemy_authoring.generate(check=True)
    generate_helldiver_fields.generate(check=True)
    generate_armor_stats.generate(check=True)
    generate_player_passives.generate(check=True)
    generate_live_evidence.generate(check=True)
    generate_attack_outputs.generate(check=True)
    generate_weapon_modes.generate(check=True)
    generate_weapon_presentation.generate(check=True)
    generate_events.generate(check=True)
    generate_event_natives.generate(check=True)
    generate_projectile_rows.generate(check=True)
    generate_stratagem_calldown.generate(check=True)
    generate_image_resources.generate(check=True)
    generate_text_resources.generate(check=True)
    generate_stratagem_slots.generate(check=True)
    generate_bombardment_payload.generate(check=True)
    generate_slot_cooldown.generate(check=True)
    generate_beacon_redirect.generate(check=True)
    generate_pelican.generate(check=True)
    generate_weapon_sounds.generate(check=True)
    generate_sound_events.generate(check=True)
    generate_wwise_plugin.generate(check=True)
    generate_stratagem_selector.generate(check=True)
    generate_stratagem_blocking.generate(check=True)
    generate_event_entities.generate(check=True)
    generate_legacy_acknowledgements.generate(check=True)
    generate_sdk.generate(check=True)
    schema=hd2.database();version=(ROOT/'VERSION').read_text().strip()
    assert version==schema['runtime_version'],'Version/schema mismatch'
    commit=revision();installed=verify_installed()
    # The unit tests, the example validation and the shipped-artifact validation are independent (none writes
    # what another reads), so they run concurrently; their verdicts are still raised in this order.
    with ThreadPoolExecutor(max_workers=3) as pool,tempfile.TemporaryDirectory(dir=ROOT/'build') as folder:
        tests=pool.submit(subprocess.run,[sys.executable,'-B','scripts/run_tests.py','-v','--jobs',
            str(parallel.resolve(args.jobs))],cwd=ROOT,capture_output=True,text=True)
        examples=pool.submit(validate_examples.validate)
        # Run the shipped artifact itself, with late resource lookup disabled as in game.
        artifact=pool.submit(lambda:validate_packaged_runtime.validate(build_runtime(version,folder=folder),
            jobs=args.jobs))
        run=tests.result()
        print(run.stderr,end='')
        if run.returncode:raise RuntimeError('Release tests failed: '+run.stdout)
        examples_report=examples.result();artifact_report=artifact.result()
    assert revision()==commit,'Source changed during build'
    report={'version':version,'commit':commit,'tests':run.stderr,'installed_files':installed,
            'deployed':False,'game_launched':False,'live_process_access':False,
            'prior_gameplay_confirmation':'User confirmed 0.4.0 live gameplay proof',
            'new_live_gameplay_test':False,'fixture_fallback':'disabled'}
    support_capabilities=json.loads((ROOT/'sdk/SupportWeaponAuthoringCapabilities.json').read_text())
    support_validation=json.loads((ROOT/'research/support-weapon-authoring-validation-F5FEE03DCFDB.json').read_text())
    report['support_weapon_authoring']=support_capabilities['summary']
    report['support_weapon_capability_contract']={
        'schemaVersion':support_capabilities['schemaVersion'],
        'contract':support_capabilities['contract'],
        'instanceAudit':support_capabilities['instanceAudit'],
        'backingObjects':len(support_capabilities['backingObjects']),
        'operationGroups':len(support_capabilities['operationGroups'])}
    report['support_weapon_snapshot_validation']=support_validation
    report['support_weapon_proof_packages']=[
        'SupportAMRProof','RecoillessProof','ArcThrowerProof','C4Proof']
    stratagem_capabilities=json.loads((ROOT/'sdk/StratagemAuthoringCapabilities.json').read_text())
    report['stratagem_authoring']=stratagem_capabilities['summary']
    report['stratagem_snapshot_validation']=json.loads(
        (ROOT/'validation/stratagem-authoring-snapshot.json').read_text())
    call_in_links=support_capabilities['supportCallInLinks']
    assert call_in_links==stratagem_capabilities['supportCallInLinks'],'Support call-in linkage diverged'
    assert call_in_links['audit']['bidirectionalMismatches']==0,'Support call-in linkage is one-way'
    report['support_call_in_linkage']=call_in_links['audit']
    vehicle_capabilities=json.loads((ROOT/'sdk/VehicleAuthoringCapabilities.json').read_text())
    backpack_capabilities=json.loads((ROOT/'sdk/BackpackAuthoringCapabilities.json').read_text())
    report['vehicle_authoring']=vehicle_capabilities['summary']
    report['backpack_authoring']=backpack_capabilities['summary']
    report['magazine_attachment_authoring']=json.loads(
        (ROOT/'sdk/MagazineAttachmentCapabilities.json').read_text())['summary']
    report['magazine_attachment_snapshot_validation']=json.loads(
        (ROOT/'validation/magazine-attachment-snapshot.json').read_text())
    report['weapon_attachment_modifier_authoring']=json.loads(
        (ROOT/'sdk/WeaponAttachmentModifierCapabilities.json').read_text())['summary']
    report['weapon_attachment_modifier_snapshot_validation']=json.loads(
        (ROOT/'validation/weapon-attachment-modifier-snapshot.json').read_text())
    report['booster_authoring']=json.loads(
        (ROOT/'sdk/BoosterAuthoringCapabilities.json').read_text())['summary']
    report['reticle_authoring_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/reticle-authoring-snapshot.json').read_text()).items() if key!='weapons'}
    report['fire_mode_authoring_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/fire-mode-authoring-snapshot.json').read_text()).items() if key!='weapons'}
    report['weapon_fire_modes']=json.loads((ROOT/'sdk/WeaponFireModeCapabilities.json').read_text())['summary']
    report['weapon_modes_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/weapon-modes-snapshot.json').read_text()).items() if key!='weapons'}
    report['weapon_fire_rates']=json.loads((ROOT/'sdk/WeaponFireRateCapabilities.json').read_text())['summary']
    report['weapon_feeds']=json.loads((ROOT/'sdk/WeaponFeedCapabilities.json').read_text())['summary']
    report['weapon_presentation']=json.loads((ROOT/'sdk/WeaponPresentationCapabilities.json').read_text(
        encoding='utf-8'))['summary']
    report['output_composition']=json.loads((ROOT/'sdk/OutputCompositionCapabilities.json').read_text())['summary']
    ammo_research=json.loads((ROOT/'research/backpack-ammo-F5FEE03DCFDB.json').read_text())
    report['backpack_ammo']={'backpackFedWeapons':{item['supportWeapon']:{'capacity':item['deposit']['values']['0'],
        'startAmount':item['deposit']['values']['4'],'refillAmount':item['deposit']['values']['8'],
        'fingerprintExact':item['fingerprintExact'],'weaponOwnsMagazine':item['weaponOwnsMagazine']}
        for item in ammo_research['backpackFedWeapons']},'liveEquality':ammo_research['liveEquality']}
    report['backpack_ammo_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/backpack-ammo-snapshot.json').read_text()).items() if key!='backpacks'}
    report['pod_payloads']=json.loads((ROOT/'sdk/PodPayloadCapabilities.json').read_text())['summary']
    report['pod_payload_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/pod-payload-snapshot.json').read_text()).items() if key!='scenarios'}
    report['vehicle_weapons']=json.loads((ROOT/'sdk/VehicleWeaponCapabilities.json').read_text())['summary']
    report['vehicle_weapon_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/vehicle-weapon-authoring-snapshot.json').read_text()).items() if key!='scenarios'}
    report['reference_mod_inventory']={name:{key:item[key] for key in ('sha256','recreation','recreationStatus')}
        for name,item in json.loads((ROOT/'research/reference-mod-inventory-F5FEE03DCFDB.json').read_text())
        ['referenceMods'].items()}
    report['weapon_attachment_catalog']=json.loads(
        (ROOT/'sdk/WeaponAttachmentCatalog.json').read_text())['summary']
    report['magazine_attachment_authoring']=json.loads(
        (ROOT/'sdk/MagazineAttachmentCapabilities.json').read_text())['summary']
    report['options_binding_validation']=json.loads(
        (ROOT/'validation/options-binding-snapshot.json').read_text())
    report['booster_snapshot_validation']=json.loads(
        (ROOT/'validation/booster-authoring-snapshot.json').read_text())
    report['throwable_authoring']=json.loads(
        (ROOT/'sdk/ThrowableAuthoringCapabilities.json').read_text())['summary']
    report['throwable_snapshot_validation']=json.loads(
        (ROOT/'validation/throwable-authoring-snapshot.json').read_text())
    report['weapon_movement']=json.loads((ROOT/'sdk/WeaponMovementCapabilities.json').read_text())['summary']
    report['asset_dependencies']=json.loads(
        (ROOT/'sdk/AssetDependencyCapabilities.json').read_text())['summary']
    report['asset_residency_snapshot_validation']={key:value for key,value in json.loads(
        (ROOT/'validation/asset-residency-snapshot.json').read_text()).items() if key!='snapshots'}
    report['entity_snapshot_validation']=json.loads(
        (ROOT/'validation/entity-authoring-snapshot.json').read_text())
    recreations=json.loads((ROOT/'validation/reference-mod-recreations.json').read_text())
    assert recreations['status']=='EXACT_MATCH','Reference mod recreation is not exact'
    report['reference_mod_recreations']={name:{key:item[key] for key in
        ('status','physicalWrites','referenceWrites','referenceSources','omittedReferenceWrites')}
        for name,item in recreations['recreations'].items()}
    report['stratagem_proof_packages']=['OrbitalLaserProof','OrbitalPrecisionProof',
        'OrbitalBarrageProof','EagleProof','SupportStratagemCooldownProof',
        'AntiTankEmplacementProof','ConventionalSentryProof','ExplosiveSentryProof',
        'UnusualSentryProof','ShieldRelayRecreation','BastionReArmoredRecreation',
        'FRVWeaponSwapRecreation','JumpPackRecreation','ConcussiveDrumMagazine',
        'ArmedResupplyTurret','CombatStimBoost','BoosterTuning','IncendiaryHellpods',
        'LiberatorDamageOptions','ReticleAmrRecreation','JAR5FullAuto','ExosuitUnlimitedUses',
        'EmancipatorAmmo','LumbererAmmo','M103TurretMagazine','PatriotExosuitBuffs','MaxigunBackpackAmmo','SurplusEatPodSwap']
    # Every shipped example (projects, live examples, the ModTemplate) must pass current Runtime validation,
    # including snapshot baselines, acknowledgements and minimum versions; a rotten example fails the release.
    if examples_report['status']!='VALIDATED':
        raise RuntimeError('Example validation failed: '+', '.join(examples_report['failed']))
    report['example_validation']={'status':examples_report['status'],'examples':examples_report['examples'],
        'failed':examples_report['failed'],'baselineChanges':sum(item['baselineChanges'] or 0
            for item in examples_report['results'].values())}
    if args.luals:
        from check_sdk_luals import check
        report['luals']={'sdk':check(args.luals),'starter':check(args.luals,ROOT/'starter')}
    report['runtime_artifact_validation']=artifact_report
    report_bytes=(json.dumps(report,indent=2)+'\n').encode()
    runtime_zip=build_runtime(version,report_bytes,folder=out)
    sdk_zip=out/('HD2Runtime-'+version+'-sdk.zip')
    sdk_files={p.relative_to(ROOT/'sdk').as_posix():p.read_bytes() for p in (ROOT/'sdk').rglob('*')
               if p.is_file() and '__pycache__' not in p.parts and p.suffix!='.pyc'}
    from tools.snapshot_scan import bundle_bytes
    sdk_files['tools/snapshot_scan_modules.json']=bundle_bytes()
    sdk_files['build-report.json']=report_bytes
    hd2.zip_files(sdk_zip,sdk_files)
    example_files={}
    starter_zip=build_starter(version,folder=out)
    artifacts=[runtime_zip,sdk_zip,starter_zip]
    for project in sorted((ROOT/'examples/projects').iterdir()):
        if not project.is_dir():continue
        artifacts.append(hd2.build_project(project))
        for path in project.rglob('*'):
            if path.is_file() and not {'build','__pycache__','.idea'}.intersection(path.relative_to(project).parts):
                example_files[path.relative_to(ROOT/'examples/projects').as_posix()]=path.read_bytes()
        name=project.name+'/hd2runtime.json'
        example_files[name]=example_config(example_files[name],version)
    example_files['README.md']=examples_readme(version)
    examples_zip=out/('HD2Runtime-'+version+'-example-projects.zip')
    hd2.zip_files(examples_zip,example_files);artifacts.append(examples_zip)
    report['artifacts']=[{'file':str(p.resolve().relative_to(ROOT) if p.resolve().is_relative_to(ROOT) else p),
        'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in artifacts]
    (out/'sdk-release-report.json').write_text(json.dumps(report,indent=2)+'\n')
    for p in artifacts:print(p)
    print('commit='+commit)


if __name__=='__main__':main()
