"""Generate domains/direct_damage.lua: the reviewed DIRECT DAMAGE OVERRIDES of a fired round (research/direct-damage-
F5FEE03DCFDB.json, scripts/research_direct_damage.py): for each round projectile, the DamageInfo its row names (`from`,
its reviewed bytes), each override's DamageInfo (its reviewed bytes and values), the spawned projectile's hit-record
members (+0x0C the DamageInfo id, +0x18 the penetration copy) and the spawn-copy code pins runtime/projectile_impact.lua
re-proves before a write. Checked here: every row has the DamageInfo stride, every override is plain (no status) and
its standard and durable damage equal its label.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/direct-damage-F5FEE03DCFDB.json'
OUTPUT = 'domains/direct_damage.lua'


def build() -> dict:
    d = json.loads(RESEARCH.read_text(encoding='utf-8'))
    stride = d['tables']['damageStride']
    rounds = {}
    for projectile, r in sorted(d['rounds'].items(), key=lambda kv: int(kv[0])):
        if len(bytes.fromhex(r['fromReviewed'])) != stride:
            raise ValueError('round %s: its DamageInfo row is not %d bytes' % (projectile, stride))
        overrides = {}
        for label, o in sorted(r['overrides'].items(), key=lambda kv: int(kv[0])):
            if len(bytes.fromhex(o['reviewed'])) != stride or o['statuses']:
                raise ValueError('round %s override %s is not a plain DamageInfo row' % (projectile, label))
            if (o['standard'], o['durable']) != (int(label), int(label)):
                raise ValueError('round %s override %s: %d / %d' % (projectile, label, o['standard'], o['durable']))
            overrides[label] = {'damage': o['damage'], 'standard': o['standard'], 'durable': o['durable'],
                'armorPenetration': o['armorPenetration'], 'reviewed': o['reviewed']}
        rounds[projectile] = {'weapon': r['weapon'], 'from': r['from'], 'fromReviewed': r['fromReviewed'],
            'own': {'standard': r['own']['standard'], 'durable': r['own']['durable'],
                'armorPenetration': r['own']['armorPenetration']}, 'overrides': overrides}
    return {'source': {'research': RESEARCH.name, 'build': d['build']}, 'table': d['tables']['damage'],
        'stride': stride, 'hit': d['hit'],
        'pins': [{'rva': p['rva'], 'hex': p['bytes'], 'label': p['label']} for p in d['pins']], 'rounds': rounds}


def outputs() -> dict[str, str]:
    return {OUTPUT: '-- Generated by scripts/generate_direct_damage.py; do not edit.\nreturn ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale generated direct damage domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
