"""Generate domains/weapon_variants.lua: the reviewed data of a support weapon's mission-scoped VARIANT of its own type
(docs/research/weapon-variants-F5FEE03DCFDB.md) from research/weapon-variants-F5FEE03DCFDB.json
(scripts/research_weapon_variants.py):

* each variant HOST (the M-1000 Maxigun): its pool (itself: the only support weapon with its component set), its four
  written records (index row, record, owner count 1, an FNV-1a of the native bytes), the presentation members (the
  clone's three, native bytes), its native round (ProjectileWeapon +0) and model (UnitComponent +0 UnitPath) members;
* the host's MODEL facts a derived Runtime-owned model must match (the SDK build derives it from the same unit):
  the package archive it ships beside, the unit's sizes and SHA-256s, its material list and body material, the
  material LUT texture and its format;
* the UnitPath consumer pins (every lookup call site and type-table read, reviewed), which runtime/weapon_clone.lua
  re-proves on the running game.dll before a model write.

Checked here: the research is read-only, every record has one owner, the pool is the host alone, every consumer site
has a reviewed kind and the model facts are the host's own UnitPath unit (the derived model keeps every reference
of the vanilla body material but its LUT).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/weapon-variants-F5FEE03DCFDB.json'
OUTPUT = 'domains/weapon_variants.lua'
SDK = 'sdk/ModelBaseCapabilities.json'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('the weapon variant research must be read-only')
    hosts = {}
    for name, h in research['hosts'].items():
        if any(r['ownerCount'] != 1 for r in h['records'].values()):
            raise ValueError(name + ': a variant host record is shared')
        if h['pool'] != [name] or len(h['componentClass']) != 1:
            raise ValueError(name + ': a variant host converts its own type only (its class is itself)')
        hosts[name] = {'entity': h['entity'], 'stratagem': h['stratagem'], 'pool': h['pool'],
            'records': h['records'], 'presentation': h['presentation'], 'markerKind': h['markerKind'],
            'projectile': h['projectile'], 'round': h['round'], 'model': h['model']}
    models = {}
    for name, m in research['models'].items():
        if m['unit']['resource'] != hosts[name]['model']['unit']:
            raise ValueError(name + ': the model facts are not its UnitPath unit')
        lut = m['lut']
        models[name] = {'archive': m['archive'], 'package': m['package'],
            'unit': {k: m['unit'][k] for k in ('resource', 'main', 'gpu', 'mainSha256', 'gpuSha256', 'materialsAt')},
            'slots': [{'slot': x['slot'], 'name': x['slotName'], 'material': x['material'], 'at': x['at'],
                'where': x['where']} for x in m['unit']['materials']],
            'body': {'slotIndex': m['body']['slotIndex'], 'material': m['body']['material'], 'main': m['body']['main'],
                'mainSha256': m['body']['mainSha256'], 'lutAt': m['body']['lutAt']},
            'lut': {'texture': lut['texture'], 'main': lut['main'], 'gpu': lut['gpu'], 'format': lut['format'],
                'mainSha256': lut['mainSha256'], 'gpuSha256': lut['gpuSha256']}}
    uses = research['unitPathConsumers']
    if any(not s['kind'] for s in uses['sites']):
        raise ValueError('an unreviewed UnitPath consumer')
    return {'source': {'research': RESEARCH.name, 'build': research['build']}, 'hosts': hosts, 'models': models,
        'unitPins': [{'rva': int(p['rva']) if isinstance(p['rva'], int) else int(str(p['rva']), 0), 'hex': p['hex'],
            'label': p['label']} for p in uses['pins']],
        'types': {'unit': '0xE0A48D0BE9A7453F', 'material': '0xEAC0B497876ADEDF', 'texture': '0xCD4238C6A0C69E32'}}


def sdk_bases(d: dict) -> dict:
    """sdk/ModelBaseCapabilities.json: the reviewed facts the SDK build derives a model from (scripts/hd2_model.py)."""
    return {'format': 1, 'build': d['source']['build'], 'source': 'research/' + d['source']['research'],
        'note': 'Generated by scripts/generate_weapon_variants.py. A model (models/<id>.json "base") derives from one of '
            'these units; the installed game\'s parts must match these SHA-256s.',
        'bases': {name: dict(m, build=d['source']['build']) for name, m in sorted(d['models'].items())}}


def outputs() -> dict[str, str]:
    d = build()
    return {OUTPUT: '-- Generated by scripts/generate_weapon_variants.py; do not edit.\nreturn ' + lua(d) + '\n',
        SDK: json.dumps(sdk_bases(d), indent=1) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale generated weapon variant domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
