"""Generate domains/ui_fonts.lua and the Runtime-owned FS Sinclair engine fonts (scripts/hd2_font.py) from the installed
game: the font names the custom stratagem panel draws with, their metrics (em, cap height, ascent, descent, line
height) and every glyph's advance at the em size (the panel measures text with them), and the SHA-256 of each built
resource. The resources themselves are cached in build/.font-cache (keyed by this domain's digests); the Runtime build
(scripts/build_release.py runtime_fonts) packs them into the Runtime's own archive and refuses resources whose digests
differ from this domain. Also monaco's metrics (the fallback font).

The game's own language fonts (research/docs/game-font-text.md; hd2_font.GAME_FONTS): each font's hash, atlas,
package, em, line and baseline drop in domains/ui_fonts.lua (`game`), its advances and kerning pairs in
domains/ui_fonts_<key>.lua (loaded only when a text needs it), and one Runtime-owned material per font plus the
placeholder texture those materials name (built into the same resources and digest). Every game font is re-proven
against the installed game (its atlas fit, em, padding and distance encoding) or the generation fails.
Read-only: nothing is written to the game.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import pickle
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402
import hd2_font  # noqa: E402

OUTPUT = 'domains/ui_fonts.lua'
CACHE = ROOT / 'build/.font-cache'
ROLES = {'title': 'medium', 'body': 'regular'}


def _digest(resources: dict) -> str:
    h = hashlib.sha256()
    for key in sorted(resources):
        main, gpu = resources[key]
        h.update(struct.pack('<QQ', *key) + hashlib.sha256(main).digest() + hashlib.sha256(gpu).digest())
    return h.hexdigest()


KERN_KEY = 4294967296   # a kerning pair's key in Lua: previous * 2^32 + codepoint (exact in a double)


def game_font_files(src: dict) -> tuple[list, dict, dict]:
    """(the domain's `game` list, {path: Lua source} of the per-font metrics, {(type, hash): parts} of the materials
    and the placeholder) for hd2_font.GAME_FONTS. Nothing when the sources hold no game fonts (offline tests)."""
    from hd2_archive import resource_hash
    entries, files, resources = [], {}, {}
    if not src.get('game_fonts'):
        return entries, files, resources
    for key, label, package, languages, font, atlas in hd2_font.GAME_FONTS:
        m = hd2_font.game_font_metrics(key, src['game_fonts'][key])
        material_name, material = hd2_font.game_font_material(key, src['monaco_material'])
        resources[(hd2_font.MATERIAL_TYPE, resource_hash(material_name))] = (material, b'')
        module = 'domains/ui_fonts_' + key + '.lua'
        body = {'key': key, 'advances': m['advances'],
            'kerning': {a * KERN_KEY + b: v for (a, b), v in sorted(m['kerning'].items())}}
        files[module] = ('-- Generated by scripts/generate_ui_fonts.py from the installed game; do not edit.\n-- The '
            + label + " game font 0x%016X: every glyph's advance and its kerning pairs (previous * 2^32 + codepoint), "
            'in font units (em 32).\nreturn ' % font) + lua(body) + '\n'
        h = m['header']
        entries.append({'key': key, 'label': label, 'languages': languages, 'package': '%016X' % package,
            'font': '%016X' % font, 'atlas': '%016X' % atlas, 'material': material_name, 'em': h['em'],
            'line': h['line'], 'drop': m['drop'], 'cap': m['cap'], 'glyphs': len(m['advances']),
            'kerning': len(m['kerning']), 'module': 'hd2runtime/' + module[:-4],
            'sha256': hashlib.sha256(src['game_fonts'][key]['font']).hexdigest()})
    main, gpu = hd2_font.placeholder_texture()
    resources[(hd2_font.TEXTURE_TYPE, resource_hash(hd2_font.GAME_FONT_PLACEHOLDER))] = (main, gpu)
    return entries, files, resources


def build_all(src: dict) -> tuple[dict, dict]:
    """(the domain data, {(type, hash): parts} of every Runtime font resource) from the game's fonts."""
    domain, resources, _files = build_everything(src)
    return domain, resources


def build_everything(src: dict) -> tuple[dict, dict, dict]:
    """(the domain data, {(type, hash): parts} of every Runtime font resource, {path: source} of the game font metric
    modules) from the game's fonts."""
    fonts, resources = {}, {}
    for role, source in ROLES.items():
        out = hd2_font.build_font(src['ttf'][source], hd2_font.NAMES[source], src['monaco_material'])
        resources.update(out['resources'])
        r = out['report']
        fonts[role] = {'name': r['name'], 'source': 'FS Sinclair' + (' Medium' if source == 'medium' else ''),
            'em': r['em'], 'cap': r['capHeight'], 'ascent': r['ascent'], 'descent': r['descent'],
            'line': r['ascent'] + r['descent'], 'glyphs': r['glyphs'],
            'advances': {cp: round(rec[6], 3) for cp, rec in sorted(out['records'].items())},
            'sha256': r['sha256']}
    mono = hd2_font.parse_font(src['monaco_font'])
    fonts['monaco'] = {'name': 'core/performance_hud/monaco', 'em': mono['em'], 'cap': 33.0, 'ascent': 37.0,
        'descent': 8.0, 'line': mono['line'],
        'advances': {cp: round(rec[6], 3) for cp, rec in sorted(mono['glyphs'].items())}}
    if src.get('monaco_atlas'):
        # Where monaco's baseline lands against the y Gui.text is given (a fraction of the size; measured on its atlas
        # as for the game fonts, hd2_font.baseline_drop): game font runs mixed into monaco text align with it.
        mono_atlas = hd2_font.atlas_top_mip(*src['monaco_atlas'])
        fonts['monaco']['drop'] = hd2_font.baseline_drop(mono, mono_atlas)['drop']
    game, files, game_resources = game_font_files(src)
    resources.update(game_resources)
    domain = {'source': {'generator': 'scripts/generate_ui_fonts.py', 'archive': hd2_font.FONT_ARCHIVE,
        'ttf': {k: '0x%016X' % v for k, v in hd2_font.SOURCES.items()}, 'resources': _digest(resources)},
        'types': {'font': '0x%016X' % hd2_font.FONT_TYPE, 'material': '0x%016X' % hd2_font.MATERIAL_TYPE,
            'texture': '0x%016X' % hd2_font.TEXTURE_TYPE},
        'fonts': fonts, 'game': game, 'placeholder': hd2_font.GAME_FONT_PLACEHOLDER}
    return domain, resources, files


def game_sources() -> dict:
    src = hd2_font.game_fonts()
    import hd2_game_data
    data = hd2_game_data.Data()
    found = data.find({(hd2_font.MONACO, hd2_font.FONT_TYPE), (hd2_font.MONACO_ATLAS, hd2_font.TEXTURE_TYPE)})
    archive, main, _s, _g = found[(hd2_font.MONACO, hd2_font.FONT_TYPE)]
    src['monaco_font'] = data.read(archive, main)
    t_archive, t_main, _ts, t_gpu = found[(hd2_font.MONACO_ATLAS, hd2_font.TEXTURE_TYPE)]
    src['monaco_atlas'] = (data.read(t_archive, t_main), data.read(t_archive, t_gpu, '.gpu_resources'))
    src['game_fonts'] = hd2_font.read_game_fonts(data)
    return src


def cached_resources(digest: str):
    path = CACHE / ('fonts-' + digest[:32] + '.pkl')
    if path.is_file():
        resources = pickle.loads(path.read_bytes())
        if _digest(resources) == digest:
            return resources
    return None


def store(resources: dict) -> None:
    CACHE.mkdir(parents=True, exist_ok=True)
    (CACHE / ('fonts-' + _digest(resources)[:32] + '.pkl')).write_bytes(pickle.dumps(resources))


def outputs() -> tuple[dict, dict]:
    domain, resources, files = build_everything(game_sources())
    store(resources)
    body = '-- Generated by scripts/generate_ui_fonts.py from the installed game; do not edit.\nreturn ' + lua(domain) + '\n'
    return {OUTPUT: body, **files}, resources


def generate(check=False):
    files, _resources = outputs()
    stale = []
    for name, body in files.items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale generated UI font domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
