"""Generate domains/teammate_hud.lua from research/teammate-hud-F5FEE03DCFDB.json: the in-mission teammate stratagem
HUD's layout (the squad container, its teammate panels and their four cards) and every pin the teammate card overlays
(runtime/stratagem_slot_overlay.lua mission_remote_slots) prove before their first read.

  py scripts/generate_teammate_hud.py [--check]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/teammate-hud-F5FEE03DCFDB.json'
OUTPUT = 'domains/teammate_hud.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    pins = [{'label': pin['role'] or pin['asm'], 'rva': pin['rva'], 'hex': pin['bytes'], 'module': 'game'}
        for group in research['proofs'].values() for pin in group]
    if len({pin['rva'] for pin in pins}) != len(pins):
        raise ValueError('a pin is listed twice')
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        'layout': research['layout'], 'semantics': research['semantics'], 'unproven': research['unproven'],
        'pins': sorted(pins, key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {OUTPUT: '-- Generated by scripts/generate_teammate_hud.py; do not edit.\nreturn ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale teammate HUD domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
