"""Generate domains/slot_cooldown.lua: a mission stratagem record entry's cooldown times, the game clock's unit, the
row's cooldown and cooldown type, and the HUD slot members that show them, which runtime/slot_cooldown.lua
(development) reads, with the pinned code it re-proves first, from research/slot-cooldown-F5FEE03DCFDB.json
(docs/custom-stratagems.md, "The fixed cooldown").
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/slot-cooldown-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/slot_cooldown.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('slot cooldown research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDll']['sha256'] not in profile:
        raise ValueError('the slot cooldown research covers another build than schemas/current.lua')
    if not all(s['sharedEndBelowClock'] for s in research['snapshots']):
        raise ValueError('a retained record holds a shared cooldown end above its clock')
    unique = {}
    for rows in research['pins'].values():
        for pin in rows:
            unique.setdefault(pin['rva'], {'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes']})
    clock = research['clock']
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        # [game + global] + time = the game clock: a u64 in microseconds (perSecond per second).
        'clock': {'global': int(clock['global'], 16), 'time': clock['time'], 'perSecond': clock['perSecond']},
        # A record entry's u64 game times: the activation, the cooldown end (unavailable while above the clock) and the
        # call-in's arrival; the game counts the cooldown from the arrival.
        'entry': research['entry'],
        # StratagemInfo: the cooldown in seconds (f32) and the cooldown type (u32, 0: the entry's own).
        'row': research['row'],
        # The in-mission HUD list slot (hud + pathOffset + index x stride): the time left inbound and cooling (f32 s);
        # its bar widget (slot + bar): the entry index, the total it took on its first cooling frame and its state.
        'hud': research['hud'],
        'pins': sorted(unique.values(), key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {'domains/slot_cooldown.lua': '-- Generated by scripts/generate_slot_cooldown.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale slot cooldown domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
