"""Generate domains/component_tables.lua: where the game reads each entity component table from (the entity manager's
per-component table pointer) and the pinned code that proves it, which core/component_tables.lua re-proves before a
typed write to a component record, from research/entity-component-table-pointers-F5FEE03DCFDB.json
(research/docs/entity-component-table-pointers.md; docs/diagnostics.md "Values changed by mods outside HD2Runtime").
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/entity-component-table-pointers-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/component_tables.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('component table research must be read-only')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDll']['sha256'] not in profile:
        raise ValueError('the component table research covers another build than schemas/current.lua')
    checks = research['checks']
    for key in ('globalWrittenOnlyByTheConstructor', 'slotsWrittenOnlyByTheLoader', 'everyComponentHasAGlobalLookup',
                'everySlotSiteReadsTheManagerFromTheGlobal', 'everySnapshotPinByteIdentical',
                'everyOtherPointerMovedOutsideTheGame', 'managerIsPrivateMemory'):
        if checks[key] is not True:
            raise ValueError('component table research check failed: ' + key)
    if checks['snapshotsWithEveryPointerOnTheProfileTable'] < 1:
        raise ValueError('no retained snapshot holds every reviewed table pointer in place')
    pins = [{'rva': pin['rva'], 'hex': pin['bytes'], 'label': pin['role']} for pin in research['code']['pins']]
    lookups = {}
    for name, component in sorted(research['code']['components'].items()):
        lookups[name] = [{'rva': pin['rva'], 'hex': pin['bytes'], 'label': pin['role']}
                         for pin in component['lookupPins']]
    extent = max([p['rva'] + len(p['hex']) // 2 for p in pins]
                 + [p['rva'] + len(p['hex']) // 2 for rows in lookups.values() for p in rows]
                 + [int(research['entityManagerGlobal'], 16) + 8])
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        # [game.dll + global] = the entity manager (its constructor's only store); manager + slotBase + 8 x component
        # index = the address of the table the game reads that component's records from (the loader's only store).
        'global': int(research['entityManagerGlobal'], 16), 'slotBase': int(research['slotBase'], 16),
        'slots': 325,
        # In place, that table is the entity allocation + the profile component offset + 28 (DL frame + 0x18).
        'tableFromProfileOffset': 28,
        # game.dll bytes the pins and the global need (the image owner's extent for the reads).
        'imageExtent': extent,
        'pins': pins, 'lookups': lookups}


def outputs() -> dict[str, str]:
    return {'domains/component_tables.lua': '-- Generated by scripts/generate_component_tables.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale component table domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
