"""Generate domains/support_delivery.lua: the hellpod a support beacon spawns and the rack slots naming its exact weapon
entities, which runtime/support_pods.lua (development) reads read-only, with the pinned code it re-proves first, from
research/support-delivery-F5FEE03DCFDB.json (research/docs/gas-eat-F5FEE03DCFDB.md).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/support-delivery-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/support_delivery.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('support delivery research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDll']['sha256'] not in profile:
        raise ValueError('the support delivery research covers another build than schemas/current.lua')
    layout = research['layout']
    asm = [pin['asm'] for rows in research['proofs'].values() for pin in rows]

    def requires(text):
        if not any(text in line for line in asm):
            raise ValueError('support delivery: %s is not a pinned instruction' % text)
    t, r = layout['transport'], layout['rack']
    requires('[rcx + r14 + 0x%x], eax' % t['type'])
    requires('[rbx + rcx + 0x%x], eax' % t['beaconNetwork'])
    requires('mov dword ptr [r12 + %d], esi' % t['contentEntity'])
    requires('mov dword ptr [r12 + 0x%x], esi' % t['contentEntityCopy'])
    requires('[rbx + rcx + 0x%x], eax' % r['type'])
    requires('imul rsi, rsi, 0x%x' % r['stride'])
    requires('add rsi, %d' % r['slots'])
    requires('qword ptr [rsi + 0x%x]' % r['elements'])
    for member in ('capacity', 'multiplier', 'keys', 'empty'):
        requires('[rsi + 0x%x]' % r[member])
    pins = [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes']}
        for rows in research['proofs'].values() for pin in rows]
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        'transport': t, 'handle': layout['handle'], 'rack': r,
        # The EAT-17: its stable id, its rack and its launcher entity resource (reference; the Runtime resolves the type
        # by stable id and reads the slots live).
        'eat17': {'stableId': research['eat17']['stableId'], 'item': research['eat17']['item'],
            'rack': research['eat17']['rack'], 'projectile': research['eat17Rocket']['projectile'],
            'impactExplosion': research['eat17Rocket']['impactExplosion']},
        'pins': sorted(pins, key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {'domains/support_delivery.lua': '-- Generated by scripts/generate_support_delivery.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale support delivery domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
