"""Generate domains/beacon_redirect.lua: the stratagem beacon manager's path and layout, the element and state members
and the pinned code the per-beacon redirect (runtime/beacon_redirect.lua, development) re-proves first, from
research/beacon-redirect-F5FEE03DCFDB.json (docs/research/beacon-redirect-F5FEE03DCFDB.md).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/beacon-redirect-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/beacon_redirect.lua'
GROUPS = ('managerPath', 'managerLayout', 'replication', 'typeReaders', 'activation', 'timing', 'dispatchRecord', 'marker',
    'callInTracking', 'timingReaders', 'bombardmentLifecycle')


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('beacon research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDll']['sha256'] not in profile:
        raise ValueError('the beacon research covers another build than schemas/current.lua')
    unique = {}
    for group in GROUPS:
        for pin in research['pins'][group]:
            unique.setdefault(pin['rva'], {'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes']})
    path = research['managerPath']
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        # [game + world] + systems + beacons = the beacon component manager.
        'path': {'world': int(path['world'], 16), 'systems': path['systems'], 'beacons': path['beacons']},
        # The manager's counts, entity map and arrays; an element (0x40) and a state (0x8E8) per beacon.
        'manager': research['beacon']['manager'], 'element': research['beacon']['element'],
        'state': research['beacon']['state'],
        # Type 0 reads the all-zero default row: no payload, nothing spawned (0x6ABE0E-0x6ABE21).
        'neutralType': research['neutralType']['type'],
        # The call-in timing: both timers computed once at creation from the carrier's row (call-in +0x54, linger
        # +0x60); the call-in delay is countdown - threshold, the life after activation the threshold.
        'timing': {'row': research['timing']['row']},
        # What the dispatcher recorded at an activation (state offsets; the element's waves): read-only evidence.
        'dispatch': research['dispatchRecord'],
        # A barrage instance's own counters (shells fired, shells and salvos left, its timers): read-only.
        'bombardment': research['bombardmentInstance'],
        # The marker component (its colour from its OWN type's row category +0xB8): read-only.
        'marker': {k: (int(v, 16) if k == 'global' else v) for k, v in research['marker'].items() if k != 'colours'},
        'pins': sorted(unique.values(), key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {'domains/beacon_redirect.lua': '-- Generated by scripts/generate_beacon_redirect.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale beacon redirect domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
