"""Generate domains/bombardment_payload.lua: the bombardment record lookup, the barrage manager, the active variants,
the code-proven pattern words, every reviewed orbital bombardment record and the donor-pattern compatibility that
runtime/bombardment_payload.lua (development) reads, with the pinned code it re-proves first, from
research/bombardment-payload-F5FEE03DCFDB.json (docs/custom-stratagems.md, "Payload stage B").
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/bombardment-payload-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/bombardment_payload.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('bombardment payload research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDll']['sha256'] not in profile:
        raise ValueError('the bombardment payload research covers another build than schemas/current.lua')
    for snap in research['snapshots']:
        if snap['instances'] or snap['barrages'] or snap['privateCopies'] or snap['activeVariants']:
            raise ValueError('the research snapshots must hold no barrage, private copy or active variant')
    unique = {}
    for rows in research['pins'].values():
        for pin in rows:
            unique.setdefault(pin['rva'], {'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes']})
    hexint = lambda value: int(value, 16)
    component, manager, variants = research['component'], research['manager'], research['variants']
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        # [[game + global] + indexField] = the bombardment index: slots x {u64 payload hash, u32 record, u32 flags}
        # (hash mod slots, linear probe); a record is index + recordOffset + record x stride.
        'component': {'global': hexint(component['global']), 'indexField': hexint(component['indexField']),
            'header': component['header'], 'slots': component['slots'], 'records': component['records'],
            'recordOffset': component['recordOffset'], 'stride': component['stride']},
        # [game + global] = the bombardment manager: instances (+instances) with handles [+handles][i] = {u64 payload
        # hash, u32 entity}; barrages (+barrages); private copies by entity (+privateTable {u32 entity, u32 copy}).
        'manager': {key: (hexint(value) if key == 'global' else value) for key, value in manager.items()},
        # [game + global] = the variant registry: active variants (+active, stride, count +activeCount) name groups
        # (+groups, count +groupCount) whose entries list payload hashes.
        'variants': {key: (hexint(value) if key == 'global' else value) for key, value in variants.items()},
        # [game + global] + time = the game clock (u64) an entry's cooldown end is compared with (0x66D200).
        'clock': {'global': hexint(research['clock']['global']), 'time': research['clock']['time']},
        'shellTable': hexint(research['shellTable']), 'emptyShell': hexint(research['emptyShell']),
        'shellStride': research['shellStride'],
        # StratagemInfo +0x3C: the call-in delivery value; a carrier's must equal the donor's.
        'delivery': research['delivery'],
        'pattern': research['pattern'], 'donor': research['donor'],
        'records': research['records'], 'shellRows': research['shellRows'],
        'compatibility': research['compatibility'],
        # Stage C: the Orbital Gas Strike's chain, read only (shell 197 -> explosion 82 -> damage 447 and volume
        # template 16 -> statuses 42/44): each row's table (pointers by id), stride, reviewed bytes and the words that
        # hold relocated pointers (masked).
        'shellDonor': research['shellDonor'],
        'gasChain': {key: value for key, value in research['gasChain'].items() if key != 'rows'},
        'gasChainRows': [{'kind': row['kind'], 'id': row['id'], 'table': hexint(row['table']), 'stride': row['stride'],
            'reviewed': row['reviewed'], 'masked': row['masked']} for row in research['gasChain']['rows']],
        'pins': sorted(unique.values(), key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {'domains/bombardment_payload.lua': '-- Generated by scripts/generate_bombardment_payload.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale bombardment payload domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
