"""Publish the central live-test evidence (schemas/live_evidence.json).

- sdk/LiveEvidenceCatalog.json: every in-game test session, test, result and observation, and every capability
  family with its status (live_proven / not_tested / inconclusive), scope and the acknowledgement change it made.
  Fields of a live-proven family carry a compact `liveEvidence` reference in their own catalogs.
- docs/live-evidence.md: the same, for readers.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import live_evidence  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
JSON_OUTPUT = ROOT / 'sdk/LiveEvidenceCatalog.json'
MD_OUTPUT = ROOT / 'docs/live-evidence.md'
CONTRACT = 'hd2runtime.live_evidence.v1'
RESULT_LABEL = {'PASS': 'pass', 'NOT_TESTED': 'not tested', 'INCONCLUSIVE': 'inconclusive'}


def build():
    registry = live_evidence.load()
    families = registry['families']
    for session in registry['sessions']:
        for test in session['tests']:
            if test['family'] not in families:
                raise ValueError('live test names an unknown family: ' + test['family'])
            expected = 'live_proven' if test['result'] == 'PASS' else test['result'].lower()
            if families[test['family']]['status'] != expected and test['result'] != 'PASS':
                raise ValueError(f"family {test['family']} status disagrees with test {test['mod']}")
    for name, entry in families.items():
        if entry['status'] == 'live_proven' and not any(t['result'] == 'PASS' for t in live_evidence.tests(name)):
            raise ValueError('live_proven family without a passing test: ' + name)
    summary = {'sessions': len(registry['sessions']),
        'tests': sum(len(s['tests']) for s in registry['sessions']),
        'passed': sum(t['result'] == 'PASS' for s in registry['sessions'] for t in s['tests']),
        'families': {status: sorted(n for n, e in families.items() if e['status'] == status)
            for status in ('live_proven', 'not_tested', 'inconclusive')}}
    document = {'contract': CONTRACT, 'schemaVersion': 1,
        'hd2RuntimeVersion': (ROOT / 'VERSION').read_text().strip(), 'build': registry['build'],
        'statusLevels': registry['statusLevels'], 'summary': summary, 'families': families,
        'sessions': registry['sessions']}
    lines = ['# Live evidence', '',
        'Generated by `scripts/generate_live_evidence.py` from `schemas/live_evidence.json`, the one place in-game test '
        'results are recorded. The public copy is `sdk/LiveEvidenceCatalog.json`.', '',
        'A capability family is **live-proven** only when a user-run in-game test showed the intended effect. Only '
        'live-proven families drop `allow_unverified_effect`, and only within the scope below. Their fields carry a '
        '`liveEvidence` reference in their own capability catalogs. Tests that were not run or were inconclusive '
        'leave the family offline-proven.', '',
        '## Capability families', '',
        '| Family | Status | Fields | Scope | Acknowledgement |', '| --- | --- | --- | --- | --- |']
    for name, entry in families.items():
        change = ('removed `' + entry['acknowledgementRemoved'] + '`' if entry.get('acknowledgementRemoved') else
            'added `' + entry['acknowledgementAdded'] + '`' if entry.get('acknowledgementAdded') else 'unchanged')
        lines.append(f"| `{name}` | {entry['status'].replace('_', '-')} | "
            + ', '.join(f'`{f}`' for f in entry['fields']) + f" | {entry['scope']} | {change} |")
    notes = [(name, entry) for name, entry in families.items()
        if entry.get('notPromoted') or entry.get('behaviour') or entry.get('observations') or entry.get('analysis')]
    if notes:
        lines += ['', '## Notes', '']
        for name, entry in notes:
            lines.append(f'**`{name}`**')
            if entry.get('behaviour'):
                lines.append(f"- Behaviour: {entry['behaviour']}")
            for item in entry.get('observations') or []:
                lines.append(f'- Observation: {item}')
            if entry.get('analysis'):
                lines.append(f"- Analysis: {entry['analysis']}")
            if entry.get('notPromoted'):
                lines.append('- Not promoted (still need `allow_unverified_effect`): '
                    + ', '.join(entry['notPromoted']) + '.')
            if entry.get('nextTests'):
                lines.append('- Next tests: ' + ', '.join(f'`{t}`' for t in entry['nextTests']) + '.')
            lines.append('')
    for session in registry['sessions']:
        lines += [f"## Session {session['id']}", '', f"Runtime: {session['runtime']}.", '',
            'Every operation logged: ' + ', '.join(f'`{s}`' for s in session['logSignals']) + '.', '',
            '| Mod | Result | Writes | Observation |', '| --- | --- | --- | --- |']
        for test in session['tests']:
            writes = '; '.join(f"{w['target']}: `{w['field']}` {w['from']} → {w['to']}" for w in test['writes'])
            lines.append(f"| {test['mod']} | {RESULT_LABEL[test['result']]} | {writes} | {test['observation']} |")
        lines.append('')
    return json.dumps(document, indent=1) + '\n', '\n'.join(lines).rstrip() + '\n'


def generate(check=False):
    json_body, md_body = build()
    stale = [path for path, body in ((JSON_OUTPUT, json_body), (MD_OUTPUT, md_body))
        if not path.exists() or path.read_text(encoding='utf-8') != body]
    if stale and check:
        raise RuntimeError('Stale live evidence: ' + ', '.join(str(p) for p in stale))
    for path, body in ((JSON_OUTPUT, json_body), (MD_OUTPUT, md_body)):
        if path in stale:
            path.write_text(body, encoding='utf-8', newline='\n')
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(str(p) for p in generate(parser.parse_args().check)) or 'up to date')
