"""Generate domains/enemy_spawn_weights.lua from research/enemy-spawn-weights-F5FEE03DCFDB.json (docs/enemy-spawns.md):
the AI manager members, the roster row layout, every faction's roster (its descriptor, rows, and each row's enemy, group
and exact vanilla weights) and every pin proven before a write.

  py scripts/generate_enemy_spawn_weights.py [--check]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/enemy-spawn-weights-F5FEE03DCFDB.json'
OUTPUT = 'domains/enemy_spawn_weights.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    pins = [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes'], 'module': 'game'}
        for group in ('installer', 'lookup', 'pick') for pin in research['proofs'][group]]
    factions = []
    for faction in research['factions']:
        factions.append({'name': faction['name'], 'faction': faction['faction'], 'descriptor': faction['descriptor'],
            'rows': faction['rows'], 'count': faction['count'],
            'entries': [{'index': e['index'], 'entity': e['entity'], 'name': e['name'], 'id': e['id'],
                'group': e['group'], 'weights': e['weightsHex']} for e in faction['entries']]})
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256'], 'imageSize': research['gameDll']['imageSize']},
        'manager': research['manager'], 'row': research['row'], 'factions': factions,
        'semantics': research['semantics'], 'unproven': research['unproven'],
        'pins': sorted(pins, key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {OUTPUT: '-- Generated by scripts/generate_enemy_spawn_weights.py; do not edit.\nreturn ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale enemy spawn weights domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
