"""Generate domains/sound_event_names.lua: a name for every Wwise event the weapon sound catalogue holds.

The game's Wwise plugin posts an event only by name (WwiseWorld.trigger_event hashes it, FNV-1 32). The catalogue
(domains/weapon_sounds.lua) knows its events by id, so hd2.sounds.play posts each through a name whose hash is that id
(runtime/wwise_names.lua). Searching takes about 40 ms an id; this runs that very Lua code offline on the game's own
lua51.dll for every catalogued event, so the game never searches for one. Uncatalogued ids are still searched at
runtime. Offline; no game process.

  py scripts/generate_sound_event_names.py          # write
  py scripts/generate_sound_event_names.py --check  # fail when stale
"""
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from lua_offline import execute  # noqa: E402
from reference_format import lua  # noqa: E402

OUTPUT = ROOT / 'domains/sound_event_names.lua'
HEADER = '-- Generated by scripts/generate_sound_event_names.py from domains/weapon_sounds.lua; do not edit.\n'


def preload(name: str, path: str) -> str:
    return ('package.preload[' + lua(name) + ']=function(...)\n' + (ROOT / path).read_text(encoding='utf-8')
        + '\nend\n')


SCRIPT = r'''
local D=require('hd2runtime/domains/weapon_sounds')
local W=require('hd2runtime/runtime/wwise_names')
local ids,seen={},{}
for _,entry in pairs(D.sounds)do
    for _,key in ipairs({'event','start','stop'})do
        local hex=entry[key]
        local id=type(hex)=='string'and tonumber(hex,16)or nil
        if id and id>0 and not seen[id]then seen[id]=true;ids[#ids+1]=id end
    end
end
table.sort(ids)
local out={}
for _,id in ipairs(ids)do
    local name=assert(W.search(id),'no name for '..id)
    assert(W.id(name)==id)
    out[#out+1]=('[%d]=%q'):format(id,name)
end
return 'return {'..table.concat(out,',')..'}\n'
'''


def output() -> str:
    source = (preload('hd2runtime/domains/weapon_sounds', 'domains/weapon_sounds.lua')
        + preload('hd2runtime/runtime/wwise_names', 'runtime/wwise_names.lua') + SCRIPT)
    return HEADER + execute(source.encode('utf-8')).decode('utf-8')


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = output()
    current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.is_file() else None
    if args.check:
        if current != text:
            print('stale: ' + str(OUTPUT.relative_to(ROOT)))
            return 1
        return 0
    with open(OUTPUT, 'w', encoding='utf-8', newline='') as handle:
        handle.write(text)
    print('Generated ' + str(OUTPUT.relative_to(ROOT)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
