"""Generate the event entity catalog (domains/event_entities.lua) from the pinned datalibrary.

Every entity type that owns a HealthComponentData record, keyed by its type hash (the resource hash of its entity
path, which is also the u64 at the start of a live health descriptor). For each:

- kill: the record's KillScore (+0x30) is greater than 0. This is the game's own rule for counting a death as an
  enemy kill: the kill-credit listener (game.dll 0x129FD00) adds dealt_kills only when the victim's settings KillScore
  is positive (research/event-combat-F5FEE03DCFDB.json). It is what `entity:is_enemy()` and `event.enemy` report.
- faction: from the entity path (content/fac_bugs -> terminids, ...), when the path is known.
- name: the enemy catalog's wiki or class name, else the entity path's leaf, else nil (path hash unknown).

A per-instance settings copy (health manager +0x10B0) could differ from the shared record; none is known to change
KillScore, and the snapshots hold none.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
import build_profile  # noqa: E402
from migration import build_view  # noqa: E402
from reference_format import lua  # noqa: E402

OUTPUT = ROOT / 'domains/event_entities.lua'
ENEMIES = ROOT / 'sdk/EnemyAuthoringCapabilities.json'
KILL_SCORE = 0x30
FACTIONS = {'fac_bugs': 'terminids', 'fac_cyborgs': 'automatons', 'fac_illuminate': 'illuminate',
    'fac_helldivers': 'helldivers', 'fac_super_earth': 'super_earth'}
AVATAR = 'content/fac_helldivers/cha_avatar/avatar_helldiver'


def paths() -> dict[int, str]:
    sys.path.insert(0, str(ROOT / 'scripts'))
    from hd2_archive import resource_hash
    result = {}
    for line in (build_profile.FILEDIVER / 'hashes/hashes.txt').read_text(encoding='utf-8', errors='ignore').splitlines():
        line = line.strip()
        if line and not line.startswith('//'):
            result[resource_hash(line)] = line
    return result


def build() -> dict:
    view = build_view.from_datalibrary(build_profile.datalibrary(), {})
    if view.build['entitiesSha256'] != build_profile.ENTITY_SHA256:
        raise ValueError('pinned datalibrary changed')
    table = view.component('HealthComponentData')
    known = paths()
    enemy_names = {}
    for item in json.loads(ENEMIES.read_text(encoding='utf-8'))['classes']:
        from hd2_archive import resource_hash
        enemy_names[resource_hash(item['identity']['path'])] = item['wikiName'] or item['className']
    entities = {}
    for resource, (record, _row) in sorted(table.owners.items()):
        path = known.get(resource)
        folder = path.split('/')[1] if path and path.startswith('content/') and path.count('/') > 1 else None
        kill_score = struct.unpack_from('<i', table.records[record], KILL_SCORE)[0]
        entry = {'kill': kill_score > 0}
        name = enemy_names.get(resource) or (path.rsplit('/', 1)[-1] if path else None)
        if name:
            entry['name'] = name
        if FACTIONS.get(folder):
            entry['faction'] = FACTIONS[folder]
        if path == AVATAR:
            entry['avatar'] = True
        entities[f'{resource:016X}'] = entry
    if not entities.get(f'{__import__("hd2_archive").resource_hash(AVATAR):016X}', {}).get('avatar'):
        raise ValueError('the Helldiver avatar type is absent from the health owners')
    return {'source': {'build': build_profile.BUILD_ID, 'entitiesSha256': build_profile.ENTITY_SHA256,
        'killScoreOffset': KILL_SCORE}, 'entities': entities,
        'summary': {'types': len(entities), 'kill': sum(e['kill'] for e in entities.values()),
            'named': sum('name' in e for e in entities.values())}}


def outputs() -> dict[str, str]:
    value = build()
    return {'domains/event_entities.lua': '-- Generated by scripts/generate_event_entities.py; do not edit.\nreturn '
        + lua(value) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale event entity catalog: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
