"""Generate domains/sound_event_names.lua: a name for every Wwise id the sound catalogues hold.

The game's Wwise plugin takes every event, game parameter, switch and state only by name (it hashes the name, FNV-1
32; docs/research/wwise-plugin-bindings-F5FEE03DCFDB.md). The catalogues (domains/weapon_sounds.lua,
domains/sound_events.lua) know most ids only as numbers, so the Runtime posts each through a name whose hash is that id
(runtime/wwise_names.lua). Searching takes about 40 ms an id; this runs that very Lua code offline on the game's own
lua51.dll, in parallel, for every catalogued event id (both catalogues) and every unnamed game parameter, switch group,
switch, state group and state id, so the game never searches for one. Other ids are still searched at runtime.
Offline; no game process.

  py scripts/generate_sound_event_names.py          # write (about a minute)
  py scripts/generate_sound_event_names.py --check  # fail when stale: the id set, every name's hash, and a sample
                                                    # of ids searched again (a name is a pure function of its id)
"""
from __future__ import annotations

import argparse
from concurrent.futures import ThreadPoolExecutor
import os
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from lua_offline import execute  # noqa: E402
from reference_format import lua  # noqa: E402

OUTPUT = ROOT / 'domains/sound_event_names.lua'
HEADER = ('-- Generated by scripts/generate_sound_event_names.py from domains/weapon_sounds.lua and '
    'domains/sound_events.lua; do not edit.\n')
SAMPLE = 48


def preload(name: str, path: str) -> str:
    return ('package.preload[' + lua(name) + ']=function(...)\n' + (ROOT / path).read_text(encoding='utf-8')
        + '\nend\n')


IDS = r'''
local W=require('hd2runtime/domains/weapon_sounds')
local E=require('hd2runtime/domains/sound_events')
local ids,seen={},{}
local function add(hex)
    local id=type(hex)=='string'and tonumber(hex,16)or nil
    if id and id>0 and not seen[id]then seen[id]=true;ids[#ids+1]=id end
end
for _,entry in pairs(W.sounds)do
    for _,key in ipairs({'event','start','stop'})do add(entry[key])end
end
for _,entry in pairs(E.events)do add(entry.id)end
for hex,p in pairs(E.parameters)do if not p.name then add(hex)end end
for _,key in ipairs({'switchGroups','stateGroups'})do
    for hex,g in pairs(E[key])do
        if not g.name then add(hex)end
        for value,name in pairs(g.values)do if not name then add(value)end end
    end
end
table.sort(ids)
local out={}
for k,id in ipairs(ids)do out[k]=('%d'):format(id)end
return table.concat(out,',')
'''

SEARCH = r'''
local W=require('hd2runtime/runtime/wwise_names')
local out={}
for _,id in ipairs({%s})do
    local name=assert(W.search(id),'no name for '..id)
    assert(W.id(name)==id)
    out[#out+1]=('[%%d]=%%q'):format(id,name)
end
return table.concat(out,',')
'''


def catalogue_ids() -> list[int]:
    source = (preload('hd2runtime/domains/weapon_sounds', 'domains/weapon_sounds.lua')
        + preload('hd2runtime/domains/sound_events', 'domains/sound_events.lua') + IDS)
    text = execute(source.encode('utf-8')).decode('utf-8')
    return [int(v) for v in text.split(',') if v]


def search(ids: list[int]) -> dict[int, str]:
    if not ids:
        return {}
    source = preload('hd2runtime/runtime/wwise_names', 'runtime/wwise_names.lua') + SEARCH % ','.join(map(str, ids))
    text = execute(source.encode('utf-8')).decode('utf-8')
    return {int(i): n for i, n in re.findall(r'\[(\d+)\]="([^"]+)"', text)}


def render(names: dict[int, str]) -> str:
    return HEADER + 'return {' + ','.join('[%d]=%s' % (i, lua(names[i])) for i in sorted(names)) + '}\n'


def output() -> str:
    ids = catalogue_ids()
    chunks = [ids[k::64] for k in range(64)]
    names = {}
    with ThreadPoolExecutor(max_workers=max(2, (os.cpu_count() or 4))) as pool:
        for part in pool.map(search, chunks):
            names.update(part)
    if set(names) != set(ids):
        raise RuntimeError('a catalogue id has no name')
    return render(names)


def fnv1(name: str) -> int:
    h = 0x811C9DC5
    for c in name.lower().encode('ascii'):
        h = ((h * 0x01000193) & 0xFFFFFFFF) ^ c
    return h


def stored() -> dict[int, str]:
    text = OUTPUT.read_text(encoding='utf-8') if OUTPUT.is_file() else ''
    return {int(i): n for i, n in re.findall(r'\[(\d+)\]="([^"]+)"', text)}


def check() -> list[str]:
    """Why the stored table is stale ([] when current): the id set, every name's hash, the format, a sample."""
    problems = []
    names = stored()
    ids = catalogue_ids()
    if set(names) != set(ids):
        problems.append('the id set differs (%d stored, %d catalogued)' % (len(names), len(ids)))
    bad = [i for i, n in names.items() if fnv1(n) != i or not re.fullmatch(r'hd2runtime_[a-z0-9_]{7}', n)]
    if bad:
        problems.append('%d names do not hash to their ids' % len(bad))
    if OUTPUT.is_file() and OUTPUT.read_text(encoding='utf-8') != render(names):
        problems.append('the file is not in its generated form')
    step = max(1, len(ids) // SAMPLE)
    sample = sorted(ids)[::step][:SAMPLE]
    again = search([i for i in sample if i in names])
    if any(again[i] != names[i] for i in again):
        problems.append('a sampled id searches to another name')
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if args.check:
        problems = check()
        for p in problems:
            print('stale: ' + str(OUTPUT.relative_to(ROOT)) + ': ' + p)
        return 1 if problems else 0
    text = output()
    with open(OUTPUT, 'w', encoding='utf-8', newline='') as handle:
        handle.write(text)
    print('Generated ' + str(OUTPUT.relative_to(ROOT)))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
