"""Generate domains/projectile_homing.lua (docs/projectile-homing.md):

* from research/projectile-homing-F5FEE03DCFDB.json, the flight record members projectile homing reads and steers and
  every pin it proves before its first write;
* from research/projectile-identities-F5FEE03DCFDB.json, the weapons whose shots can home: every named owner of a
  projectile type (an entity member typed ProjectileType: a player, support or vehicle weapon, a mounted weapon, a
  stratagem payload or deployed entity) with the projectile types it fires and the entity types that fire them. Enemy
  owners are left out (their shots are never this machine's player's).

  py scripts/generate_projectile_homing.py [--check]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/projectile-homing-F5FEE03DCFDB.json'
IDENTITIES = ROOT / 'research/projectile-identities-F5FEE03DCFDB.json'
OUTPUT = 'domains/projectile_homing.lua'


def weapons(identities: dict) -> list[dict]:
    """Every named non-enemy owner: {name, categories, types, roles (type -> roles), sources (entity types)}."""
    by_name: dict[str, dict] = {}
    for row in identities['types']:
        for owner in row['identity']['owners']:
            resource = owner.get('resource')
            if not (isinstance(resource, str) and resource.startswith('0x') and len(resource) == 18):
                continue
            for name in owner['names']:
                if 'enemy' in name['category']:
                    continue
                entry = by_name.setdefault(name['name'], {'name': name['name'], 'categories': set(), 'types': set(),
                    'roles': {}, 'sources': set()})
                entry['categories'].add(name['category'])
                entry['types'].add(row['type'])
                entry['roles'].setdefault(row['type'], set()).add(owner['role'])
                entry['sources'].add(resource[2:].upper())
    out = []
    for name in sorted(by_name, key=str.lower):
        entry = by_name[name]
        out.append({'name': name, 'categories': sorted(entry['categories']), 'types': sorted(entry['types']),
            'roles': [{'type': t, 'roles': sorted(entry['roles'][t])} for t in sorted(entry['roles'])],
            'sources': sorted(entry['sources'])})
    lowered = [item['name'].lower() for item in out]
    if len(set(lowered)) != len(lowered):
        raise ValueError('two homing weapons differ only in case')
    return out


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    identities = json.loads(IDENTITIES.read_text(encoding='utf-8'))
    if identities['build'] != research['build']:
        raise ValueError('the projectile identities cover another build')
    pins = [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes'], 'module': 'game'}
        for group in ('update', 'integrator', 'network') for pin in research['proofs'][group]]
    return {'source': {'research': RESEARCH.name, 'identities': IDENTITIES.name, 'build': research['build'],
            'gameDllSha256': research['gameDll']['sha256']},
        'flight': research['pool']['flight'], 'flags': research['pool']['flags'],
        'semantics': research['semantics'], 'unproven': research['unproven'],
        'pins': sorted(pins, key=lambda pin: pin['rva']),
        'weapons': weapons(identities)}


def outputs() -> dict[str, str]:
    return {OUTPUT: '-- Generated by scripts/generate_projectile_homing.py; do not edit.\nreturn ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale projectile homing domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
