"""Generate domains/hud_icons.lua from sdk/HudIconSprites.json: every stratagem's and booster's HUD icon sprite name, for
hd2.resources.game_icon (runtime/game_icons.lua, docs/game-icons.md).

Only names are published, as in sdk/HudIconSprites.json: a sprite name is the lookup key of a record in the game's
in-memory atlas sprite map, and the Runtime reads the record (its atlas page and rectangle) from the running game.
No artwork, texture name or archive detail enters the repository.

    py scripts/generate_game_icons.py           # writes domains/hud_icons.lua
    py scripts/generate_game_icons.py --check   # exit 1 when the file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'sdk/HudIconSprites.json'
OUTPUT = ROOT / 'domains/hud_icons.lua'


def lua_string(text: str) -> str:
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def render(data: dict) -> str:
    lines = ['-- Generated by scripts/generate_game_icons.py from sdk/HudIconSprites.json; do not edit.',
             '-- Every stratagem\'s and booster\'s HUD icon sprite name (the key of its record in the game\'s atlas sprite',
             '-- map; the record itself is read from the running game). Names only: no artwork, texture name or archive',
             '-- detail.',
             'return {build=%s,source="sdk/HudIconSprites.json",' % lua_string(data['build'])]
    for kind, key in (('stratagem', 'stratagems'), ('booster', 'boosters')):
        lines.append('%s={' % key)
        for name in sorted(data[key]):
            sprite = data[key][name]['sprite']
            if not (sprite.startswith('0x') and len(sprite) == 18):
                raise ValueError('%s %s: sprite %r is not 0x and 16 hex digits' % (kind, name, sprite))
            lines.append('  [%s]="%s",' % (lua_string(name), sprite[2:].upper()))
        lines.append('},')
    lines.append('missing={')
    for name in sorted(data.get('missing', {})):
        lines.append('  [%s]=%s,' % (lua_string(name), lua_string(data['missing'][name])))
    lines.append('}}')
    return '\n'.join(lines) + '\n'


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true', help='only check that the output is current')
    args = parser.parse_args(argv)
    text = render(json.loads(SOURCE.read_text(encoding='utf-8')))
    if args.check:
        current = OUTPUT.read_text(encoding='utf-8') if OUTPUT.exists() else ''
        if current != text:
            print('%s is stale: run py scripts/generate_game_icons.py' % OUTPUT.relative_to(ROOT))
            return 1
        return 0
    OUTPUT.write_text(text, encoding='utf-8', newline='\n')
    data = json.loads(SOURCE.read_text(encoding='utf-8'))
    print('%s: %d stratagems, %d boosters' % (OUTPUT.relative_to(ROOT), len(data['stratagems']), len(data['boosters'])))
    return 0


if __name__ == '__main__':
    sys.exit(main())
