"""Generate the status-effect catalog from research/status-effects-F5FEE03DCFDB.json.

- domains/status_catalog.lua: the runtime's semantic <-> native status table, used to encode and verify
  status_reference fields. Only this build's numbers appear; semantic IDs come from each status row's own name.
- sdk/StatusEffectCatalog.json: the public catalog for ModBuilder: every status with its family, duration, tick
  damage, the attacks that already apply it, whether it can be attached to another attack, and the attachment
  model. Native type numbers are not published.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
import status_fields  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
LUA_OUTPUT = ROOT / 'domains/status_catalog.lua'
JSON_OUTPUT = ROOT / 'sdk/StatusEffectCatalog.json'
CONTRACT = 'hd2runtime.status_effects.v1'


def lua(value) -> str:
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if value is None:
        return 'nil'
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, dict):
        return '{' + ','.join('[' + lua(key) + ']=' + lua(item) for key, item in sorted(value.items(),
            key=lambda pair: str(pair[0]))) + '}'
    return '{' + ','.join(lua(item) for item in value) + '}'


def build():
    research = json.loads(status_fields.RESEARCH.read_text(encoding='utf-8'))
    statuses = research['statuses']
    runtime = {'statuses': {s['semanticId']: {'nativeType': s['nativeType'], 'name': s['name'],
            'family': s['family'], 'attachable': s['attachable']} for s in statuses},
        'byType': {s['nativeType']: s['semanticId'] for s in statuses}}
    lua_body = ('-- Generated by scripts/generate_status_catalog.py. Semantic status identity <-> this build\'s '
        'StatusEffectType.\nreturn ' + lua(runtime) + '\n')
    public = []
    for s in statuses:
        public.append({'semanticId': s['semanticId'], 'name': s['name'], 'family': s['family'],
            'duration': s['duration'], 'tickDamage': ({k: v for k, v in s['tickDamage'].items() if k != 'damageType'}
                if s['tickDamage'] else None),
            'appliedBy': s['knownConsumers'], 'slotUsers': s['slotUsers'],
            'strengthObserved': s['strength'],
            'attachable': s['attachable'], 'attachableReason': s['attachableReason'],
            'sharedGlobal': True,
            'assetDependency': 'none known: StatusEffectSettings is a global settings table resident in every mission',
            'durationField': 'status.duration (shared: every attack applying this status)'})
    model = research['model']
    document = {'contract': CONTRACT, 'schemaVersion': 1, 'hd2RuntimeVersion': (ROOT / 'VERSION').read_text().strip(),
        'source': research['source'],
        'attachmentModel': {
            'owner': 'DamageInfo (the damage definition a hit, explosion, beam/arc/spray tick or melee strike applies)',
            'slots': model['slots'],
            'packing': model['packing'],
            'fields': ['damage.status_<k>_type (status_reference)', 'damage.status_<k>_strength (number)'],
            'attachmentSlot': 'the first empty slot of each DamageInfo row; only it is offered, so slots stay packed',
            'directHitVsExplosion': 'separate DamageInfo rows: a projectile\'s direct-hit damage and its explosion '
                'damage each have their own four slots',
            'multipleStatuses': 'yes, up to four per DamageInfo row (flamethrowers apply fire, fire_panic and '
                'flamer_slowed from one row)',
            'application': 'per DamageInfo application: every projectile hit, every explosion, every beam / arc / '
                'spray tick, every melee strike',
            'sharedDefinitions': 'status definitions (duration, tick damage) are global; editing status.duration '
                'changes every attack that applies the status',
            'acknowledgements': ['allow_unverified_effect for every status slot write',
                'allow_shared when the DamageInfo row is shared by several weapons'],
            'blocked': ['adding a fifth status (the slot array is fixed at four)',
                'statuses only enemies, terrain, weather, stims or other systems apply',
                'removing a status from any but the last used slot (it would leave a gap)'],
            'damageRows': model['damageRows'], 'rowsBySlotsUsed': model['rowsBySlotsUsed']},
        'summary': {'statuses': len(statuses), 'attachable': sum(s['attachable'] for s in statuses),
            'families': {family: sum(1 for s in statuses if s['family'] == family)
                for family in sorted({s['family'] or 'unclassified' for s in statuses})}},
        'statuses': public}
    return lua_body, json.dumps(document, indent=2) + '\n'


def generate(check=False):
    lua_body, json_body = build()
    stale = [path for path, body in ((LUA_OUTPUT, lua_body), (JSON_OUTPUT, json_body))
        if not path.exists() or path.read_text(encoding='utf-8') != body]
    if stale and check:
        raise RuntimeError('Stale status catalog: ' + ', '.join(str(p) for p in stale))
    for path, body in ((LUA_OUTPUT, lua_body), (JSON_OUTPUT, json_body)):
        if path in stale:
            path.write_text(body, encoding='utf-8', newline='\n')
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(str(p) for p in generate(parser.parse_args().check)) or 'up to date')
