"""Generate domains/stratagem_blocking.lua: the native stratagem grid's per-card BLOCKED state (the card list entry byte
the game's own server-disabled treatment and pick refusal read), the grid's one-shot realize request, the catalogue
lookup from a stable id to a card key, and the pinned code runtime/stratagem_blocking.lua re-proves first, from
research/stratagem-blocking-F5FEE03DCFDB.json (research/docs/stratagem-blocking-F5FEE03DCFDB.md).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/stratagem-blocking-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/stratagem_blocking.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('blocking research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['gameDllSha256'] not in profile or research['exeSha256'] not in profile:
        raise ValueError('the blocking research covers another build than schemas/current.lua')
    access = research['access']
    if [row.split(':')[0] for row in access['blockedByte']['writers']] != ['0x18D444B']:
        raise ValueError('the card blocked byte has a writer other than the grid\'s add')
    if [row.split(':')[0] for row in access['catalogueDisabled']['writers']] != ['0x12E80FC', '0x12E81AE']:
        raise ValueError('the catalogue disabled flag has a writer outside the online override apply')
    by_id = {m['id']: m for m in research['mechanisms']}
    if not (by_id['card-blocked-byte']['implemented'] and not by_id['catalogue-disabled-flag']['implemented']):
        raise ValueError('only the UI-local card byte may be implemented')
    helper = research['cardEnable']
    if not (helper['sameInEverySnapshot'] and [w.split(': ', 1)[1] for w in helper['memoryWrites']] == [
            'mov byte ptr [r9 + rcx + 0x92dc2], sil', 'mov word ptr [rcx + 0x2b5a], dx']
            and [c.split(': ', 1)[1] for c in helper['calls']] == ['call 0x18ca560']):
        raise ValueError('the per-card grey helper is not the reviewed one')
    layout = research['layout']
    pins = []
    for rows in research['pins'].values():
        pins += [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes']} for pin in rows]
    unique = {}
    for pin in pins:
        unique.setdefault(pin['rva'], pin)
    return {'source': {'research': RESEARCH.name, 'build': research['build'],
            'gameDllSha256': research['gameDllSha256'], 'exeSha256': research['exeSha256']},
        # ui = [[game + ownerGlobal] + root]; the grid is open while ui + selectionOpen is set, the sub-state is the
        # stratagem slot and the edited slot a loadout slot. The card list is ui + list; the stratagem screen ui + screen.
        'loadout': layout['loadout'],
        # The card list (relative to it): mode (3 = stratagems), count, per entry the key (u32), the enabled byte and the
        # BLOCKED byte; the one-shot realize request, the scrollbar drag byte, the scroll-moved byte; and the screen's
        # grid-shown byte (relative to the screen).
        'grid': layout['grid'],
        # The account catalogue (read only): the stratagem range of record indexes, each record {definition, key, stable
        # id}, and the definition's server-disabled byte.
        'catalogue': layout['catalogue'],
        # What the game draws from the blocked byte (documentation; nothing here is written).
        'treatment': layout['treatment'],
        # The game's per-card grey helper (list, key, 0|1): its whole body, re-proved before every call.
        'cardEnable': {'rva': helper['rva'], 'code': helper['bytes']},
        'pins': sorted(unique.values(), key=lambda pin: pin['rva'])}


def outputs() -> dict[str, str]:
    return {'domains/stratagem_blocking.lua': '-- Generated by scripts/generate_stratagem_blocking.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale stratagem blocking domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
