"""Generate domains/projectile_ballistics.lua: a fired round's OWN stat copies (research/projectile-ballistics-
F5FEE03DCFDB.json, scripts/research_projectile_ballistics.py): the flight record members (velocity, gravity, mass, drag
constant, reference speed, distance, lifetime, substeps, driving unit) and the hit record members (damage multiplier,
penetration multiplier) a per-shot modification writes (runtime/projectile_shots.lua), each with its research verdict,
and every pin of the research (SpawnProjectile's stores, the update, the integrator, hit processing, the damage event)
the Runtime re-proves before a write. Checked here: every member written is WRITABLE_PER_ROUND, the record bases and
strides are the pool's (domains/projectile_rows.lua), every pin is hex.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402

RESEARCH = ROOT / 'research/projectile-ballistics-F5FEE03DCFDB.json'
OUTPUT = 'domains/projectile_ballistics.lua'
# The members a per-shot modification reads or writes: {name: (record, offset, verdict key or None for read-only)}.
FLIGHT = {'velocity': (0x0C, 'velocity'), 'gravity': (0x1C, 'gravity'), 'mass': (0x24, 'mass'), 'drag': (0x28, 'drag'),
    'speed': (0x2C, 'speed'), 'distance': (0x30, None), 'lifetime': (0x34, 'lifetime'), 'substeps': (0x48, 'substeps'),
    'unit': (0x50, None)}
HIT = {'directDamage': 0x0C, 'armorPenetration': 0x18, 'damageMultiplier': 0x34, 'penetrationMultiplier': 0x38}


def build() -> dict:
    d = json.loads(RESEARCH.read_text(encoding='utf-8'))
    rec = d['records']
    if (rec['flight']['base'], rec['flight']['stride'], rec['hit']['base'], rec['hit']['stride']) != (0x3040, 0x70,
            0x4D040, 0xC8):
        raise ValueError('the research records are not the pool layout')
    flight = {}
    for name, (offset, verdict) in FLIGHT.items():
        if verdict is not None and d['verdicts'][verdict]['verdict'] != 'WRITABLE_PER_ROUND':
            raise ValueError('flight member %s is not WRITABLE_PER_ROUND' % name)
        flight[name] = offset
    if d['damageMultiplier']['verdict'] != 'WRITABLE_PER_ROUND':
        raise ValueError('the damage multiplier is not WRITABLE_PER_ROUND')
    pins, seen = [], set()
    for group, items in d['proofs'].items():
        for p in items:
            if not re.fullmatch(r'[0-9a-f]+', p['bytes']):
                raise ValueError('pin %s is not hex' % p['rva'])
            if p['rva'] in seen:
                continue
            seen.add(p['rva'])
            pins.append({'rva': p['rva'], 'hex': p['bytes'], 'label': group + ': ' + p['role'][:80]})
    pins.sort(key=lambda p: p['rva'])
    return {'source': {'research': RESEARCH.name, 'build': d['build'], 'gameDllSha256': d['gameDllSha256']},
        'flight': dict(flight, base=rec['flight']['base'], stride=rec['flight']['stride'], read=0x58),
        'hit': dict(HIT, base=rec['hit']['base'], stride=rec['hit']['stride']),
        'speedFactor': d['damageMultiplier']['speedFactor'], 'pins': pins}


def outputs() -> dict[str, str]:
    return {OUTPUT: '-- Generated by scripts/generate_projectile_ballistics.py; do not edit.\nreturn ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale generated projectile ballistics domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
