"""Generate research/docs/projectile-components-F5FEE03DCFDB.md, the human-readable projectile component catalogue, from
research/projectile-components-F5FEE03DCFDB.json (scripts/research_projectile_components.py).
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / 'research/projectile-components-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'research/docs/projectile-components-F5FEE03DCFDB.md'
TITLES = {'visual': 'Visual components', 'damage': 'Direct-damage components',
    'impact_explosion': 'Impact-explosion components', 'ballistics': 'Ballistic profiles'}
LIVE = {'observed': 'OBSERVED live on a Runtime-owned row', 'verified': 'VERIFIED live on a Runtime-owned row',
    'untested_on_hybrid_rows': 'live-proven on native rows only; not yet live-tested on a Runtime-owned row',
    'untested': 'not yet live-tested'}


def donors(group, unitless=False) -> str:
    items = group['unitlessDonors'] if unitless else group['donors']
    names = sorted({d['name'] for d in items})
    return ', '.join(names) if names else '-'


def packages(group) -> str:
    return ', '.join('`%s`' % p['name'] for p in group['packages']) or '-'


def damage_text(definition) -> str:
    if not definition:
        return 'none'
    statuses = ', '.join('%s %g' % (s['status'], s['strength']) for s in definition['statuses'])
    return '%d / %d, AP %s%s' % (definition['standard'], definition['durable'],
        '/'.join(str(v) for v in definition['armorPenetration']), (', ' + statuses) if statuses else '')


def explosion_text(definition) -> str:
    if not definition:
        return 'none'
    extra = []
    if definition.get('volume'):
        extra.append('volume %s %gs' % (definition['volume'], definition['volumeSeconds'] or 0))
    if definition.get('submunition'):
        extra.append('submunition type %d' % definition['submunition'])
    if definition.get('arc'):
        extra.append('arc %d' % definition['arc'])
    return 'type %d: radii %s m, damage %s%s' % (definition['type'], '/'.join('%g' % r for r in definition['radii']),
        damage_text(definition['damage']), ('; ' + ', '.join(extra)) if extra else '')


def values_text(cid, group) -> str:
    v = group['values']
    if cid == 'visual':
        return 'effect %s, alternate %s, parameter %g, secondary %s, record %s' % (v['spawn_effect'],
            v['spawn_effect_alternate'], v['spawn_effect_parameter'], v['spawn_effect_secondary'],
            v['spawn_effect_record'])
    if cid == 'damage':
        return 'DamageInfoType %d: %s' % (v['direct_damage'], damage_text(group['definition']))
    if cid == 'impact_explosion':
        return explosion_text(group['definition'])
    return ('%g mm, %g m/s, %g g, drag %g, gravity %g, lifetime variance %g, penetration slowdown %g' % (
        v['diameter'], v['speed'], v['mass'], v['drag'], v['gravity'], v['lifetime_variance'],
        v['penetration_slowdown']))


def build() -> str:
    data = json.loads(RESEARCH.read_text(encoding='utf-8'))
    s = data['summary']
    lines = ['# Projectile component catalogue (build %s)' % data['build'], '',
        'Generated by `scripts/generate_projectile_catalogue_report.py` from `%s`; do not edit.' % RESEARCH.name, '',
        'Every vanilla ProjectileSettings row split into the hybrid-row components a Runtime-owned custom projectile '
        'can take from it (`docs/custom-projectile-rows.md`). A component copies exactly the members its descriptor '
        'owns, all COPIED_AT_SPAWN (hybrid-safe by the member policy); everything else stays the base row\'s. '
        'Identical values are grouped. A source can be a donor only when it is an established projectile output '
        'with a known package (`runtime donor`); other rows are listed by type.', '',
        '| Rows | Live rows matching the datalibrary | Rows with an identity | Rows with a runtime donor | '
        'Runtime donors | Rows with a unit |', '| --- | --- | --- | --- | --- | --- |',
        '| %d | %d | %d | %d | %d | %d |' % (s['rows'], s['liveRowsMatchingDatalibrary'], s['rowsWithIdentity'],
            s['rowsWithRuntimeDonor'], s['runtimeDonors'], s['rowsWithUnit']), '',
        '| Component | Unique values (all rows) | Unique values with a runtime donor |', '| --- | --- | --- |']
    for cid, title in TITLES.items():
        lines.append('| %s | %d | %d |' % (data['components'][cid]['descriptor']['name'], s['unique'][cid],
            s['uniqueAmongRuntimeDonors'][cid]))
    lines += ['', 'Unit-less visuals with a runtime donor (usable on a unit-less base such as the LAS-58 Talon): '
        '%d.' % s['unitlessVisualsAmongRuntimeDonors'], '']
    for cid, title in TITLES.items():
        component = data['components'][cid]
        d = component['descriptor']
        members = ', '.join('+0x%X %s' % (m['offset'], m['label']) for m in component['members'])
        lines += ['## %s (%s)' % (title, d['name']), '',
            '- Owns: %s (all COPIED_AT_SPAWN: hybrid-safe by the member policy).' % members,
            '- Meaning: %s.' % d['meaning'],
            '- Assets: %s.' % ('the donor\'s package must be resident' if d['assets'] == 'donor' else 'none (numbers)'),
            '- Constraints: %s.' % ('; '.join(d['constraints']) if d['constraints'] else 'none'),
            '- Evidence: %s.' % d['evidence'], '- Live: %s.' % LIVE.get(d['live'], d['live']), '']
        usable = [g for g in component['groups'] if g['donors'] and not g['none']]
        header = '| Donor (source projectile) | Types | Values | Packages |'
        if cid == 'visual':
            header = '| Donor (source projectile) | Types | Unit-less donors | Values | Packages |'
        lines += ['### With a runtime donor (%d)' % len(usable), '', header,
            '| --- | --- | --- | --- | --- |' if cid == 'visual' else '| --- | --- | --- | --- |']
        for group in usable:
            types = ', '.join(str(t) for t in group['types'])
            if cid == 'visual':
                lines.append('| %s | %s | %s | %s | %s |' % (donors(group), types, donors(group, True),
                    values_text(cid, group), packages(group)))
            else:
                lines.append('| %s | %s | %s | %s |' % (donors(group), types, values_text(cid, group),
                    packages(group)))
        others = [g for g in component['groups'] if not g['donors'] and not g['none']]
        none = [g for g in component['groups'] if g['none']]
        lines += ['', '### Without a runtime donor (%d)' % len(others), '',
            'Rows with no established output or no known package (for example enemy and mission projectiles). '
            'Types: %s.' % ', '.join(str(t) for t in sorted(t for g in others for t in g['types'])) if others
            else 'None.']
        if none:
            lines += ['', 'No value (%s): types %s.' % ('none' if cid != 'visual' else 'no spawn effect',
                ', '.join(str(t) for g in none for t in g['types']))]
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def generate(check=False):
    body = build()
    if check:
        return [] if OUTPUT.exists() and OUTPUT.read_text(encoding='utf-8') == body else [OUTPUT.name]
    OUTPUT.parent.mkdir(exist_ok=True)
    OUTPUT.write_text(body, encoding='utf-8', newline='\n')
    return [OUTPUT.name]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    stale = generate(parser.parse_args().check)
    print(', '.join(stale) or 'up to date')
