"""Generate domains/ui_fonts.lua and the Runtime-owned FS Sinclair engine fonts (scripts/hd2_font.py) from the installed
game: the font names the custom stratagem panel draws with, their metrics (em, cap height, ascent, descent, line
height) and every glyph's advance at the em size (the panel measures text with them), and the SHA-256 of each built
resource. The resources themselves are cached in build/.font-cache (keyed by this domain's digests); the Runtime build
(scripts/build_release.py runtime_fonts) packs them into the Runtime's own archive and refuses resources whose digests
differ from this domain. Also monaco's metrics (the fallback font). Read-only: nothing is written to the game.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import pickle
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402
import hd2_font  # noqa: E402

OUTPUT = 'domains/ui_fonts.lua'
CACHE = ROOT / 'build/.font-cache'
ROLES = {'title': 'medium', 'body': 'regular'}


def _digest(resources: dict) -> str:
    h = hashlib.sha256()
    for key in sorted(resources):
        main, gpu = resources[key]
        h.update(struct.pack('<QQ', *key) + hashlib.sha256(main).digest() + hashlib.sha256(gpu).digest())
    return h.hexdigest()


def build_all(src: dict) -> tuple[dict, dict]:
    """(the domain data, {(type, hash): parts} of both fonts) from the game's fonts."""
    fonts, resources = {}, {}
    for role, source in ROLES.items():
        out = hd2_font.build_font(src['ttf'][source], hd2_font.NAMES[source], src['monaco_material'])
        resources.update(out['resources'])
        r = out['report']
        fonts[role] = {'name': r['name'], 'source': 'FS Sinclair' + (' Medium' if source == 'medium' else ''),
            'em': r['em'], 'cap': r['capHeight'], 'ascent': r['ascent'], 'descent': r['descent'],
            'line': r['ascent'] + r['descent'], 'glyphs': r['glyphs'],
            'advances': {cp: round(rec[6], 3) for cp, rec in sorted(out['records'].items())},
            'sha256': r['sha256']}
    mono = hd2_font.parse_font(src['monaco_font'])
    fonts['monaco'] = {'name': 'core/performance_hud/monaco', 'em': mono['em'], 'cap': 33.0, 'ascent': 37.0,
        'descent': 8.0, 'line': mono['line'],
        'advances': {cp: round(rec[6], 3) for cp, rec in sorted(mono['glyphs'].items())}}
    domain = {'source': {'generator': 'scripts/generate_ui_fonts.py', 'archive': hd2_font.FONT_ARCHIVE,
        'ttf': {k: '0x%016X' % v for k, v in hd2_font.SOURCES.items()}, 'resources': _digest(resources)},
        'types': {'font': '0x%016X' % hd2_font.FONT_TYPE, 'material': '0x%016X' % hd2_font.MATERIAL_TYPE},
        'fonts': fonts}
    return domain, resources


def game_sources() -> dict:
    src = hd2_font.game_fonts()
    import hd2_game_data
    data = hd2_game_data.Data()
    found = data.find({(hd2_font.MONACO, hd2_font.FONT_TYPE)})
    archive, main, _s, _g = found[(hd2_font.MONACO, hd2_font.FONT_TYPE)]
    src['monaco_font'] = data.read(archive, main)
    return src


def cached_resources(digest: str):
    path = CACHE / ('fonts-' + digest[:32] + '.pkl')
    if path.is_file():
        resources = pickle.loads(path.read_bytes())
        if _digest(resources) == digest:
            return resources
    return None


def store(resources: dict) -> None:
    CACHE.mkdir(parents=True, exist_ok=True)
    (CACHE / ('fonts-' + _digest(resources)[:32] + '.pkl')).write_bytes(pickle.dumps(resources))


def outputs() -> tuple[dict, dict]:
    domain, resources = build_all(game_sources())
    store(resources)
    body = '-- Generated by scripts/generate_ui_fonts.py from the installed game; do not edit.\nreturn ' + lua(domain) + '\n'
    return {OUTPUT: body}, resources


def generate(check=False):
    files, _resources = outputs()
    stale = []
    for name, body in files.items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale generated UI font domain: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
