"""Generate domains/text_resources.lua: the game's text registry, its table format and languages, and the pinned code the
Runtime proves before it registers its own text table (runtime/text_resources.lua, docs/custom-text.md), from
research/stratagem-text-F5FEE03DCFDB.json.

The pins are re-proven in game before the first registration of each loaded game; one mismatch refuses all custom
text.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from reference_format import lua  # noqa: E402
import hd2_text  # noqa: E402

RESEARCH = ROOT / 'research/stratagem-text-F5FEE03DCFDB.json'
OUTPUT = ROOT / 'domains/text_resources.lua'


def build() -> dict:
    research = json.loads(RESEARCH.read_text(encoding='utf-8'))
    if research['writes'] or research['protectionChanges']:
        raise ValueError('text research must be read-only')
    if any(research['pinnedBytesMismatchPerSnapshot'].values()):
        raise ValueError('a pinned text instruction differs between retained snapshots')
    profile = (ROOT / 'schemas/current.lua').read_text(encoding='utf-8')
    if research['exe']['sha256'] not in profile or research['gameDll']['sha256'] not in profile:
        raise ValueError('the text research covers another build than schemas/current.lua')
    fmt = research['format']
    if fmt['rebuiltByteForByte'] != fmt['vanillaTables'] or fmt['languagesPerTable'] != [[1, fmt['vanillaTables']]]:
        raise ValueError('the text table format is not reproduced for every game table')
    registry = research['registry']
    if (registry['gameSlotUseFunctions']['add'] != ['0x12FED80', '0x12FEDC0']
            or registry['gameSlotUseFunctions']['clear'] != ['0x12FEDC0']
            or registry['gameSlotUseFunctions']['set language'] != ['0x12FF050']):
        raise ValueError('the game registers text outside its language registration')
    if len({tuple((t['resource'], t['ids']) for t in s['tables']) for s in research['snapshots']}) != 1             or any(s['currentLanguage'] != 'us' for s in research['snapshots']):
        raise ValueError('the retained snapshots do not agree on the English game text tables')
    if any(s['languageTable'] != list(hd2_text.LANGUAGES) or s['capacity'] <= s['count'] for s in research['snapshots']):
        raise ValueError('the language table or the registry headroom is not proven in every snapshot')
    pins = [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes'], 'module': 'exe'}
        for rows in research['pins']['exe'].values() for pin in rows]
    pins += [{'label': pin['role'], 'rva': pin['rva'], 'hex': pin['bytes'], 'module': 'game'}
        for rows in research['pins']['game'].values() for pin in rows]
    layout = registry['layout']
    return {'source': {'research': RESEARCH.name, 'build': research['build'], 'exeSha256': research['exe']['sha256'],
            'gameDllSha256': research['gameDll']['sha256']},
        # [exe + global] = the registry: {u32 count, u32 capacity, table pointers, allocator}.
        'registry': {'global': int(registry['global'], 16), 'count': layout['count'], 'capacity': layout['capacity'],
            'tables': layout['tables']},
        'currentLanguage': int(registry['currentLanguage'], 16),
        'table': {'magic': hd2_text.MAGIC, 'languages': 4, 'ids': 8, 'header': 12},
        # The game's text languages (its language table order) and their hashes; 'us' is the default.
        'languages': [{'code': item['code'], 'hash': int(item['hash'], 16)} for item in research['languages']],
        'defaultLanguage': 'us',
        # Bounds: what the Runtime reads (a changed or busy registry, never a guess) and what it builds.
        'limits': {'registryCapacity': 64, 'tableLanguages': 32, 'tableIds': 200000, 'texts': 256, 'textBytes': 512,
            'tableBytes': 65536, 'tables': 16},
        # The game's own tables in English, by id count (every retained snapshot is English): the REGISTRY_FULL
        # diagnostic names a one-language 'us' table by its size (0.30.2, read-only).
        # 0.30.2: how a full registry grows (the add's own policy and allocator; research registry.growth): a larger
        # array from the registry allocator (registry +0x10, vtable +0x30), the old one kept allocated.
        'growth': {'allocator': 0x10, 'vtable': int(registry['growth']['allocatorVtable'], 16),
            'allocate': int(registry['growth']['allocate'], 16), 'minimum': 8},
        'knownTables': [{'resource': table['resource'].removesuffix('_us'), 'ids': table['ids']}
            for table in research['snapshots'][0]['tables']],
        'pins': sorted(pins, key=lambda pin: (pin['module'], pin['rva']))}


def outputs() -> dict[str, str]:
    return {'domains/text_resources.lua': '-- Generated by scripts/generate_text_resources.py; do not edit.\n'
        'return ' + lua(build()) + '\n'}


def generate(check=False):
    stale = []
    for name, body in outputs().items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            stale.append(name)
            if not check:
                path.write_text(body, encoding='utf-8', newline='\n')
    if check and stale:
        raise RuntimeError('Stale text resources: ' + ', '.join(stale))
    return stale


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    print(', '.join(generate(parser.parse_args().check)) or 'up to date')
